import Link from "next/link";
import { GuideArticle } from "@/components/guide-article";

const title = "How to Price Window Cleaning Jobs | zaps.work";
const description = "A practical guide to pricing window cleaning from window type, access, crew time, add-ons, minimum fees, margin, and tax.";

export default function Page() {
  return <GuideArticle title={title} description={description} published="2026-07-14" updated="2026-07-14" readingTime="7 min read" slug="how-to-price-window-cleaning-jobs" toolHref="/tools/window-cleaning-quote" toolLabel="Open calculator" toc={[{ id: "scope", label: "Count the serviceable glass" }, { id: "time", label: "Turn scope into crew time" }, { id: "price", label: "Set a profitable visit price" }]} faq={[{ question: "Should window cleaning be priced per window?", answer: "A per-window count is useful for estimating time, but your customer quote should also account for access, travel, equipment, and minimum service fees." }, { question: "How should second-floor windows be priced?", answer: "Use a consistent access factor based on real setup and ladder time. Keep the resulting customer quote clear rather than adding an unexplained surcharge." }]}><p className="guide-lead">A profitable window-cleaning quote starts with the work that actually changes crew time: glass type, cleaning sides, access, condition, screens, and tracks. A simple window count alone is rarely enough.</p><div className="guide-callout"><strong>The short formula</strong><code>Quote = max((labor + supplies + travel + overhead) ÷ (1 − target margin), minimum fee)</code></div><h2 id="scope">1. Count the serviceable glass</h2><p>Separate standard windows, large glass or patio doors, and skylights. Define whether the customer wants exterior-only or inside-and-exterior cleaning. Screens and deep track cleaning should remain separate add-ons, because they add predictable handling time and make the scope easier to confirm.</p><h2 id="time">2. Use your own crew production</h2><p>Start with minutes per window type from completed jobs. Set the second-floor, high-access, and heavy-soil factors from your own completed work; the calculator exposes all three so the estimate reflects your actual setup, ladder, and cleaning time. Record these as consistent operating assumptions—not vague premium labels—so quotes remain comparable from job to job.</p><h2 id="price">3. Protect the short visit</h2><p>Travel, loading, water-fed poles, squeegees, towels, communication, and setup still exist on small jobs. Add supplies, travel, overhead, target margin, and a minimum fee before applying tax. The <Link href="/tools/window-cleaning-quote">window cleaning quote calculator</Link> keeps the customer-facing service line equal to the pre-tax subtotal, with tax shown only once at the bottom.</p></GuideArticle>;
}
