import { z } from "zod";
import { convertCurrencyAmount, type Currency } from "../currency";

export const cncInputSchema = z.object({ quantity: z.number().int().min(1).max(100_000), stockVolumeCm3: z.number().finite().min(0).max(10_000_000), materialCostPerCm3: z.number().finite().min(0).max(1_000_000), scrapPercent: z.number().finite().min(0).max(100), programmingHours: z.number().finite().min(0).max(10_000), setupHours: z.number().finite().min(0).max(10_000), cycleMinutes: z.number().finite().min(0).max(100_000), inspectionMinutes: z.number().finite().min(0).max(100_000), machineRate: z.number().finite().min(0).max(1_000_000), laborRate: z.number().finite().min(0).max(1_000_000), toolingCost: z.number().finite().min(0).max(1_000_000), finishingCost: z.number().finite().min(0).max(1_000_000), targetMargin: z.number().finite().min(0).max(95), minimumFee: z.number().finite().min(0).max(1_000_000), taxRate: z.number().finite().min(0).max(100) });
export type CncInput = z.infer<typeof cncInputSchema>;
const clamp = (value: number, min: number, max: number, fallback = min) => Math.min(max, Math.max(min, Number.isFinite(value) ? value : fallback));
export function createDefaultCncInput(currency: Currency = "USD"): CncInput { return convertCncCurrency({ quantity: 10, stockVolumeCm3: 150, materialCostPerCm3: .04, scrapPercent: 15, programmingHours: 2, setupHours: 1.5, cycleMinutes: 18, inspectionMinutes: 3, machineRate: 85, laborRate: 38, toolingCost: 35, finishingCost: 0, targetMargin: 35, minimumFee: 300, taxRate: 0 }, "USD", currency); }
export function convertCncCurrency(input: CncInput, from: Currency, to: Currency): CncInput { if (from === to) return input; const convert = (value: number) => convertCurrencyAmount(value, from, to); return { ...input, materialCostPerCm3: convert(input.materialCostPerCm3), machineRate: convert(input.machineRate), laborRate: convert(input.laborRate), toolingCost: convert(input.toolingCost), finishingCost: convert(input.finishingCost), minimumFee: convert(input.minimumFee) }; }
export function calculateCncQuote(raw: CncInput) { const input = cncInputSchema.parse({ ...raw, quantity: Math.round(clamp(raw.quantity, 1, 100_000, 1)), stockVolumeCm3: clamp(raw.stockVolumeCm3, 0, 10_000_000), materialCostPerCm3: clamp(raw.materialCostPerCm3, 0, 1_000_000), scrapPercent: clamp(raw.scrapPercent, 0, 100), programmingHours: clamp(raw.programmingHours, 0, 10_000), setupHours: clamp(raw.setupHours, 0, 10_000), cycleMinutes: clamp(raw.cycleMinutes, 0, 100_000), inspectionMinutes: clamp(raw.inspectionMinutes, 0, 100_000), machineRate: clamp(raw.machineRate, 0, 1_000_000), laborRate: clamp(raw.laborRate, 0, 1_000_000), toolingCost: clamp(raw.toolingCost, 0, 1_000_000), finishingCost: clamp(raw.finishingCost, 0, 1_000_000), targetMargin: clamp(raw.targetMargin, 0, 95), minimumFee: clamp(raw.minimumFee, 0, 1_000_000), taxRate: clamp(raw.taxRate, 0, 100) }); const materialCost = input.quantity * input.stockVolumeCm3 * input.materialCostPerCm3 * (1 + input.scrapPercent / 100); const machineHours = input.setupHours + input.quantity * input.cycleMinutes / 60; const machineCost = machineHours * input.machineRate; const laborHours = input.programmingHours + input.setupHours + input.quantity * input.inspectionMinutes / 60; const laborCost = laborHours * input.laborRate; const directCost = materialCost + machineCost + laborCost + input.toolingCost + input.finishingCost; const marginFloor = directCost / Math.max(.05, 1 - input.targetMargin / 100); const subtotal = Math.max(marginFloor, input.minimumFee); const tax = subtotal * input.taxRate / 100; const total = subtotal + tax; const profit = subtotal - directCost; return { input, materialCost, machineHours, machineCost, laborHours, laborCost, directCost, marginFloor, subtotal, tax, total, profit, margin: subtotal > 0 ? profit / subtotal : 0, unitPrice: total / input.quantity }; }
