import { z } from "zod";
import { convertCurrencyAmount, type Currency } from "../currency";

export const freelanceInputSchema = z.object({ hours: z.number().finite().min(0).max(10_000), hourlyRate: z.number().finite().min(0).max(1_000_000), revisions: z.number().int().min(0).max(100), revisionHours: z.number().finite().min(0).max(1_000), fixedCosts: z.number().finite().min(0).max(1_000_000), rushPercent: z.number().finite().min(0).max(200), targetMargin: z.number().finite().min(0).max(95), minimumFee: z.number().finite().min(0).max(1_000_000), taxRate: z.number().finite().min(0).max(100) });
export type FreelanceInput = z.infer<typeof freelanceInputSchema>;
const clamp = (value: number, min: number, max: number, fallback = min) => Math.min(max, Math.max(min, Number.isFinite(value) ? value : fallback));
export function createDefaultFreelanceInput(currency: Currency = "USD"): FreelanceInput { return convertFreelanceCurrency({ hours: 12, hourlyRate: 65, revisions: 2, revisionHours: 1, fixedCosts: 25, rushPercent: 0, targetMargin: 35, minimumFee: 250, taxRate: 0 }, "USD", currency); }
export function convertFreelanceCurrency(input: FreelanceInput, from: Currency, to: Currency): FreelanceInput { if (from === to) return input; const convert = (value: number) => convertCurrencyAmount(value, from, to); return { ...input, hourlyRate: convert(input.hourlyRate), fixedCosts: convert(input.fixedCosts), minimumFee: convert(input.minimumFee) }; }
export function calculateFreelanceQuote(raw: FreelanceInput) { const input = freelanceInputSchema.parse({ ...raw, hours: clamp(raw.hours, 0, 10_000), hourlyRate: clamp(raw.hourlyRate, 0, 1_000_000), revisions: Math.round(clamp(raw.revisions, 0, 100)), revisionHours: clamp(raw.revisionHours, 0, 1_000), fixedCosts: clamp(raw.fixedCosts, 0, 1_000_000), rushPercent: clamp(raw.rushPercent, 0, 200), targetMargin: clamp(raw.targetMargin, 0, 95), minimumFee: clamp(raw.minimumFee, 0, 1_000_000), taxRate: clamp(raw.taxRate, 0, 100) }); const baseHours = input.hours + input.revisions * input.revisionHours; const laborCost = baseHours * input.hourlyRate; const directCost = laborCost + input.fixedCosts; const marginFloor = directCost / Math.max(.05, 1 - input.targetMargin / 100); const subtotal = Math.max(marginFloor * (1 + input.rushPercent / 100), input.minimumFee); const tax = subtotal * input.taxRate / 100; const total = subtotal + tax; const profit = subtotal - directCost; return { input, baseHours, laborCost, directCost, marginFloor, subtotal, tax, total, profit, margin: subtotal > 0 ? profit / subtotal : 0 }; }
