import { z } from "zod";
import { convertCurrencyAmount, type Currency } from "../currency";

export const lawnCareInputSchema = z.object({ area: z.number().finite().min(0).max(10_000_000), condition: z.enum(["light", "standard", "overgrown"]), productionRate: z.number().finite().min(.01).max(10_000_000), crewSize: z.number().int().min(1).max(100), laborRate: z.number().finite().min(0).max(1_000_000), equipmentCost: z.number().finite().min(0).max(1_000_000), travelCost: z.number().finite().min(0).max(1_000_000), addOnAmount: z.number().finite().min(0).max(1_000_000), overheadPercent: z.number().finite().min(0).max(100), targetMargin: z.number().finite().min(0).max(95), minimumFee: z.number().finite().min(0).max(1_000_000), taxRate: z.number().finite().min(0).max(100) });
export type LawnCareInput = z.infer<typeof lawnCareInputSchema>;
const clamp = (value: number, min: number, max: number, fallback = min) => Math.min(max, Math.max(min, Number.isFinite(value) ? value : fallback));
const conditionMultiplier = { light: .85, standard: 1, overgrown: 1.45 } as const;
export function createDefaultLawnCareInput(currency: Currency = "USD"): LawnCareInput { return convertLawnCareCurrency({ area: 5_000, condition: "standard", productionRate: 3_000, crewSize: 2, laborRate: 28, equipmentCost: 12, travelCost: 15, addOnAmount: 0, overheadPercent: 12, targetMargin: 35, minimumFee: 75, taxRate: 0 }, "USD", currency); }
export function convertLawnCareCurrency(input: LawnCareInput, from: Currency, to: Currency): LawnCareInput { if (from === to) return input; const convert = (value: number) => convertCurrencyAmount(value, from, to); return { ...input, laborRate: convert(input.laborRate), equipmentCost: convert(input.equipmentCost), travelCost: convert(input.travelCost), addOnAmount: convert(input.addOnAmount), minimumFee: convert(input.minimumFee) }; }
export function calculateLawnCareQuote(raw: LawnCareInput) { const input = lawnCareInputSchema.parse({ ...raw, area: clamp(raw.area, 0, 10_000_000), productionRate: clamp(raw.productionRate, .01, 10_000_000, 1), crewSize: Math.round(clamp(raw.crewSize, 1, 100, 1)), laborRate: clamp(raw.laborRate, 0, 1_000_000), equipmentCost: clamp(raw.equipmentCost, 0, 1_000_000), travelCost: clamp(raw.travelCost, 0, 1_000_000), addOnAmount: clamp(raw.addOnAmount, 0, 1_000_000), overheadPercent: clamp(raw.overheadPercent, 0, 100), targetMargin: clamp(raw.targetMargin, 0, 95), minimumFee: clamp(raw.minimumFee, 0, 1_000_000), taxRate: clamp(raw.taxRate, 0, 100) }); const crewHours = input.area / input.productionRate * conditionMultiplier[input.condition]; const laborCost = crewHours * input.crewSize * input.laborRate; const overheadCost = laborCost * input.overheadPercent / 100; const directCost = laborCost + overheadCost + input.equipmentCost + input.travelCost + input.addOnAmount; const marginFloor = directCost / Math.max(.05, 1 - input.targetMargin / 100); const subtotal = Math.max(marginFloor, input.minimumFee); const tax = subtotal * input.taxRate / 100; const total = subtotal + tax; const profit = subtotal - directCost; return { input, crewHours, laborCost, overheadCost, directCost, marginFloor, subtotal, tax, total, profit, margin: subtotal > 0 ? profit / subtotal : 0 }; }
