import type { Locale } from "@/lib/i18n/config";
import type { LocalizedGuideCopy } from "./types";

type TranslatedLocale = Exclude<Locale, "en">;

export const houseCleaningGuide: Record<TranslatedLocale, LocalizedGuideCopy> = {
  "zh-hant": {
    title: "居家清潔如何報價：人工時、成本與毛利指南", description: "依房屋面積、清潔類型、人工時、耗材、交通、附加服務、最低收費與毛利建立清潔報價。", readingTime: "閱讀約 9 分鐘", toolLabel: "開啟清潔報價工具",
    toc: [{ id: "scope", label: "定義範圍" }, { id: "hours", label: "估算人工時" }, { id: "costs", label: "加入成本" }, { id: "pricing", label: "設定價格" }, { id: "example", label: "計算實例" }, { id: "quote", label: "寫入報價" }],
    faq: [{ question: "居家清潔應按小時還是固定價格？", answer: "內部用清潔人工時與成本計算；範圍清楚時，向客戶提供固定價格通常更容易理解。" }, { question: "如何估算清潔需要多久？", answer: "用可清潔面積除以自己的實際生產率，再依標準、深度或搬家清潔與現場難度調整。" }, { question: "兩人工作兩小時是多少人工時？", answer: "是四個清潔人工時。團隊人數會改變現場時長，但不會減少總人工成本。" }, { question: "定期清潔可以打折嗎？", answer: "可以，但只有重複拜訪真的降低銷售、設定或清潔時間時才合理，并要重新檢查折扣後毛利。" }],
    lead: "可持續的清潔報價應從工作範圍與總人工時開始，而不是直接複製當地均價。算清人工、營運、耗材、交通和附加服務後，再套用毛利與最低上門費。",
    formulaLabel: "核心公式", formula: "清潔報價 =（人工 + 營運分攤 + 耗材 + 交通 + 附加服務成本）÷（1 − 目標毛利率）", formulaBody: "套用首次清潔附加費與週期折扣後，再與最低服務費比較并加入適用稅額。",
    sections: [{ id: "scope", title: "1. 先定義清潔範圍", paragraphs: ["記錄房屋類型、可清潔面積、臥室、衛浴、清潔類型、頻率與整體狀況。面積相同的房屋可能因雜物、油污、寵物毛髮、樓梯或進出限制而需要不同工時。", "說明是否包含烤箱、冰箱、窗戶、櫥櫃內部、洗衣、家具移動和清運，避免客戶把未列項目視為免費包含。"] }, { id: "hours", title: "2. 用生產率估算總清潔人工時", paragraphs: ["生產率應來自自己已完成的工作。總清潔人工時代表全隊工作量；兩人各工作兩小時等於四個人工時。", "深度與搬家清潔可用可調整係數增加基礎工時。有經驗的業者也可以直接輸入手工人工時。"], formula: "基礎人工時 = 面積 ÷ 生產率 × 清潔類型係數 × 難度係數" }, { id: "costs", title: "3. 加入全部工作成本", paragraphs: ["人工成本應包含薪資與雇主負擔。每人工時營運分攤可涵蓋保險、軟體、管理、設備、車輛和不可計費時間。", "另外加入耗材、交通、停車與附加服務增加的時間。固定價格附加項仍要保留其人工成本。"] }, { id: "pricing", title: "4. 套用毛利、最低收費與折扣", paragraphs: ["目標毛利不是成本加價率。用總成本除以一減目標毛利率，才能得到需要的價格。", "最低服務費用來保護小工作；週期折扣與首次附加費要反映真實資源差異，并在套用後檢查實際毛利。"], formula: "目標價格 = 工作成本 ÷（1 − 目標毛利率）" }, { id: "example", title: "5. 居家清潔報價實例", paragraphs: ["1,800 平方英尺的標準清潔，生產率 500 平方英尺／人工時，需要 3.6 人工時。兩人團隊約在現場 1.8 小時。", "人工 86.40、營運分攤 36、耗材 12、交通 15，工作成本 149.40。30% 目標毛利的未稅報價為 213.43。"] }, { id: "quote", title: "6. 寫出不易爭議的客戶報價", paragraphs: ["列出房屋、清潔類型、頻率、包含範圍、附加服務、客戶準備、排除事項、總價、稅額、有效期限和預計服務時間。", "不要保證無法預先判斷的污漬結果。現場狀況明顯不同時，應先取得範圍與價格調整同意。"] }],
    checklistTitle: "清潔報價檢查清單", checklist: ["確認房屋、面積、類型、頻率與狀況。", "用自身資料設定生產率。", "分清總人工時與現場時長。", "加入人工、營運、耗材與交通。", "逐項計算附加服務。", "套用正確毛利公式。", "比較最低服務費并檢查折扣後毛利。", "寫明範圍、排除事項與有效期限。"],
  },
  de: {
    title: "Hausreinigung kalkulieren: Stunden, Kosten und Marge", description: "Erstelle ein Reinigungsangebot aus Fläche, Art, Reinigerstunden, Material, Anfahrt, Zusätzen, Mindestpreis und Marge.", readingTime: "9 Min. Lesezeit", toolLabel: "Reinigungsrechner öffnen",
    toc: [{ id: "scope", label: "Umfang" }, { id: "hours", label: "Stunden" }, { id: "costs", label: "Kosten" }, { id: "pricing", label: "Preis" }, { id: "example", label: "Beispiel" }, { id: "quote", label: "Angebot" }], faq: [{ question: "Stunden- oder Festpreis?", answer: "Kalkuliere intern mit Reinigerstunden und Kosten; bei klarem Umfang ist ein Festpreis für Kunden meist verständlicher." }, { question: "Wie schätze ich die Dauer?", answer: "Teile die Fläche durch deine gemessene Leistung und passe Reinigungsart und Schwierigkeit an." }, { question: "Zwei Personen für zwei Stunden?", answer: "Das sind vier Reinigerstunden und etwa zwei Stunden vor Ort." }, { question: "Sind Rabatte für Wiederholungen sinnvoll?", answer: "Nur wenn Wiederholungen wirklich Verkauf, Einrichtung oder Reinigung verkürzen. Prüfe danach die tatsächliche Marge." }],
    lead: "Eine nachhaltige Reinigungskalkulation beginnt bei Umfang und Reinigerstunden, nicht bei einem kopierten Marktpreis. Danach folgen Arbeit, Gemeinkosten, Material, Anfahrt, Zusätze, Marge und Mindestpreis.", formulaLabel: "Kernformel", formula: "Angebot = (Arbeit + Gemeinkosten + Material + Anfahrt + Zusätze) ÷ (1 − Zielmarge)", formulaBody: "Zuschlag und Intervallrabatt anwenden, mit dem Mindestpreis vergleichen und gegebenenfalls Steuer ergänzen.",
    sections: [{ id: "scope", title: "1. Umfang definieren", paragraphs: ["Erfasse Objekttyp, Fläche, Zimmer, Bäder, Reinigungsart, Häufigkeit und Zustand. Gleiche Flächen können durch Unordnung, Fett, Tierhaare, Treppen oder Zugang sehr unterschiedliche Zeiten benötigen.", "Nenne Backofen, Kühlschrank, Fenster, Schränke, Wäsche, Möbel und Entsorgung ausdrücklich als enthalten oder ausgeschlossen."] }, { id: "hours", title: "2. Reinigerstunden aus Leistung schätzen", paragraphs: ["Die Leistung sollte aus abgeschlossenen Aufträgen stammen. Zwei Personen für zwei Stunden sind vier Reinigerstunden.", "Grund- und Umzugsreinigung erhalten anpassbare Faktoren; erfahrene Anbieter können Stunden manuell eingeben."], formula: "Stunden = Fläche ÷ Leistung × Artfaktor × Schwierigkeitsfaktor" }, { id: "costs", title: "3. Alle Kosten ergänzen", paragraphs: ["Arbeit umfasst Lohn und Arbeitgeberkosten. Gemeinkosten je Stunde können Versicherung, Software, Verwaltung, Geräte, Fahrzeug und nicht abrechenbare Zeit finanzieren.", "Ergänze Material, Anfahrt, Parken und Zeit der Zusatzleistungen."] }, { id: "pricing", title: "4. Marge, Mindestpreis und Rabatt", paragraphs: ["Teile Kosten durch eins minus Zielmarge. Ein Mindestpreis schützt kleine Aufträge; Rabatte müssen echte Einsparungen abbilden."], formula: "Zielpreis = Auftragskosten ÷ (1 − Zielmarge)" }, { id: "example", title: "5. Beispiel", paragraphs: ["1.800 sq ft bei 500 sq ft je Reinigerstunde ergeben 3,6 Stunden. Zwei Personen sind etwa 1,8 Stunden vor Ort.", "Arbeit 86,40, Gemeinkosten 36, Material 12 und Anfahrt 15 ergeben 149,40. Bei 30% Marge beträgt das Nettoangebot 213,43."] }, { id: "quote", title: "6. Klares Kundenangebot", paragraphs: ["Nenne Objekt, Reinigungsart, Häufigkeit, enthaltene Leistungen, Kundenvorbereitung, Ausschlüsse, Gesamtpreis, Steuer, Gültigkeit und Terminfenster."] }], checklistTitle: "Checkliste Reinigung", checklist: ["Objekt, Fläche, Art, Häufigkeit und Zustand prüfen.", "Eigene Leistung nutzen.", "Reinigerstunden und Vor-Ort-Zeit trennen.", "Arbeit, Gemeinkosten, Material und Anfahrt ergänzen.", "Zusätze kalkulieren.", "Marge korrekt anwenden.", "Mindestpreis und Rabatt prüfen.", "Umfang und Gültigkeit dokumentieren."],
  },
  ja: {
    title: "ハウスクリーニングの見積もり方法：人時・原価・利益率", description: "面積、清掃タイプ、清掃人時、用品、移動、追加サービス、最低料金と利益率から見積もります。", readingTime: "読了約9分", toolLabel: "清掃見積もり計算機を開く",
    toc: [{ id: "scope", label: "範囲" }, { id: "hours", label: "人時" }, { id: "costs", label: "原価" }, { id: "pricing", label: "価格" }, { id: "example", label: "例" }, { id: "quote", label: "見積書" }], faq: [{ question: "時間制と固定価格のどちら？", answer: "内部では清掃人時と原価で計算し、範囲が明確なら顧客には固定価格を提示します。" }, { question: "作業時間はどう見積もりますか？", answer: "面積を自社実績の作業効率で割り、清掃タイプと難易度で調整します。" }, { question: "2人で2時間は何人時？", answer: "4清掃人時で、現場時間は約2時間です。" }, { question: "定期割引は必要ですか？", answer: "再訪で営業、準備、清掃時間が実際に減る場合だけ適用し、割引後の利益率を確認します。" }],
    lead: "持続可能な清掃価格は相場のコピーではなく、範囲と総清掃人時から作ります。人件費、間接費、用品、移動、追加サービスを計算して利益率と最低料金を適用します。", formulaLabel: "基本式", formula: "見積価格 =（人件費 + 間接費 + 用品 + 移動 + 追加作業）÷（1 − 目標利益率）", formulaBody: "初回加算と定期割引を適用し、最低料金と比較して必要な税を加えます。",
    sections: [{ id: "scope", title: "1. 清掃範囲を定義する", paragraphs: ["物件、面積、部屋、浴室、清掃タイプ、頻度、状態を記録します。同じ面積でも物量、油、ペット毛、階段、アクセスで時間は変わります。", "オーブン、冷蔵庫、窓、収納内部、洗濯、家具移動を含むか明記します。"] }, { id: "hours", title: "2. 作業効率から清掃人時を計算する", paragraphs: ["作業効率は完了した実績から設定します。2人が2時間なら4人時です。", "徹底清掃や入退去清掃は調整係数を使い、経験者は手動入力もできます。"], formula: "基本人時 = 面積 ÷ 作業効率 × タイプ係数 × 難易度係数" }, { id: "costs", title: "3. すべての原価を加える", paragraphs: ["人件費には賃金と雇用負担を含めます。間接費は保険、ソフト、管理、設備、車両、非請求時間を支えます。", "用品、移動、駐車、追加サービス時間も加えます。"] }, { id: "pricing", title: "4. 利益率、最低料金、割引", paragraphs: ["原価を1から目標利益率を引いた値で割ります。最低料金は小規模案件を守り、割引は実際の節約を反映させます。"], formula: "目標価格 = 作業原価 ÷（1 − 目標利益率）" }, { id: "example", title: "5. 計算例", paragraphs: ["1,800平方フィートを効率500で清掃すると3.6人時、2人なら現場1.8時間です。", "人件費86.40、間接費36、用品12、移動15で原価149.40。利益率30%の税抜見積は213.43です。"] }, { id: "quote", title: "6. 顧客向け見積書", paragraphs: ["物件、清掃タイプ、頻度、含まれる作業、顧客準備、対象外、合計、税、有効期限と予定時間を記載します。"] }], checklistTitle: "清掃見積チェックリスト", checklist: ["物件、面積、タイプ、頻度、状態を確認。", "自社実績の作業効率を使用。", "総人時と現場時間を区別。", "人件費、間接費、用品、移動を追加。", "追加サービスを計算。", "利益率式を適用。", "最低料金と割引後利益率を確認。", "範囲と有効期限を記載。"],
  },
  es: {
    title: "Cómo presupuestar limpieza doméstica: horas, costes y margen", description: "Crea un presupuesto con área, tipo de limpieza, horas-persona, suministros, viaje, extras, mínimo y margen.", readingTime: "9 min de lectura", toolLabel: "Abrir calculadora de limpieza",
    toc: [{ id: "scope", label: "Alcance" }, { id: "hours", label: "Horas" }, { id: "costs", label: "Costes" }, { id: "pricing", label: "Precio" }, { id: "example", label: "Ejemplo" }, { id: "quote", label: "Presupuesto" }], faq: [{ question: "¿Por hora o precio fijo?", answer: "Calcula internamente con horas-persona y costes; si el alcance es claro, ofrece un precio fijo." }, { question: "¿Cómo estimo la duración?", answer: "Divide el área por tu productividad real y ajusta tipo y dificultad." }, { question: "¿Dos personas durante dos horas?", answer: "Son cuatro horas-persona y unas dos horas en el lugar." }, { question: "¿Descuento recurrente?", answer: "Solo si las visitas repetidas reducen ventas, preparación o tiempo; revisa el margen final." }],
    lead: "Un precio sostenible comienza con alcance y horas-persona, no con una media de mercado. Añade trabajo, gastos, suministros, viaje y extras antes del margen y mínimo.", formulaLabel: "Fórmula principal", formula: "Presupuesto = (trabajo + gastos + suministros + viaje + extras) ÷ (1 − margen)", formulaBody: "Aplica recargo y descuento, compara con el mínimo y añade impuestos cuando correspondan.",
    sections: [{ id: "scope", title: "1. Define el alcance", paragraphs: ["Registra propiedad, área, habitaciones, baños, tipo, frecuencia y estado. Desorden, grasa, mascotas, escaleras y acceso cambian el tiempo.", "Indica horno, frigorífico, ventanas, armarios, lavandería y muebles como incluidos o excluidos."] }, { id: "hours", title: "2. Estima horas-persona", paragraphs: ["Usa productividad de trabajos terminados. Dos personas por dos horas son cuatro horas-persona.", "Ajusta limpieza profunda o mudanza y permite entrada manual."], formula: "Horas = área ÷ productividad × factor de tipo × dificultad" }, { id: "costs", title: "3. Añade todos los costes", paragraphs: ["Incluye salario y cargas, seguro, software, gestión, equipo, vehículo, suministros, viaje y tiempo de extras."] }, { id: "pricing", title: "4. Margen, mínimo y descuento", paragraphs: ["Divide el coste por uno menos el margen. El mínimo protege trabajos pequeños y el descuento debe reflejar ahorro real."], formula: "Precio = coste ÷ (1 − margen)" }, { id: "example", title: "5. Ejemplo", paragraphs: ["1.800 pies² a 500 por hora son 3,6 horas-persona y 1,8 horas con dos personas.", "Trabajo 86,40, gastos 36, suministros 12 y viaje 15 suman 149,40. Con margen 30%, el precio es 213,43."] }, { id: "quote", title: "6. Escribe el presupuesto", paragraphs: ["Incluye propiedad, tipo, frecuencia, alcance, extras, preparación, exclusiones, total, impuestos, validez y ventana de servicio."] }], checklistTitle: "Checklist de limpieza", checklist: ["Confirmar propiedad, área, tipo, frecuencia y estado.", "Usar productividad propia.", "Separar horas-persona y tiempo en sitio.", "Añadir trabajo, gastos, suministros y viaje.", "Calcular extras.", "Aplicar margen.", "Revisar mínimo y descuento.", "Documentar alcance y validez."],
  },
  fr: {
    title: "Comment chiffrer un ménage : heures, coûts et marge", description: "Créez un devis avec surface, type, heures-personnes, fournitures, trajet, options, minimum et marge.", readingTime: "9 min de lecture", toolLabel: "Ouvrir le calculateur de ménage",
    toc: [{ id: "scope", label: "Périmètre" }, { id: "hours", label: "Heures" }, { id: "costs", label: "Coûts" }, { id: "pricing", label: "Prix" }, { id: "example", label: "Exemple" }, { id: "quote", label: "Devis" }], faq: [{ question: "À l’heure ou au forfait ?", answer: "Calculez en interne avec heures-personnes et coûts ; si le périmètre est clair, proposez un forfait." }, { question: "Comment estimer la durée ?", answer: "Divisez la surface par votre rendement réel puis ajustez type et difficulté." }, { question: "Deux personnes pendant deux heures ?", answer: "Cela représente quatre heures-personnes et environ deux heures sur place." }, { question: "Remise récurrente ?", answer: "Seulement si les visites réduisent réellement vente, préparation ou travail ; contrôlez ensuite la marge." }],
    lead: "Un prix durable part du périmètre et des heures-personnes, pas d’une moyenne. Ajoutez travail, frais, fournitures, trajet et options avant la marge et le minimum.", formulaLabel: "Formule principale", formula: "Devis = (travail + frais + fournitures + trajet + options) ÷ (1 − marge)", formulaBody: "Appliquez supplément et remise, comparez au minimum et ajoutez les taxes applicables.",
    sections: [{ id: "scope", title: "1. Définir le périmètre", paragraphs: ["Notez logement, surface, pièces, salles de bain, type, fréquence et état. Encombrement, graisse, animaux, escaliers et accès changent le temps.", "Précisez four, réfrigérateur, vitres, placards, linge et meubles inclus ou exclus."] }, { id: "hours", title: "2. Estimer les heures-personnes", paragraphs: ["Utilisez le rendement de travaux terminés. Deux personnes pendant deux heures égalent quatre heures-personnes.", "Ajustez grand nettoyage et déménagement ou saisissez les heures."], formula: "Heures = surface ÷ rendement × facteur de type × difficulté" }, { id: "costs", title: "3. Ajouter tous les coûts", paragraphs: ["Incluez salaire chargé, assurance, logiciel, gestion, matériel, véhicule, fournitures, trajet et temps des options."] }, { id: "pricing", title: "4. Marge, minimum et remise", paragraphs: ["Divisez le coût par un moins la marge. Le minimum protège les petits travaux et la remise doit refléter une économie réelle."], formula: "Prix = coût ÷ (1 − marge)" }, { id: "example", title: "5. Exemple", paragraphs: ["1 800 pi² à 500 par heure donnent 3,6 heures-personnes et 1,8 heure avec deux personnes.", "Travail 86,40, frais 36, fournitures 12 et trajet 15 donnent 149,40. À 30% de marge, le prix est 213,43."] }, { id: "quote", title: "6. Rédiger le devis", paragraphs: ["Indiquez logement, type, fréquence, périmètre, options, préparation, exclusions, total, taxes, validité et période d’intervention."] }], checklistTitle: "Checklist ménage", checklist: ["Vérifier logement, surface, type, fréquence et état.", "Utiliser son rendement.", "Séparer heures-personnes et durée sur place.", "Ajouter travail, frais, fournitures et trajet.", "Calculer les options.", "Appliquer la marge.", "Contrôler minimum et remise.", "Documenter périmètre et validité."],
  },
  "pt-br": {
    title: "Como orçar limpeza residencial: horas, custos e margem", description: "Crie orçamento com área, tipo, horas-pessoa, materiais, viagem, adicionais, valor mínimo e margem.", readingTime: "9 min de leitura", toolLabel: "Abrir calculadora de limpeza",
    toc: [{ id: "scope", label: "Escopo" }, { id: "hours", label: "Horas" }, { id: "costs", label: "Custos" }, { id: "pricing", label: "Preço" }, { id: "example", label: "Exemplo" }, { id: "quote", label: "Orçamento" }], faq: [{ question: "Por hora ou valor fechado?", answer: "Calcule internamente com horas-pessoa e custos; quando o escopo estiver claro, ofereça valor fechado." }, { question: "Como estimar duração?", answer: "Divida a área pela produtividade real e ajuste tipo e dificuldade." }, { question: "Duas pessoas por duas horas?", answer: "São quatro horas-pessoa e cerca de duas horas no local." }, { question: "Desconto recorrente?", answer: "Só quando visitas repetidas reduzem venda, preparação ou trabalho; confira a margem final." }],
    lead: "Um preço sustentável começa pelo escopo e horas-pessoa, não por média de mercado. Some trabalho, despesas, materiais, viagem e adicionais antes da margem e mínimo.", formulaLabel: "Fórmula principal", formula: "Orçamento = (trabalho + despesas + materiais + viagem + adicionais) ÷ (1 − margem)", formulaBody: "Aplique adicional e desconto, compare ao mínimo e acrescente impostos aplicáveis.",
    sections: [{ id: "scope", title: "1. Defina o escopo", paragraphs: ["Registre imóvel, área, cômodos, banheiros, tipo, frequência e estado. Bagunça, gordura, animais, escadas e acesso mudam o tempo.", "Informe forno, geladeira, janelas, armários, lavanderia e móveis incluídos ou excluídos."] }, { id: "hours", title: "2. Estime horas-pessoa", paragraphs: ["Use produtividade de serviços concluídos. Duas pessoas por duas horas são quatro horas-pessoa.", "Ajuste limpeza pesada e mudança ou informe horas manualmente."], formula: "Horas = área ÷ produtividade × fator de tipo × dificuldade" }, { id: "costs", title: "3. Some todos os custos", paragraphs: ["Inclua salário e encargos, seguro, software, gestão, equipamento, veículo, materiais, viagem e tempo dos adicionais."] }, { id: "pricing", title: "4. Margem, mínimo e desconto", paragraphs: ["Divida o custo por um menos a margem. O mínimo protege serviços pequenos e o desconto deve refletir economia real."], formula: "Preço = custo ÷ (1 − margem)" }, { id: "example", title: "5. Exemplo", paragraphs: ["1.800 pés² a 500 por hora dão 3,6 horas-pessoa e 1,8 hora com duas pessoas.", "Trabalho 86,40, despesas 36, materiais 12 e viagem 15 totalizam 149,40. Com margem de 30%, o preço é 213,43."] }, { id: "quote", title: "6. Escreva o orçamento", paragraphs: ["Inclua imóvel, tipo, frequência, escopo, adicionais, preparação, exclusões, total, impostos, validade e período do serviço."] }], checklistTitle: "Checklist de limpeza", checklist: ["Confirmar imóvel, área, tipo, frequência e estado.", "Usar produtividade própria.", "Separar horas-pessoa e tempo no local.", "Somar trabalho, despesas, materiais e viagem.", "Calcular adicionais.", "Aplicar margem.", "Revisar mínimo e desconto.", "Documentar escopo e validade."],
  },
  ko: {
    title: "가정 청소 견적 방법: 인시, 원가와 마진", description: "면적, 청소 유형, 인시, 용품, 이동, 추가 서비스, 최소 요금과 마진으로 견적을 만듭니다.", readingTime: "읽는 시간 9분", toolLabel: "청소 견적 계산기 열기",
    toc: [{ id: "scope", label: "범위" }, { id: "hours", label: "인시" }, { id: "costs", label: "원가" }, { id: "pricing", label: "가격" }, { id: "example", label: "예시" }, { id: "quote", label: "견적서" }], faq: [{ question: "시간제와 고정 가격 중 무엇이 좋나요?", answer: "내부에서는 청소 인시와 원가로 계산하고 범위가 명확하면 고객에게 고정 가격을 제시합니다." }, { question: "작업 시간은 어떻게 계산하나요?", answer: "면적을 실제 작업 효율로 나누고 청소 유형과 난이도로 조정합니다." }, { question: "2명이 2시간 일하면?", answer: "4청소 인시이며 현장 시간은 약 2시간입니다." }, { question: "정기 할인은 필요한가요?", answer: "재방문이 실제 영업, 준비, 청소 시간을 줄일 때만 적용하고 할인 후 마진을 확인합니다." }],
    lead: "지속 가능한 청소 가격은 시세가 아니라 범위와 총 청소 인시에서 시작합니다. 인건비, 간접비, 용품, 이동과 추가 작업을 계산한 뒤 마진과 최소 요금을 적용합니다.", formulaLabel: "핵심 공식", formula: "견적가 = (인건비 + 간접비 + 용품 + 이동 + 추가 작업) ÷ (1 − 목표 마진)", formulaBody: "첫 청소 추가 요금과 정기 할인을 적용하고 최소 요금과 비교한 뒤 세금을 더합니다.",
    sections: [{ id: "scope", title: "1. 청소 범위를 정의합니다", paragraphs: ["공간, 면적, 방, 욕실, 청소 유형, 주기와 상태를 기록합니다. 물건, 기름, 반려동물 털, 계단과 접근은 시간을 바꿉니다.", "오븐, 냉장고, 창문, 수납장, 세탁, 가구 이동의 포함 여부를 적습니다."] }, { id: "hours", title: "2. 작업 효율로 청소 인시를 계산합니다", paragraphs: ["완료 작업의 실제 효율을 사용하세요. 2명이 2시간 일하면 4인시입니다.", "대청소와 이사 청소는 조정 계수를 사용하거나 인시를 직접 입력합니다."], formula: "기본 인시 = 면적 ÷ 작업 효율 × 유형 계수 × 난이도" }, { id: "costs", title: "3. 모든 원가를 더합니다", paragraphs: ["인건비에 고용 부담을 포함하고 간접비로 보험, 소프트웨어, 관리, 장비, 차량과 비청구 시간을 회수합니다.", "용품, 이동, 주차와 추가 작업 시간을 더합니다."] }, { id: "pricing", title: "4. 마진, 최소 요금과 할인", paragraphs: ["원가를 1에서 목표 마진을 뺀 값으로 나눕니다. 최소 요금은 작은 작업을 보호하고 할인은 실제 절약을 반영해야 합니다."], formula: "목표 가격 = 작업 원가 ÷ (1 − 목표 마진)" }, { id: "example", title: "5. 계산 예시", paragraphs: ["1,800제곱피트를 시간당 500으로 청소하면 3.6인시이고 2명이면 현장 1.8시간입니다.", "인건비 86.40, 간접비 36, 용품 12, 이동 15로 원가는 149.40입니다. 마진 30%의 세전 가격은 213.43입니다."] }, { id: "quote", title: "6. 고객 견적서를 작성합니다", paragraphs: ["공간, 청소 유형, 주기, 포함 범위, 추가 서비스, 고객 준비, 제외, 총액, 세금, 유효기간과 작업 예정 시간을 적습니다."] }], checklistTitle: "청소 견적 체크리스트", checklist: ["공간, 면적, 유형, 주기와 상태 확인.", "자체 작업 효율 사용.", "총 인시와 현장 시간 구분.", "인건비, 간접비, 용품과 이동 추가.", "추가 서비스 계산.", "마진 공식 적용.", "최소 요금과 할인 후 마진 확인.", "범위와 유효기간 기록."],
  },
};
