import type { Locale } from "@/lib/i18n/config";
import type { LocalizedGuideCopy } from "./types";

type TranslatedLocale = Exclude<Locale, "en">;

export const laserMaterialFormula: Record<TranslatedLocale, string> = {
  "zh-hant": "材料成本 = 占用面積 × 基準面積單價 × 材料係數 × 厚度係數（厚度 ÷ 3 mm）×（1 + 損耗率）× 數量",
  de: "Materialkosten = Fläche × Basis-Flächensatz × Materialfaktor × Dickenfaktor (Dicke ÷ 3 mm) × (1 + Ausschuss) × Menge",
  ja: "材料費 = 占有面積 × 基準面積単価 × 材料係数 × 厚さ係数（厚さ ÷ 3 mm）×（1 + ロス率）× 数量",
  es: "Coste de material = área × tarifa base × factor de material × factor de espesor (espesor ÷ 3 mm) × (1 + merma) × cantidad",
  fr: "Coût matière = surface × tarif de base × facteur matière × facteur d’épaisseur (épaisseur ÷ 3 mm) × (1 + perte) × quantité",
  "pt-br": "Custo do material = área × valor-base × fator do material × fator de espessura (espessura ÷ 3 mm) × (1 + perda) × quantidade",
  ko: "재료비 = 면적 × 기준 면적 단가 × 재료 계수 × 두께 계수(두께 ÷ 3mm) × (1 + 폐기율) × 수량",
};

export const laserCuttingGuide: Record<TranslatedLocale, LocalizedGuideCopy> = {
  "zh-hant": {
    title: "雷射切割如何報價：材料、機器時間與毛利指南",
    description: "用板材、損耗、切割時間、設定人工、後處理與目標毛利，建立可重複的雷射切割報價。",
    readingTime: "閱讀約 9 分鐘", toolLabel: "開啟雷射切割計算器",
    toc: [{ id: "job-data", label: "整理工作資料" }, { id: "material", label: "計算材料" }, { id: "machine", label: "機器與人工" }, { id: "margin", label: "套用毛利" }, { id: "example", label: "報價實例" }, { id: "quote", label: "製作正式報價" }],
    faq: [
      { question: "雷射切割應按分鐘還是按長度收費？", answer: "以最能反映自身成本的方式建立內部模型。切割時間通常直接連結機器占用；切割長度與穿孔數可用來檢查 CAM 結果、難度與耗材。" },
      { question: "材料損耗如何加入報價？", answer: "用排版實際占用的板材面積乘以材料單價，再加入邊料、起切、測試與無法利用餘料的損耗比例。" },
      { question: "設定費應分攤到每件嗎？", answer: "設定通常是每批一次的成本。先把設定人工加入整批成本，再除以數量觀察單件價格；材料、切割與搬運則依實際批量計算。" },
      { question: "雷射切割報價要包含哪些內容？", answer: "寫明材料、厚度、數量、檔案版本、表面處理、尺寸與公差假設、交期、運費、稅額、有效期限和不包含的工作。" },
    ],
    lead: "可靠的雷射切割價格不是只看切割分鐘。板材占用、排版損耗、設定、機器時間、搬運、後處理與失敗風險都會影響這批工作的真實成本。",
    formulaLabel: "核心公式", formula: "報價 =（材料 + 機器 + 設定 + 搬運 + 後處理 + 其他成本）÷（1 − 目標毛利率）", formulaBody: "折扣後價格不能低於直接成本；稅額在未稅報價之後計算。",
    sections: [
      { id: "job-data", title: "1. 從 CAD/CAM 整理可核對的工作資料", paragraphs: ["記錄材料種類、厚度、數量、板材占用面積、切割時間、切割長度與穿孔數，並註明使用的檔案版本。第一版不需要上傳 CAD，只要輸入 CAM 或排版軟體已提供的統計資料。", "切割長度和穿孔數不必硬套一個通用價格，但它們能幫助你發現路徑、密集小孔或設定差異。"] },
      { id: "material", title: "2. 計算實際板材成本與損耗", paragraphs: ["材料成本應使用排版占用面積，而不是只看成品外形。加入邊框、共同切割限制、測試片、瑕疵和難以再利用的餘料。", "如果整張板材必須為這筆工作採購，還要決定剩餘材料是否能在可預期期間內再次使用。"], formula: "材料成本 = 占用面積 × 面積單價 ×（1 + 損耗率）× 數量" },
      { id: "machine", title: "3. 分開計算機器時間、設定與人工", paragraphs: ["機器費率可涵蓋設備折舊、雷射源、氣體、電力、鏡片、噴嘴、維護與可計費產能。設定時間通常每批只發生一次；搬運、去毛刺與包裝可能隨數量增加。", "不要把主動人工和無人值守的機器時間視為同一費率。分開記錄能讓批量變化更容易解釋。"], formula: "機器成本 = 切割小時 × 機器費率 × 數量" },
      { id: "margin", title: "4. 使用目標毛利，而不是把毛利當加價率", paragraphs: ["若直接成本為 100，目標毛利率 30%，價格應為 100 ÷ 0.70 = 142.86。直接加 30% 只得到 130，實際毛利率約 23.1%。", "折扣應在模型中明確顯示，并確認折扣後仍高於直接成本和企業需要的最低毛利。"], formula: "目標價格 = 直接成本 ÷（1 − 目標毛利率）" },
      { id: "example", title: "5. 雷射切割報價實例", paragraphs: ["假設一批零件的板材與損耗為 48，機器時間為 32，設定人工為 18，搬運與去毛刺為 22，其他成本為 5，直接成本共 125。", "若目標毛利為 35%，未稅報價是 192.31。再依數量算出單價，并加入適用稅額與運費。"] },
      { id: "quote", title: "6. 把計算結果轉成客戶報價", paragraphs: ["客戶報價應描述交付成果，而不是公開內部成本。至少列出材料、厚度、數量、單價、總額、交期、檔案版本與表面處理。", "說明公差、材料替代、設計變更、未包含的折彎或焊接，以及報價有效期限。設計或数量變更時應重新計算。"] },
    ],
    checklistTitle: "雷射切割報價檢查清單",
    checklist: ["確認材料、厚度、數量與檔案版本。", "使用排版占用面積與可解釋的損耗率。", "輸入 CAM 的切割時間、長度與穿孔數。", "分開計算機器、設定、搬運和後處理。", "加入其他工作成本。", "使用正確的目標毛利公式。", "檢查折扣後不低於成本。", "在報價中寫明範圍、假設、交期與有效期限。"],
  },
  de: {
    title: "Laserschneiden kalkulieren: Material, Maschinenzeit und Marge",
    description: "Berechne Material, Ausschuss, Maschinenzeit, Einrichtung, Nachbearbeitung und Zielmarge für ein belastbares Laserschneidangebot.",
    readingTime: "9 Min. Lesezeit", toolLabel: "Laserschneidrechner öffnen",
    toc: [{ id: "job-data", label: "Auftragsdaten" }, { id: "material", label: "Material" }, { id: "machine", label: "Maschine und Arbeit" }, { id: "margin", label: "Marge" }, { id: "example", label: "Beispiel" }, { id: "quote", label: "Angebot erstellen" }],
    faq: [{ question: "Nach Minuten oder Schnittlänge abrechnen?", answer: "Nutze intern die Größe, die deine Kosten am besten erklärt. Maschinenzeit bildet die Belegung direkt ab; Schnittlänge und Piercings helfen bei der Prüfung von CAM-Daten und Schwierigkeit." }, { question: "Wie wird Ausschuss kalkuliert?", answer: "Multipliziere die tatsächlich belegte Blechfläche mit dem Materialsatz und ergänze einen begründeten Anteil für Ränder, Tests und nicht nutzbare Reste." }, { question: "Wird die Einrichtung je Teil berechnet?", answer: "Einrichtung fällt meist einmal je Los an. Addiere sie zum Auftrag und prüfe anschließend den Stückpreis; Material, Schnitt und Handhabung wachsen mit der Menge." }, { question: "Was gehört ins Kundenangebot?", answer: "Material, Dicke, Menge, Dateiversion, Nachbearbeitung, Annahmen, Lieferzeit, Versand, Steuer, Gültigkeit und ausgeschlossene Leistungen." }],
    lead: "Ein belastbarer Preis entsteht nicht nur aus Schnittminuten. Blechbelegung, Ausschuss, Einrichtung, Maschinenzeit, Handhabung und Nachbearbeitung bestimmen die echten Auftragskosten.",
    formulaLabel: "Kernformel", formula: "Angebot = (Material + Maschine + Einrichtung + Handhabung + Nachbearbeitung + sonstige Kosten) ÷ (1 − Zielmarge)", formulaBody: "Rabatte dürfen den Preis nicht unter die direkten Kosten drücken; Steuern kommen danach hinzu.",
    sections: [{ id: "job-data", title: "1. Verlässliche CAD/CAM-Auftragsdaten sammeln", paragraphs: ["Erfasse Material, Dicke, Menge, belegte Fläche, Schnittzeit, Schnittlänge, Piercings und Dateiversion. Für die manuelle Version reichen Statistiken aus CAM oder Verschachtelung.", "Länge und Piercings müssen keinen universellen Preis erhalten, helfen aber, komplexe Wege und viele kleine Konturen zu erkennen."] }, { id: "material", title: "2. Material und Ausschuss berechnen", paragraphs: ["Nutze die tatsächlich belegte Fläche statt nur der Fertigteilkontur. Berücksichtige Rand, Tests, Fehler und nicht wiederverwendbare Reste."], formula: "Materialkosten = Fläche × Flächensatz × (1 + Ausschuss) × Menge" }, { id: "machine", title: "3. Maschine, Einrichtung und Arbeit trennen", paragraphs: ["Der Maschinensatz kann Abschreibung, Laserquelle, Gas, Strom, Optik, Düsen, Wartung und Kapazität enthalten. Einrichtung fällt je Los an; Handhabung und Entgraten wachsen häufig mit der Menge."] }, { id: "margin", title: "4. Zielmarge korrekt anwenden", paragraphs: ["Bei Kosten von 100 und 30% Zielmarge beträgt der Preis 142,86. Ein Aufschlag von 30% ergibt nur rund 23,1% Marge."], formula: "Zielpreis = Direktkosten ÷ (1 − Zielmarge)" }, { id: "example", title: "5. Kalkulationsbeispiel", paragraphs: ["Material und Ausschuss 48, Maschine 32, Einrichtung 18, Handhabung 22 und sonstige Kosten 5 ergeben 125 Direktkosten. Bei 35% Marge beträgt das Nettoangebot 192,31."] }, { id: "quote", title: "6. Ein klares Kundenangebot schreiben", paragraphs: ["Nenne Material, Dicke, Menge, Stückpreis, Gesamtpreis, Lieferzeit, Dateiversion und Nachbearbeitung. Dokumentiere Toleranzen, Änderungen, Ausschlüsse und Gültigkeit."] }],
    checklistTitle: "Checkliste für Laserschneidangebote", checklist: ["Material, Dicke, Menge und Dateiversion prüfen.", "Belegte Fläche und Ausschuss erfassen.", "CAM-Zeit, Länge und Piercings übernehmen.", "Maschine, Einrichtung und Nachbearbeitung trennen.", "Zielmarge korrekt anwenden.", "Rabatt gegen Kosten prüfen.", "Umfang und Gültigkeit dokumentieren."],
  },
  ja: {
    title: "レーザー加工の見積もり方法：材料・加工時間・利益率",
    description: "材料、廃材、加工時間、段取り、後処理、目標利益率からレーザー加工の見積価格を計算します。",
    readingTime: "読了約9分", toolLabel: "レーザー加工計算機を開く",
    toc: [{ id: "job-data", label: "加工データ" }, { id: "material", label: "材料費" }, { id: "machine", label: "機械と作業" }, { id: "margin", label: "利益率" }, { id: "example", label: "計算例" }, { id: "quote", label: "見積書" }],
    faq: [{ question: "加工時間と切断長のどちらで料金を決めますか？", answer: "自社コストを最も説明できる指標を使います。加工時間は設備占有、切断長とピアス数はCAMデータや難易度の確認に役立ちます。" }, { question: "材料ロスはどう計算しますか？", answer: "ネスティングで占有した面積に材料単価を掛け、端材、試し切り、再利用できない残材の割合を加えます。" }, { question: "段取り費は数量ごとですか？", answer: "通常はロットごとに一度です。全体原価に加えた後で数量で割り、単価を確認します。" }, { question: "見積書に必要な項目は？", answer: "材料、厚さ、数量、データ版、仕上げ、前提、公差、納期、送料、税、見積有効期限、対象外作業です。" }],
    lead: "レーザー加工価格は加工分数だけでは決まりません。板材占有、ロス、段取り、設備時間、取り扱い、後処理まで含めて実際の原価を把握します。",
    formulaLabel: "基本式", formula: "見積価格 =（材料 + 機械 + 段取り + 取り扱い + 後処理 + その他）÷（1 − 目標利益率）", formulaBody: "値引き後も直接費を下回らないことを確認し、税は税抜価格の後に加えます。",
    sections: [{ id: "job-data", title: "1. CAD/CAMの加工データを整理する", paragraphs: ["材料、厚さ、数量、占有面積、加工時間、切断長、ピアス数、データ版を記録します。初版ではファイル解析は不要で、CAMやネスティングの統計値を入力します。"] }, { id: "material", title: "2. 板材費とロスを計算する", paragraphs: ["完成形状だけでなく、ネスティングで実際に占有する面積を使います。外周、試し切り、不良、再利用できない端材を含めます。"], formula: "材料費 = 占有面積 × 面積単価 ×（1 + ロス率）× 数量" }, { id: "machine", title: "3. 機械、段取り、作業を分ける", paragraphs: ["機械単価には減価償却、レーザー源、ガス、電気、光学部品、ノズル、保守と設備能力を含められます。段取りはロット単位、取り扱いやバリ取りは数量に応じて増えます。"] }, { id: "margin", title: "4. 目標利益率を正しく適用する", paragraphs: ["原価100で目標利益率30%なら価格は142.86です。30%を加算するだけでは利益率は約23.1%です。"], formula: "目標価格 = 直接費 ÷（1 − 目標利益率）" }, { id: "example", title: "5. 見積計算例", paragraphs: ["材料とロス48、機械32、段取り18、取り扱い22、その他5なら直接費は125です。目標利益率35%の税抜見積は192.31です。"] }, { id: "quote", title: "6. 顧客向け見積書にまとめる", paragraphs: ["材料、厚さ、数量、単価、合計、納期、データ版、仕上げを記載します。公差、設計変更、対象外作業、有効期限も明確にします。"] }],
    checklistTitle: "レーザー加工見積チェックリスト", checklist: ["材料、厚さ、数量、データ版を確認。", "占有面積とロスを入力。", "加工時間、切断長、ピアス数を転記。", "機械、段取り、取り扱いを分ける。", "正しい利益率式を使う。", "値引き後の原価割れを確認。", "範囲、納期、有効期限を記載。"],
  },
  es: {
    title: "Cómo presupuestar corte láser: material, máquina y margen",
    description: "Calcula material, desperdicio, tiempo de máquina, preparación, acabado y margen objetivo para cotizar corte láser.", readingTime: "9 min de lectura", toolLabel: "Abrir calculadora de corte láser",
    toc: [{ id: "job-data", label: "Datos del trabajo" }, { id: "material", label: "Material" }, { id: "machine", label: "Máquina y trabajo" }, { id: "margin", label: "Margen" }, { id: "example", label: "Ejemplo" }, { id: "quote", label: "Presupuesto" }],
    faq: [{ question: "¿Cobrar por minuto o longitud de corte?", answer: "Usa la medida que mejor explique tus costes. El tiempo refleja la ocupación de máquina; longitud y perforaciones ayudan a revisar CAM y dificultad." }, { question: "¿Cómo incluyo el desperdicio?", answer: "Multiplica el área ocupada por la tarifa de material y añade un porcentaje razonado para bordes, pruebas y retales no reutilizables." }, { question: "¿La preparación se cobra por pieza?", answer: "Normalmente ocurre una vez por lote. Súmala al trabajo y después revisa el coste unitario." }, { question: "¿Qué debe incluir el presupuesto?", answer: "Material, grosor, cantidad, versión del archivo, acabado, supuestos, tolerancias, plazo, envío, impuestos, validez y exclusiones." }],
    lead: "Un precio fiable no sale solo de los minutos de corte. La chapa ocupada, el desperdicio, la preparación, la máquina, la manipulación y el acabado forman el coste real.", formulaLabel: "Fórmula principal", formula: "Presupuesto = (material + máquina + preparación + manipulación + acabado + otros) ÷ (1 − margen)", formulaBody: "El descuento no debe bajar del coste directo; los impuestos se añaden después.",
    sections: [{ id: "job-data", title: "1. Reúne datos CAD/CAM verificables", paragraphs: ["Registra material, grosor, cantidad, área ocupada, tiempo, longitud, perforaciones y versión del archivo. La versión manual usa estadísticas de CAM o nesting."] }, { id: "material", title: "2. Calcula material y desperdicio", paragraphs: ["Usa el área realmente ocupada e incluye bordes, pruebas, fallos y retales no aprovechables."], formula: "Material = área × tarifa × (1 + desperdicio) × cantidad" }, { id: "machine", title: "3. Separa máquina, preparación y trabajo", paragraphs: ["La tarifa de máquina puede cubrir depreciación, fuente láser, gas, energía, óptica, boquillas y mantenimiento. La preparación suele ser por lote; manipulación y desbarbado crecen con la cantidad."] }, { id: "margin", title: "4. Aplica el margen objetivo", paragraphs: ["Con coste 100 y margen objetivo 30%, el precio es 142,86; sumar 30% solo deja un margen del 23,1%."], formula: "Precio = coste directo ÷ (1 − margen)" }, { id: "example", title: "5. Ejemplo", paragraphs: ["Material 48, máquina 32, preparación 18, manipulación 22 y otros 5 suman 125. Con margen del 35%, el presupuesto antes de impuestos es 192,31."] }, { id: "quote", title: "6. Escribe el presupuesto", paragraphs: ["Incluye material, grosor, cantidad, precio unitario, total, plazo, versión y acabado. Documenta tolerancias, cambios, exclusiones y validez."] }], checklistTitle: "Checklist de corte láser", checklist: ["Confirmar material, grosor, cantidad y versión.", "Medir área ocupada y desperdicio.", "Copiar tiempo, longitud y perforaciones de CAM.", "Separar máquina, preparación y acabado.", "Aplicar la fórmula de margen.", "Revisar descuentos y coste.", "Documentar alcance y validez."],
  },
  fr: {
    title: "Comment chiffrer la découpe laser : matière, machine et marge",
    description: "Calculez matière, pertes, temps machine, réglage, finition et marge cible pour établir un devis de découpe laser.", readingTime: "9 min de lecture", toolLabel: "Ouvrir le calculateur laser",
    toc: [{ id: "job-data", label: "Données du travail" }, { id: "material", label: "Matière" }, { id: "machine", label: "Machine et travail" }, { id: "margin", label: "Marge" }, { id: "example", label: "Exemple" }, { id: "quote", label: "Devis" }],
    faq: [{ question: "Facturer au temps ou à la longueur ?", answer: "Utilisez la mesure qui explique vos coûts. Le temps reflète l’occupation machine ; longueur et perçages servent à vérifier les données CAM et la difficulté." }, { question: "Comment inclure les pertes ?", answer: "Multipliez la surface réellement occupée par le tarif matière puis ajoutez un taux justifié pour les bords, tests et chutes inutilisables." }, { question: "Le réglage est-il facturé par pièce ?", answer: "Il intervient généralement une fois par lot. Ajoutez-le au travail puis contrôlez le prix unitaire." }, { question: "Que doit contenir le devis ?", answer: "Matière, épaisseur, quantité, version du fichier, finition, hypothèses, tolérances, délai, livraison, taxes, validité et exclusions." }],
    lead: "Un prix fiable ne dépend pas seulement des minutes de coupe. Surface occupée, pertes, réglage, machine, manutention et finition constituent le coût réel.", formulaLabel: "Formule principale", formula: "Devis = (matière + machine + réglage + manutention + finition + autres coûts) ÷ (1 − marge)", formulaBody: "La remise ne doit pas descendre sous le coût direct ; les taxes viennent ensuite.",
    sections: [{ id: "job-data", title: "1. Rassembler les données CAD/CAM", paragraphs: ["Notez matière, épaisseur, quantité, surface occupée, temps, longueur, perçages et version. La version manuelle utilise les statistiques du CAM ou du nesting."] }, { id: "material", title: "2. Calculer matière et pertes", paragraphs: ["Utilisez la surface réellement occupée et incluez bordures, essais, défauts et chutes inutilisables."], formula: "Matière = surface × tarif × (1 + pertes) × quantité" }, { id: "machine", title: "3. Séparer machine, réglage et travail", paragraphs: ["Le tarif machine peut financer amortissement, source laser, gaz, énergie, optique, buses et maintenance. Le réglage est souvent par lot ; manutention et ébavurage suivent la quantité."] }, { id: "margin", title: "4. Appliquer la marge cible", paragraphs: ["Pour un coût de 100 et une marge de 30%, le prix est 142,86. Ajouter 30% ne donne que 23,1% de marge."], formula: "Prix = coût direct ÷ (1 − marge)" }, { id: "example", title: "5. Exemple", paragraphs: ["Matière 48, machine 32, réglage 18, manutention 22 et autres 5 donnent 125. Avec 35% de marge, le devis HT est 192,31."] }, { id: "quote", title: "6. Rédiger le devis", paragraphs: ["Indiquez matière, épaisseur, quantité, prix unitaire, total, délai, version et finition. Documentez tolérances, changements, exclusions et validité."] }], checklistTitle: "Checklist découpe laser", checklist: ["Vérifier matière, épaisseur, quantité et version.", "Mesurer surface et pertes.", "Reporter temps, longueur et perçages CAM.", "Séparer machine, réglage et finition.", "Appliquer la formule de marge.", "Contrôler remise et coût.", "Documenter périmètre et validité."],
  },
  "pt-br": {
    title: "Como orçar corte a laser: material, máquina e margem",
    description: "Calcule material, desperdício, tempo de máquina, preparação, acabamento e margem para criar orçamento de corte a laser.", readingTime: "9 min de leitura", toolLabel: "Abrir calculadora de corte a laser",
    toc: [{ id: "job-data", label: "Dados do trabalho" }, { id: "material", label: "Material" }, { id: "machine", label: "Máquina e trabalho" }, { id: "margin", label: "Margem" }, { id: "example", label: "Exemplo" }, { id: "quote", label: "Orçamento" }],
    faq: [{ question: "Cobrar por minuto ou comprimento?", answer: "Use a medida que melhor explica seus custos. O tempo representa ocupação da máquina; comprimento e perfurações ajudam a conferir CAM e dificuldade." }, { question: "Como incluir desperdício?", answer: "Multiplique a área ocupada pelo valor do material e acrescente uma taxa justificada para bordas, testes e sobras sem uso." }, { question: "A preparação é por peça?", answer: "Normalmente ocorre uma vez por lote. Some ao trabalho e depois confira o preço unitário." }, { question: "O que entra no orçamento?", answer: "Material, espessura, quantidade, versão do arquivo, acabamento, premissas, tolerâncias, prazo, frete, impostos, validade e exclusões." }],
    lead: "Um preço confiável não vem apenas dos minutos de corte. Chapa ocupada, desperdício, preparação, máquina, manuseio e acabamento formam o custo real.", formulaLabel: "Fórmula principal", formula: "Orçamento = (material + máquina + preparação + manuseio + acabamento + outros) ÷ (1 − margem)", formulaBody: "O desconto não deve ficar abaixo do custo direto; impostos são adicionados depois.",
    sections: [{ id: "job-data", title: "1. Reúna dados CAD/CAM", paragraphs: ["Registre material, espessura, quantidade, área ocupada, tempo, comprimento, perfurações e versão. A versão manual usa estatísticas do CAM ou nesting."] }, { id: "material", title: "2. Calcule material e desperdício", paragraphs: ["Use a área realmente ocupada e inclua bordas, testes, falhas e sobras sem reaproveitamento."], formula: "Material = área × valor × (1 + desperdício) × quantidade" }, { id: "machine", title: "3. Separe máquina, preparação e trabalho", paragraphs: ["A taxa de máquina pode cobrir depreciação, fonte laser, gás, energia, óptica, bicos e manutenção. Preparação é por lote; manuseio e rebarbação crescem com a quantidade."] }, { id: "margin", title: "4. Aplique a margem desejada", paragraphs: ["Com custo 100 e margem de 30%, o preço é 142,86. Somar 30% deixa margem de apenas 23,1%."], formula: "Preço = custo direto ÷ (1 − margem)" }, { id: "example", title: "5. Exemplo", paragraphs: ["Material 48, máquina 32, preparação 18, manuseio 22 e outros 5 totalizam 125. Com margem de 35%, o orçamento sem imposto é 192,31."] }, { id: "quote", title: "6. Escreva o orçamento", paragraphs: ["Informe material, espessura, quantidade, preço unitário, total, prazo, versão e acabamento. Documente tolerâncias, alterações, exclusões e validade."] }], checklistTitle: "Checklist de corte a laser", checklist: ["Confirmar material, espessura, quantidade e versão.", "Medir área ocupada e desperdício.", "Copiar tempo, comprimento e perfurações do CAM.", "Separar máquina, preparação e acabamento.", "Aplicar a fórmula de margem.", "Revisar desconto e custo.", "Documentar escopo e validade."],
  },
  ko: {
    title: "레이저 절단 견적 방법: 재료, 장비 시간과 마진",
    description: "재료, 폐기물, 장비 시간, 설정, 후처리와 목표 마진으로 레이저 절단 견적을 계산합니다.", readingTime: "읽는 시간 9분", toolLabel: "레이저 절단 계산기 열기",
    toc: [{ id: "job-data", label: "작업 데이터" }, { id: "material", label: "재료" }, { id: "machine", label: "장비와 작업" }, { id: "margin", label: "마진" }, { id: "example", label: "예시" }, { id: "quote", label: "견적서" }],
    faq: [{ question: "시간과 절단 길이 중 무엇으로 청구하나요?", answer: "자체 비용을 가장 잘 설명하는 기준을 사용하세요. 시간은 장비 점유를 반영하고 길이와 피어싱은 CAM 데이터와 난이도를 확인하는 데 유용합니다." }, { question: "재료 폐기물은 어떻게 넣나요?", answer: "실제 네스팅 점유 면적에 재료 단가를 곱하고 가장자리, 시험 절단, 재사용할 수 없는 잔재 비율을 더합니다." }, { question: "설정비는 부품마다 적용하나요?", answer: "보통 배치당 한 번 발생합니다. 전체 작업 원가에 더한 뒤 수량으로 나누어 단가를 확인합니다." }, { question: "견적서에는 무엇이 필요한가요?", answer: "재료, 두께, 수량, 파일 버전, 후처리, 가정, 공차, 납기, 배송, 세금, 유효기간과 제외 작업입니다." }],
    lead: "레이저 절단 가격은 절단 시간만으로 정하지 않습니다. 판재 점유, 폐기물, 설정, 장비 시간, 취급과 후처리가 실제 작업 원가를 만듭니다.", formulaLabel: "핵심 공식", formula: "견적가 = (재료 + 장비 + 설정 + 취급 + 후처리 + 기타) ÷ (1 − 목표 마진)", formulaBody: "할인 후에도 직접 원가보다 낮지 않은지 확인하고 세금은 이후에 더합니다.",
    sections: [{ id: "job-data", title: "1. CAD/CAM 작업 데이터를 정리합니다", paragraphs: ["재료, 두께, 수량, 점유 면적, 절단 시간, 길이, 피어싱과 파일 버전을 기록합니다. 수동 버전은 CAM 또는 네스팅 통계를 입력합니다."] }, { id: "material", title: "2. 재료와 폐기물을 계산합니다", paragraphs: ["완성 형상만이 아니라 실제 점유 면적을 사용하고 가장자리, 시험, 불량과 재사용 불가능한 잔재를 포함합니다."], formula: "재료비 = 면적 × 단가 × (1 + 폐기율) × 수량" }, { id: "machine", title: "3. 장비, 설정과 작업을 분리합니다", paragraphs: ["장비 단가에는 감가, 레이저 소스, 가스, 전기, 광학, 노즐과 유지보수를 포함할 수 있습니다. 설정은 배치 단위이며 취급과 디버링은 수량에 따라 늘어납니다."] }, { id: "margin", title: "4. 목표 마진을 올바르게 적용합니다", paragraphs: ["원가 100에 목표 마진 30%면 가격은 142.86입니다. 30%를 더하기만 하면 마진은 약 23.1%입니다."], formula: "목표 가격 = 직접 원가 ÷ (1 − 목표 마진)" }, { id: "example", title: "5. 계산 예시", paragraphs: ["재료 48, 장비 32, 설정 18, 취급 22, 기타 5이면 직접 원가는 125입니다. 목표 마진 35%의 세전 견적은 192.31입니다."] }, { id: "quote", title: "6. 고객 견적서를 작성합니다", paragraphs: ["재료, 두께, 수량, 단가, 합계, 납기, 파일 버전과 후처리를 적고 공차, 변경, 제외와 유효기간을 문서화합니다."] }], checklistTitle: "레이저 절단 견적 체크리스트", checklist: ["재료, 두께, 수량, 파일 버전 확인.", "점유 면적과 폐기물 입력.", "CAM 시간, 길이, 피어싱 기록.", "장비, 설정과 후처리 분리.", "올바른 마진 공식 적용.", "할인 후 원가 확인.", "범위와 유효기간 문서화."],
  },
};
