import type { Locale } from "@/lib/i18n/config";
import type { LocalizedGuideCopy } from "./types";

type TranslatedLocale = Exclude<Locale, "en">;

export const pressureWashingGuide: Record<TranslatedLocale, LocalizedGuideCopy> = {
  "zh-hant": {
    title: "高壓清洗如何報價：逐步估價指南",
    description: "依清洗面積、表面狀況、團隊工時、營運成本、最低收費與目標毛利建立高壓清洗報價。",
    readingTime: "閱讀約 9 分鐘", toolLabel: "開啟計算器",
    toc: [{ id: "define-scope", label: "定義工作範圍" }, { id: "pricing-method", label: "選擇計價方式" }, { id: "condition", label: "狀況與難度" }, { id: "operating-costs", label: "營運成本" }, { id: "profit-margin", label: "加入目標毛利" }, { id: "worked-example", label: "計算實例" }, { id: "minimum-charge", label: "最低收費" }, { id: "write-quote", label: "撰寫報價" }],
    faq: [
      { question: "高壓清洗應按面積還是按小時計價？", answer: "應選擇最能預測自身成本的方式。重複性高的表面適合按面積；進出、設定、污漬或細節工作不確定時，按工時或整案計價更安全。" },
      { question: "如何計算每平方英尺的高壓清洗價格？", answer: "先估算產能、人工、藥劑、燃料、設備、交通、設定與營運費用，再把達到目標毛利的專案價格除以可清洗面積。" },
      { question: "需要設定最低上門費嗎？", answer: "通常需要。即使面積很小，交通、卸貨、設定、溝通和收款仍會發生。最低收費確保固定成本得到回收。" },
      { question: "高壓清洗報價應包含什麼？", answer: "列出表面、約略面積、清洗方式、處理項目、進出條件、排除事項、總價、稅額、付款方式與有效期限，並說明隱藏損壞可能需要重新確認範圍。" },
    ],
    lead: "好的高壓清洗估價應從實際工作開始，而不是抄一個市場單價。先量面積、判斷表面狀況、估算團隊工時，加入營運與交通成本，再套用企業需要的毛利和最低收費。",
    formulaLabel: "簡化公式", formula: "報價 =（人工 + 營運成本 + 交通 + 間接費）÷（1 − 目標毛利率）", formulaBody: "算出結果後與最低上門費比較，只在適用時加入稅額。",
    sections: [
      { id: "define-scope", title: "1. 明確定義要清洗的範圍", paragraphs: ["相同面積的兩個物業可能需要完全不同的工時。逐一記錄車道、走道、露台、外牆、圍欄、木平台或商業區域的材質、約略面積、狀況和進出條件。", "照片有幫助，但排水、水源、脆弱表面、嚴重青苔、油漬、鏽斑、高度或鄰近財物可能改變工法與風險。報價必須寫明包含哪些表面，避免客戶把所有可見區域都視為已包含。"] },
      { id: "pricing-method", title: "2. 選擇合適的計價方式", paragraphs: ["熟悉且重複性高的表面可以按面積檢查價格，但不要先猜單價。應先由工時和成本算出專案所需價格，再除以可清洗面積得到有效面積單價。", "難以量測或施工速度不確定時，按團隊總工時估算更安全。對住宅客戶，固定整案價格通常最容易理解；內部仍可用面積、工時和成本建立。"], formula: "有效面積單價 = 所需專案價格 ÷ 可清洗面積" },
      { id: "condition", title: "3. 依狀況與難度調整", paragraphs: ["一般產能只適用於一般狀況。大量有機物、油漬、鏽、口香糖、油漆、粗糙表面、障礙物、排水不良、水源限制、斜坡和細部收邊都會增加時間、藥劑或風險。", "建立輕度、標準、重度、嚴重等一致分級，並清楚定義。難度倍率應對應額外資源，而不是任意加價。"] },
      { id: "operating-costs", title: "4. 納入全部營運成本", paragraphs: ["完整估價包括所有人員的綜合人工、清洗機與車輛燃料、清潔劑與污漬處理、水、設備折舊維修、軟管與噴嘴耗損、交通時間、里程、停車、設定、防護、收尾與客戶驗收。", "人工費率不能只看實領薪資；雇主成本、非計費時間與團隊管理都要回收。保險、軟體、排程、行銷和行政可分攤為間接費。"] },
      { id: "profit-margin", title: "5. 正確加入目標毛利", paragraphs: ["知道總工作成本後，以一減目標毛利率作為除數。直接在成本上乘毛利百分比得到的是加價率，不是實際毛利率。最後用自己的成交資料檢查價格，而不是盲目套用別人的每平方單價。"], formula: "專案價格 = 總工作成本 ÷（1 − 目標毛利率）" },
      { id: "worked-example", title: "6. 車道清洗估價實例", paragraphs: ["假設車道與短走道共 1,200 平方英尺，狀況標準，兩人團隊包含設定與收尾需 3 小時。人工 132、藥劑 18、設備與燃料 24、交通 20、間接費 16，總成本為 210。", "目標毛利 30% 時，專案價格為 300，有效單價為每平方英尺 0.25。這是由該業者的成本與產能推導出的結果，不是所有市場的統一價格。"] },
      { id: "minimum-charge", title: "7. 用最低收費保護小型工作", paragraphs: ["200 平方英尺的走道清洗時間可能很短，但仍要排程、開車、卸貨、接水、設定、收尾、開單與收款。依最小一次出勤所需的固定成本和毛利設定最低上門費。多項小服務在同一地點時，可合併為套餐。"] },
      { id: "write-quote", title: "8. 寫出能避免範圍爭議的報價", paragraphs: ["列出所有包含的表面、約略面積、清洗方式、處理項目、客戶需完成的準備與排除事項。說明水源、通行、搬動家具、排水和隱藏損壞的處理方式。", "不要保證每種污漬都能完全消失。加入總價、稅額、付款安排、預計服務時段和報價有效期限，並在實際狀況明顯不同時取得客戶同意後再變更範圍。"] },
    ],
    checklistTitle: "高壓清洗估價檢查清單",
    checklist: ["逐一確認表面並量測可清洗面積。", "記錄材質、狀況、進出、水源和排水。", "估算含設定與收尾的團隊總工時。", "加入藥劑、燃料、設備、交通與間接費。", "依異常難度與風險調整。", "套用正確的目標毛利公式。", "與最低上門費比較。", "在報價中寫明範圍、假設、排除事項與有效期限。"],
  },
  de: {
    title: "Hochdruckreinigung kalkulieren: Schritt-für-Schritt zum Angebot",
    description: "Erstelle ein Angebot aus Fläche, Zustand, Teamzeit, Betriebskosten, Mindestpreis und Zielmarge.",
    readingTime: "9 Min. Lesezeit", toolLabel: "Rechner öffnen",
    toc: [{ id: "define-scope", label: "Leistungsumfang" }, { id: "pricing-method", label: "Preismethode" }, { id: "condition", label: "Zustand und Schwierigkeit" }, { id: "operating-costs", label: "Betriebskosten" }, { id: "profit-margin", label: "Gewinnmarge" }, { id: "worked-example", label: "Rechenbeispiel" }, { id: "minimum-charge", label: "Mindestpreis" }, { id: "write-quote", label: "Angebot schreiben" }],
    faq: [
      { question: "Nach Fläche oder Stunde abrechnen?", answer: "Nutze die Methode, die deine Kosten am besten vorhersagt. Flächenpreise passen zu wiederholbaren Oberflächen; bei unsicherem Zugang, Aufbau, Verschmutzung oder Detailarbeit sind Stunden- oder Projektpreise sicherer." },
      { question: "Wie berechne ich einen Quadratmeterpreis?", answer: "Schätze zuerst Leistung, Arbeit, Chemie, Kraftstoff, Gerät, Fahrt, Aufbau und Gemeinkosten. Teile anschließend den erforderlichen Projektpreis durch die zu reinigende Fläche." },
      { question: "Brauche ich einen Mindestpreis?", answer: "Meistens ja. Fahrt, Entladen, Aufbau, Kommunikation und Zahlung fallen auch bei kleinen Flächen an. Der Mindestpreis deckt diese Fixkosten." },
      { question: "Was gehört in ein Angebot?", answer: "Nenne Oberflächen, Fläche, Verfahren, Behandlungen, Zugangsannahmen, Ausschlüsse, Gesamtpreis, Steuer, Zahlung und Gültigkeit. Verdeckte Schäden können eine Freigabe des geänderten Umfangs erfordern." },
    ],
    lead: "Eine gute Kalkulation beginnt bei der tatsächlichen Arbeit, nicht bei einem kopierten Marktpreis. Miss die Fläche, bewerte den Zustand, schätze Teamzeit sowie Betriebs- und Fahrtkosten und wende dann deine Marge und Mindestgebühr an.",
    formulaLabel: "Kurzformel", formula: "Angebot = (Arbeit + Betrieb + Fahrt + Gemeinkosten) ÷ (1 − Zielmarge)", formulaBody: "Vergleiche das Ergebnis mit deinem Mindestpreis und ergänze Steuern nur, wenn sie anfallen.",
    sections: [
      { id: "define-scope", title: "1. Den Reinigungsumfang genau festlegen", paragraphs: ["Zwei Objekte mit gleicher Fläche können völlig unterschiedliche Arbeit verursachen. Erfasse Einfahrt, Weg, Terrasse, Fassade, Zaun, Deck oder Gewerbefläche einzeln mit Material, ungefährer Fläche, Zustand und Zugang.", "Fotos helfen, doch Entwässerung, Wasserzugang, empfindliche Flächen, starker Bewuchs, Öl, Rost, Höhe oder Nachbareigentum können Methode und Risiko verändern. Schreibe ausdrücklich, welche Flächen enthalten sind."] },
      { id: "pricing-method", title: "2. Eine passende Preismethode wählen", paragraphs: ["Flächenpreise funktionieren bei bekannten, wiederholbaren Oberflächen. Leite den Preis aber aus deinen Kosten ab: Berechne zunächst den nötigen Projektpreis und teile ihn erst danach durch die reinigbare Fläche.", "Stundenpreise eignen sich bei schwer messbarem Umfang oder unsicherer Leistung. Für Privatkunden ist ein Festpreis meist verständlicher; intern kann er weiterhin aus Fläche, Zeit und Kosten entstehen."], formula: "Effektiver Flächenpreis = erforderlicher Projektpreis ÷ reinigbare Fläche" },
      { id: "condition", title: "3. Zustand und Schwierigkeit berücksichtigen", paragraphs: ["Starker organischer Bewuchs, Öl, Rost, Kaugummi, Farbe, raue Strukturen, Hindernisse, schlechte Entwässerung, begrenztes Wasser, Gefälle oder Detailkanten erhöhen Zeit, Chemie oder Risiko.", "Definiere eine konsistente Skala wie leicht, normal, stark und extrem. Ein Faktor soll zusätzliche Ressourcen abbilden und kein willkürlicher Zuschlag sein."] },
      { id: "operating-costs", title: "4. Alle Betriebskosten einbeziehen", paragraphs: ["Berücksichtige belastete Lohnkosten aller Personen, Kraftstoff, Reinigungs- und Fleckenmittel, Wasser, Geräteverschleiß, Reparaturen, Schläuche, Düsen, Fahrtzeit, Kilometer, Maut, Parken, Aufbau, Schutz, Nacharbeit und Übergabe.", "Der Lohnsatz umfasst mehr als Nettolohn. Arbeitgeberkosten, nicht abrechenbare Zeit und Teamführung müssen ebenso wie Versicherung, Software, Planung, Marketing und Verwaltung finanziert werden."] },
      { id: "profit-margin", title: "5. Gewinnmarge korrekt ergänzen", paragraphs: ["Teile die Gesamtkosten durch eins minus Zielmarge. Einfaches Multiplizieren mit dem Margenprozentsatz erzeugt einen Aufschlag, nicht die gewünschte Marge. Kalibriere Preise mit echten Aufträgen statt fremde Quadratmeterpreise blind zu übernehmen."], formula: "Projektpreis = Gesamtkosten ÷ (1 − Zielmarge)" },
      { id: "worked-example", title: "6. Beispiel für eine Einfahrt", paragraphs: ["Einfahrt und Weg umfassen 1.200 Quadratfuß. Ein Zweierteam benötigt inklusive Aufbau und Abschluss drei Stunden. Arbeit kostet 132, Chemie 18, Gerät und Kraftstoff 24, Fahrt 20 und Gemeinkosten 16. Gesamtkosten: 210.", "Bei 30% Zielmarge beträgt der Projektpreis 300, entsprechend 0,25 pro Quadratfuß. Dieser Satz folgt den eigenen Kosten und Annahmen, nicht einem allgemeinen Marktpreis."] },
      { id: "minimum-charge", title: "7. Kleine Aufträge mit einem Mindestpreis schützen", paragraphs: ["Auch ein kleiner Weg braucht Terminierung, Fahrt, Entladen, Wasseranschluss, Aufbau, Abbau, Rechnung und Zahlung. Leite den Mindestpreis aus dem kleinsten lohnenden Einsatz ab. Mehrere kleine Leistungen am selben Objekt können zu einem Paket gebündelt werden."] },
      { id: "write-quote", title: "8. Ein Angebot ohne Missverständnisse schreiben", paragraphs: ["Liste Flächen, Maße, Verfahren, Behandlungen, Kundenvorbereitung und Ausschlüsse. Kläre Wasser, Zugang, Möbel, Abfluss und den Umgang mit verdeckten Schäden.", "Versprich nicht, dass jeder Fleck vollständig verschwindet. Nenne Gesamtpreis, Steuer, Zahlungsplan, Leistungszeitraum und Gültigkeit und hole bei wesentlich anderem Zustand die Zustimmung zu einem geänderten Umfang ein."] },
    ],
    checklistTitle: "Checkliste für Hochdruckreinigungsangebote",
    checklist: ["Jede Oberfläche bestimmen und messen.", "Material, Zustand, Zugang, Wasser und Abfluss notieren.", "Gesamte Teamzeit inklusive Aufbau schätzen.", "Chemie, Kraftstoff, Gerät, Fahrt und Gemeinkosten addieren.", "Besondere Schwierigkeit und Risiko anpassen.", "Korrekte Margenformel anwenden.", "Mit dem Mindestpreis vergleichen.", "Umfang, Annahmen, Ausschlüsse und Gültigkeit dokumentieren."],
  },
  ja: {
    title: "高圧洗浄作業の価格設定：見積もりを作る手順",
    description: "洗浄面積、状態、作業時間、運営費、最低料金、目標利益率から高圧洗浄の見積もりを作成します。",
    readingTime: "読了約9分", toolLabel: "計算機を開く",
    toc: [{ id: "define-scope", label: "作業範囲を定義" }, { id: "pricing-method", label: "価格方式を選択" }, { id: "condition", label: "状態と難易度" }, { id: "operating-costs", label: "運営費" }, { id: "profit-margin", label: "利益率を適用" }, { id: "worked-example", label: "計算例" }, { id: "minimum-charge", label: "最低料金" }, { id: "write-quote", label: "見積書を書く" }],
    faq: [
      { question: "高圧洗浄は面積単価と時間単価のどちらがよいですか？", answer: "自社の原価を最も正確に予測できる方法を選びます。反復しやすい面は面積、アクセスや汚れ、細部作業が不確実なら時間または案件単位が安全です。" },
      { question: "面積単価はどう計算しますか？", answer: "作業効率、人件費、薬剤、燃料、設備、移動、準備、間接費を先に計算し、必要な案件価格を洗浄面積で割ります。" },
      { question: "最低出張料金は必要ですか？", answer: "通常は必要です。小さな面積でも移動、荷下ろし、準備、顧客対応、決済が発生するためです。" },
      { question: "見積書には何を含めますか？", answer: "対象面、概算面積、方法、処理、アクセス前提、除外事項、総額、税、支払条件、有効期限を記載し、隠れた損傷は範囲変更になる場合があると説明します。" },
    ],
    lead: "適切な見積もりは、他社の相場を写すのではなく実際の作業から始めます。面積と状態を確認し、チーム時間、運営費、移動費を見積もり、自社に必要な利益率と最低料金を適用します。",
    formulaLabel: "基本式", formula: "見積価格 =（人件費 + 運営費 + 移動費 + 間接費）÷（1 − 目標利益率）", formulaBody: "計算結果を最低出張料金と比較し、必要な場合のみ税を加えます。",
    sections: [
      { id: "define-scope", title: "1. 洗浄対象を明確にする", paragraphs: ["同じ面積でも必要作業は異なります。駐車場、通路、テラス、外壁、フェンス、デッキ、商業スペースごとに材質、概算面積、状態、アクセスを記録します。", "写真は有効ですが、排水、水源、傷みやすい面、藻、油、錆、高さ、周辺物件によって方法とリスクが変わります。対象外の面も明記して範囲誤認を防ぎます。"] },
      { id: "pricing-method", title: "2. 価格設定方法を選ぶ", paragraphs: ["作業効率が分かる反復的な面では面積単価を使えます。ただし単価から始めず、まず必要な案件価格を原価から計算し、面積で割って実効単価を確認します。", "範囲や速度が不確実なら総作業時間で見積もります。住宅顧客には固定案件価格が理解されやすく、内部では面積・時間・原価から算出できます。"], formula: "実効面積単価 = 必要案件価格 ÷ 洗浄可能面積" },
      { id: "condition", title: "3. 状態と難易度を調整する", paragraphs: ["強い藻、油、錆、ガム、塗料、粗面、障害物、排水不良、水源制限、傾斜、細部処理は時間、薬剤、リスクを増やします。", "軽度、標準、重度、深刻など一貫した区分を自社で定義します。係数は追加資源を表し、根拠のない追加料金にしません。"] },
      { id: "operating-costs", title: "4. すべての運営費を含める", paragraphs: ["全員の総人件費、洗浄機と車両の燃料、洗剤、薬剤、水、設備の減価と修理、ホースやノズル、移動時間、距離、駐車、準備、養生、片付け、顧客確認を含めます。", "時間単価は手取り賃金だけではありません。雇用側負担、非請求時間、管理に加え、保険、ソフト、予定管理、広告、事務も回収します。"] },
      { id: "profit-margin", title: "5. 目標利益率を正しく加える", paragraphs: ["総原価を一から目標利益率を引いた値で割ります。原価に利益率をそのまま掛けると、求める利益率ではなく上乗せ率になります。他社単価ではなく実績で調整します。"], formula: "案件価格 = 総原価 ÷（1 − 目標利益率）" },
      { id: "worked-example", title: "6. 駐車場洗浄の計算例", paragraphs: ["駐車場と短い通路が合計1,200平方フィートで、2名が準備と片付けを含め3時間とします。人件費132、薬剤18、設備と燃料24、移動20、間接費16で総原価210です。", "目標利益率30%なら案件価格300、実効単価は平方フィート当たり0.25です。これはこの事業者の原価と生産性から得た値で、全国共通相場ではありません。"] },
      { id: "minimum-charge", title: "7. 最低料金で小規模案件を守る", paragraphs: ["小さな通路でも予定、移動、荷下ろし、水接続、準備、片付け、請求、回収が必要です。採算の取れる最小訪問を基準に最低出張料金を設定し、同じ場所の小作業はパッケージ化できます。"] },
      { id: "write-quote", title: "8. 範囲トラブルを防ぐ見積書を書く", paragraphs: ["対象面、概算面積、方法、処理、顧客準備、除外事項を記載し、水、アクセス、家具移動、排水、隠れた損傷の扱いを明確にします。", "すべての汚れが消えると保証せず、総額、税、支払い、作業時期、有効期限を記載します。現場状態が大きく違う場合は範囲変更の承認を得ます。"] },
    ],
    checklistTitle: "高圧洗浄見積もりチェックリスト",
    checklist: ["対象面を特定して面積を測る。", "材質、状態、アクセス、水、排水を記録。", "準備と片付けを含む総作業時間を見積もる。", "薬剤、燃料、設備、移動、間接費を加える。", "特殊な難易度とリスクを調整。", "正しい利益率式を使う。", "最低料金と比較。", "範囲、前提、除外事項、有効期限を記載。"],
  },
  es: {
    title: "Cómo presupuestar trabajos de lavado a presión: guía paso a paso",
    description: "Crea un presupuesto con superficie, estado, horas de equipo, costes operativos, mínimo de servicio y margen objetivo.",
    readingTime: "9 min de lectura", toolLabel: "Abrir calculadora",
    toc: [{ id: "define-scope", label: "Definir el alcance" }, { id: "pricing-method", label: "Método de precio" }, { id: "condition", label: "Estado y dificultad" }, { id: "operating-costs", label: "Costes operativos" }, { id: "profit-margin", label: "Margen de beneficio" }, { id: "worked-example", label: "Ejemplo completo" }, { id: "minimum-charge", label: "Precio mínimo" }, { id: "write-quote", label: "Redactar presupuesto" }],
    faq: [
      { question: "¿Cobrar por superficie o por hora?", answer: "Usa el método que mejor prediga tus costes. La superficie funciona en trabajos repetibles; horas o proyecto son más seguros si acceso, montaje, manchas o detalle crean incertidumbre." },
      { question: "¿Cómo calculo el precio por pie cuadrado?", answer: "Estima productividad, trabajo, químicos, combustible, equipo, viaje, montaje y gastos. Divide el precio requerido por la superficie limpiable." },
      { question: "¿Necesito un mínimo de servicio?", answer: "Normalmente sí. Viaje, descarga, preparación, comunicación y cobro existen incluso en superficies pequeñas." },
      { question: "¿Qué debe incluir el presupuesto?", answer: "Indica superficies, área, método, tratamientos, acceso, exclusiones, total, impuestos, pago y validez. Aclara que daños ocultos pueden exigir aprobar un alcance revisado." },
    ],
    lead: "Un buen presupuesto empieza por el trabajo real, no por copiar una tarifa de mercado. Mide, evalúa el estado, calcula horas, operación y viaje, y después aplica el margen y mínimo que necesita tu negocio.",
    formulaLabel: "Fórmula breve", formula: "Presupuesto = (trabajo + operación + viaje + gastos) ÷ (1 − margen)", formulaBody: "Compara el resultado con el mínimo de servicio y añade impuestos solo cuando correspondan.",
    sections: [
      { id: "define-scope", title: "1. Define exactamente qué se limpia", paragraphs: ["Dos propiedades con igual superficie pueden requerir trabajos distintos. Registra entrada, camino, patio, fachada, valla, terraza o zona comercial con material, área, estado y acceso.", "Fotos ayudan, pero drenaje, agua, superficies delicadas, crecimiento orgánico, aceite, óxido, altura o propiedad vecina pueden cambiar método y riesgo. Escribe qué está incluido."] },
      { id: "pricing-method", title: "2. Elige el método de precio", paragraphs: ["El precio por área sirve cuando conoces tu productividad. No adivines una tarifa: calcula primero el precio necesario y divídelo por la superficie.", "Las horas son útiles con alcance o velocidad inciertos. Un precio fijo suele ser más claro para clientes residenciales, aunque internamente nazca de área, tiempo y costes."], formula: "Tarifa efectiva = precio requerido ÷ superficie limpiable" },
      { id: "condition", title: "3. Ajusta estado y dificultad", paragraphs: ["Materia orgánica, aceite, óxido, chicle, pintura, textura, obstáculos, drenaje, agua limitada, pendientes y bordes aumentan tiempo, químicos o riesgo.", "Define niveles consistentes: ligero, normal, fuerte y severo. El multiplicador debe representar recursos extra, no un recargo arbitrario."] },
      { id: "operating-costs", title: "4. Incluye todos los costes operativos", paragraphs: ["Incluye coste laboral completo, combustible, detergente, tratamientos, agua, depreciación, reparaciones, mangueras, boquillas, viaje, kilometraje, peajes, aparcamiento, montaje, protección, limpieza final y entrega.", "La tarifa laboral supera el salario neto: también recupera cargas, tiempo no facturable, gestión, seguro, software, agenda, marketing y administración."] },
      { id: "profit-margin", title: "5. Añade correctamente el margen", paragraphs: ["Divide el coste total por uno menos el margen objetivo. Multiplicar el coste por el porcentaje produce recargo, no margen. Ajusta con pedidos reales, no copiando tarifas ajenas."], formula: "Precio del proyecto = coste total ÷ (1 − margen)" },
      { id: "worked-example", title: "6. Ejemplo de entrada de vehículos", paragraphs: ["Una entrada y camino suman 1.200 pies cuadrados. Dos personas tardan tres horas. Trabajo 132, químicos 18, equipo y combustible 24, viaje 20 y gastos 16: coste total 210.", "Con margen del 30%, el precio es 300 y la tarifa efectiva 0,25 por pie cuadrado. Es resultado de estos costes, no una tarifa universal."] },
      { id: "minimum-charge", title: "7. Protege trabajos pequeños con un mínimo", paragraphs: ["Una zona pequeña aún exige agenda, viaje, descarga, conexión, montaje, recogida, factura y cobro. Basa el mínimo en la visita más pequeña rentable y agrupa varios servicios en la misma propiedad."] },
      { id: "write-quote", title: "8. Redacta un presupuesto sin disputas", paragraphs: ["Enumera superficies, área, método, tratamientos, preparación y exclusiones. Aclara agua, acceso, muebles, escorrentía y daños ocultos.", "No prometas eliminar todas las manchas. Incluye total, impuestos, pago, fecha prevista y validez, y pide aprobación si el estado real cambia el alcance."] },
    ],
    checklistTitle: "Lista de control para lavado a presión",
    checklist: ["Identificar y medir cada superficie.", "Registrar material, estado, acceso, agua y drenaje.", "Estimar horas totales con montaje y cierre.", "Añadir químicos, combustible, equipo, viaje y gastos.", "Ajustar dificultad y riesgo.", "Aplicar la fórmula correcta de margen.", "Comparar con el mínimo.", "Documentar alcance, supuestos, exclusiones y validez."],
  },
  fr: {
    title: "Comment chiffrer un nettoyage haute pression : guide étape par étape",
    description: "Créez un devis à partir de la surface, de l’état, du temps d’équipe, des coûts, du minimum d’intervention et de la marge cible.",
    readingTime: "9 min de lecture", toolLabel: "Ouvrir le calculateur",
    toc: [{ id: "define-scope", label: "Définir le périmètre" }, { id: "pricing-method", label: "Méthode de prix" }, { id: "condition", label: "État et difficulté" }, { id: "operating-costs", label: "Coûts d’exploitation" }, { id: "profit-margin", label: "Marge" }, { id: "worked-example", label: "Exemple" }, { id: "minimum-charge", label: "Minimum" }, { id: "write-quote", label: "Rédiger le devis" }],
    faq: [
      { question: "Facturer à la surface ou à l’heure ?", answer: "Choisissez la méthode qui prédit le mieux vos coûts. La surface convient aux travaux répétables ; l’heure ou le forfait protège mieux quand accès, installation, taches ou détails sont incertains." },
      { question: "Comment calculer un prix au pied carré ?", answer: "Estimez rendement, travail, produits, carburant, matériel, déplacement, installation et frais. Divisez ensuite le prix requis par la surface nettoyable." },
      { question: "Faut-il un minimum d’intervention ?", answer: "Généralement oui. Déplacement, déchargement, installation, échanges et paiement existent même pour une petite surface." },
      { question: "Que doit contenir le devis ?", answer: "Précisez surfaces, superficie, méthode, traitements, accès, exclusions, total, taxes, paiement et validité. Les dommages cachés peuvent imposer une révision approuvée." },
    ],
    lead: "Un bon devis part du travail réel, pas d’un tarif de marché copié. Mesurez, évaluez l’état, estimez le temps d’équipe, l’exploitation et le déplacement, puis appliquez votre marge et votre minimum.",
    formulaLabel: "Formule courte", formula: "Devis = (travail + exploitation + déplacement + frais) ÷ (1 − marge)", formulaBody: "Comparez le résultat au minimum d’intervention et ajoutez les taxes uniquement si elles s’appliquent.",
    sections: [
      { id: "define-scope", title: "1. Définir exactement ce qui sera nettoyé", paragraphs: ["Deux biens de même surface peuvent demander un travail très différent. Notez chaque allée, passage, terrasse, façade, clôture, deck ou zone commerciale avec matériau, superficie, état et accès.", "Photos utiles, mais drainage, eau, surfaces fragiles, végétation, huile, rouille, hauteur ou voisinage peuvent modifier méthode et risque. Écrivez clairement ce qui est inclus."] },
      { id: "pricing-method", title: "2. Choisir une méthode de prix", paragraphs: ["Le prix à la surface fonctionne quand votre rendement est connu. Ne choisissez pas d’abord un tarif : calculez le prix nécessaire puis divisez-le par la surface.", "La facturation horaire aide quand l’étendue ou la vitesse est incertaine. Un forfait est souvent plus clair pour le particulier, tout en restant construit en interne sur surface, temps et coûts."], formula: "Tarif effectif = prix requis ÷ surface nettoyable" },
      { id: "condition", title: "3. Ajuster l’état et la difficulté", paragraphs: ["Végétation, huile, rouille, chewing-gum, peinture, texture, obstacles, drainage, eau limitée, pente et finitions augmentent temps, produits ou risque.", "Définissez des niveaux cohérents : léger, normal, fort, sévère. Un coefficient doit représenter des ressources supplémentaires, pas une majoration arbitraire."] },
      { id: "operating-costs", title: "4. Inclure tous les coûts d’exploitation", paragraphs: ["Ajoutez coût chargé de chaque personne, carburant, détergents, traitements, eau, amortissement, réparations, tuyaux, buses, temps de route, kilométrage, péages, stationnement, installation, protection, remise en état et réception.", "Le taux de travail dépasse le salaire net : charges, temps non facturable, encadrement, assurance, logiciel, planning, marketing et administration doivent être financés."] },
      { id: "profit-margin", title: "5. Ajouter correctement la marge", paragraphs: ["Divisez le coût total par un moins la marge cible. Multiplier simplement par le pourcentage crée une majoration, pas la marge souhaitée. Ajustez à partir de vos vrais chantiers plutôt que de copier un tarif concurrent."], formula: "Prix du projet = coût total ÷ (1 − marge)" },
      { id: "worked-example", title: "6. Exemple pour une allée", paragraphs: ["Une allée et un passage totalisent 1 200 pieds carrés. Deux personnes travaillent trois heures. Travail 132, produits 18, matériel et carburant 24, déplacement 20, frais 16 : coût total 210.", "Avec 30% de marge, le prix est 300, soit 0,25 par pied carré. Ce tarif vient des coûts de cette entreprise, pas d’une moyenne universelle."] },
      { id: "minimum-charge", title: "7. Protéger les petits chantiers avec un minimum", paragraphs: ["Une petite zone exige toujours planning, route, déchargement, eau, installation, rangement, facture et encaissement. Basez le minimum sur la plus petite visite rentable et regroupez plusieurs services sur place."] },
      { id: "write-quote", title: "8. Rédiger un devis qui évite les litiges", paragraphs: ["Listez surfaces, mesures, méthode, traitements, préparation client et exclusions. Clarifiez eau, accès, mobilier, ruissellement et dommages cachés.", "Ne garantissez pas la disparition de chaque tache. Indiquez total, taxes, paiement, période d’intervention et validité, et faites approuver toute modification importante du périmètre."] },
    ],
    checklistTitle: "Liste de contrôle du devis haute pression",
    checklist: ["Identifier et mesurer chaque surface.", "Noter matériau, état, accès, eau et drainage.", "Estimer le temps total avec installation et rangement.", "Ajouter produits, carburant, matériel, déplacement et frais.", "Ajuster difficulté et risque.", "Appliquer la bonne formule de marge.", "Comparer au minimum.", "Documenter périmètre, hypothèses, exclusions et validité."],
  },
  "pt-br": {
    title: "Como orçar lavagem de alta pressão: guia passo a passo",
    description: "Crie um orçamento usando área, estado, horas da equipe, custos operacionais, valor mínimo e margem desejada.",
    readingTime: "9 min de leitura", toolLabel: "Abrir calculadora",
    toc: [{ id: "define-scope", label: "Definir escopo" }, { id: "pricing-method", label: "Método de preço" }, { id: "condition", label: "Estado e dificuldade" }, { id: "operating-costs", label: "Custos operacionais" }, { id: "profit-margin", label: "Margem" }, { id: "worked-example", label: "Exemplo" }, { id: "minimum-charge", label: "Valor mínimo" }, { id: "write-quote", label: "Escrever orçamento" }],
    faq: [
      { question: "Cobrar por área ou por hora?", answer: "Use o método que melhor prevê seus custos. Área funciona para superfícies repetíveis; hora ou projeto é mais seguro quando acesso, montagem, manchas ou detalhes são incertos." },
      { question: "Como calcular o preço por pé quadrado?", answer: "Estime produtividade, trabalho, produtos, combustível, equipamento, deslocamento, montagem e despesas. Divida o preço necessário pela área lavável." },
      { question: "Preciso de um valor mínimo?", answer: "Geralmente sim. Viagem, descarga, preparação, comunicação e cobrança existem mesmo em uma área pequena." },
      { question: "O que incluir no orçamento?", answer: "Informe superfícies, área, método, tratamentos, acesso, exclusões, total, impostos, pagamento e validade. Danos ocultos podem exigir aprovação de escopo revisado." },
    ],
    lead: "Um bom orçamento começa pelo trabalho real, não por uma tarifa de mercado copiada. Meça, avalie o estado, estime horas, operação e viagem, e aplique a margem e o mínimo do seu negócio.",
    formulaLabel: "Fórmula resumida", formula: "Orçamento = (trabalho + operação + viagem + despesas) ÷ (1 − margem)", formulaBody: "Compare o resultado ao valor mínimo e acrescente impostos somente quando aplicáveis.",
    sections: [
      { id: "define-scope", title: "1. Defina exatamente o que será lavado", paragraphs: ["Duas propriedades com a mesma área podem exigir trabalhos diferentes. Registre entrada, calçada, pátio, fachada, cerca, deck ou área comercial com material, tamanho, estado e acesso.", "Fotos ajudam, mas drenagem, água, superfícies frágeis, matéria orgânica, óleo, ferrugem, altura ou imóveis próximos podem mudar método e risco. Escreva o que está incluído."] },
      { id: "pricing-method", title: "2. Escolha o método de preço", paragraphs: ["Preço por área funciona quando sua produtividade é conhecida. Não comece chutando a taxa: calcule o preço necessário e só então divida pela área.", "Preço por hora ajuda com escopo ou velocidade incertos. Um preço fechado é mais claro para o cliente residencial, embora internamente venha de área, tempo e custos."], formula: "Taxa efetiva = preço necessário ÷ área lavável" },
      { id: "condition", title: "3. Ajuste estado e dificuldade", paragraphs: ["Matéria orgânica, óleo, ferrugem, chiclete, tinta, textura, obstáculos, drenagem, pouca água, inclinação e detalhes aumentam tempo, produtos ou risco.", "Defina níveis consistentes: leve, normal, pesado e severo. O multiplicador deve representar recursos extras, não uma cobrança arbitrária."] },
      { id: "operating-costs", title: "4. Inclua todos os custos operacionais", paragraphs: ["Inclua custo completo de cada pessoa, combustível, detergente, tratamentos, água, depreciação, reparos, mangueiras, bicos, viagem, quilometragem, pedágios, estacionamento, montagem, proteção, finalização e vistoria.", "A taxa de trabalho é maior que o salário líquido: encargos, horas não faturáveis, gestão, seguro, software, agenda, marketing e administração precisam ser pagos."] },
      { id: "profit-margin", title: "5. Aplique corretamente a margem", paragraphs: ["Divida o custo total por um menos a margem desejada. Multiplicar o custo pelo percentual gera acréscimo, não a margem. Ajuste com trabalhos reais, não copiando a taxa de outro negócio."], formula: "Preço do projeto = custo total ÷ (1 − margem)" },
      { id: "worked-example", title: "6. Exemplo de entrada de garagem", paragraphs: ["Entrada e calçada somam 1.200 pés quadrados. Duas pessoas trabalham três horas. Trabalho 132, produtos 18, equipamento e combustível 24, viagem 20 e despesas 16: custo total 210.", "Com margem de 30%, o preço é 300 e a taxa efetiva 0,25 por pé quadrado. Esse valor vem destes custos, não de uma média universal."] },
      { id: "minimum-charge", title: "7. Proteja serviços pequenos com um mínimo", paragraphs: ["Uma área pequena ainda exige agenda, viagem, descarga, água, montagem, recolhimento, fatura e cobrança. Baseie o mínimo na menor visita lucrativa e agrupe serviços no mesmo imóvel."] },
      { id: "write-quote", title: "8. Escreva um orçamento sem disputa de escopo", paragraphs: ["Liste superfícies, medidas, método, tratamentos, preparação do cliente e exclusões. Esclareça água, acesso, móveis, escoamento e danos ocultos.", "Não prometa remover toda mancha. Inclua total, impostos, pagamento, janela do serviço e validade, e peça aprovação se o estado real mudar o escopo."] },
    ],
    checklistTitle: "Checklist de orçamento de lavagem",
    checklist: ["Identificar e medir cada superfície.", "Registrar material, estado, acesso, água e drenagem.", "Estimar horas totais com montagem e finalização.", "Somar produtos, combustível, equipamento, viagem e despesas.", "Ajustar dificuldade e risco.", "Aplicar a fórmula correta de margem.", "Comparar com o mínimo.", "Documentar escopo, premissas, exclusões e validade."],
  },
  ko: {
    title: "고압 세척 작업 가격 책정: 단계별 견적 가이드",
    description: "세척 면적, 상태, 작업 시간, 운영비, 최소 요금과 목표 마진으로 고압 세척 견적을 만듭니다.",
    readingTime: "읽는 시간 9분", toolLabel: "계산기 열기",
    toc: [{ id: "define-scope", label: "작업 범위 정의" }, { id: "pricing-method", label: "가격 방식 선택" }, { id: "condition", label: "상태와 난이도" }, { id: "operating-costs", label: "운영비" }, { id: "profit-margin", label: "마진 적용" }, { id: "worked-example", label: "계산 예시" }, { id: "minimum-charge", label: "최소 요금" }, { id: "write-quote", label: "견적 작성" }],
    faq: [
      { question: "면적과 시간 중 무엇으로 청구해야 하나요?", answer: "자신의 비용을 더 잘 예측하는 방식을 사용하세요. 반복 가능한 표면은 면적, 접근·준비·오염·세부 작업이 불확실하면 시간 또는 프로젝트 가격이 안전합니다." },
      { question: "제곱피트당 가격은 어떻게 계산하나요?", answer: "생산성, 인건비, 약품, 연료, 장비, 이동, 준비와 간접비를 먼저 계산하고 필요한 프로젝트 가격을 세척 면적으로 나눕니다." },
      { question: "최소 출장 요금이 필요한가요?", answer: "대부분 필요합니다. 작은 면적도 이동, 하역, 설정, 고객 응대와 결제가 발생합니다." },
      { question: "견적에는 무엇을 포함해야 하나요?", answer: "표면, 면적, 방법, 처리, 접근 가정, 제외 사항, 총액, 세금, 결제와 유효기간을 적고 숨은 손상은 범위 수정이 필요할 수 있음을 설명합니다." },
    ],
    lead: "좋은 고압 세척 견적은 다른 업체의 시세가 아니라 실제 작업에서 시작합니다. 면적과 상태를 확인하고 팀 시간, 운영비, 이동비를 계산한 뒤 필요한 마진과 최소 요금을 적용합니다.",
    formulaLabel: "기본 공식", formula: "견적가 = (인건비 + 운영비 + 이동비 + 간접비) ÷ (1 − 목표 마진)", formulaBody: "결과를 최소 출장 요금과 비교하고 해당되는 경우에만 세금을 더합니다.",
    sections: [
      { id: "define-scope", title: "1. 세척 범위를 정확히 정의합니다", paragraphs: ["같은 면적의 두 현장도 작업량이 다를 수 있습니다. 진입로, 보도, 파티오, 외벽, 울타리, 데크, 상업 구역을 재질, 면적, 상태, 접근 조건과 함께 기록하세요.", "사진은 유용하지만 배수, 물, 민감한 표면, 심한 유기물, 기름, 녹, 높이, 인접 재산은 방법과 위험을 바꿀 수 있습니다. 포함 표면을 명시하세요."] },
      { id: "pricing-method", title: "2. 적절한 가격 방식을 선택합니다", paragraphs: ["생산성을 아는 반복 작업은 면적 가격을 사용할 수 있습니다. 먼저 단가를 고르지 말고 필요한 프로젝트 가격을 계산한 뒤 면적으로 나눠 유효 단가를 확인하세요.", "범위나 속도가 불확실하면 총 팀 시간으로 계산합니다. 주거 고객에게는 고정 프로젝트 가격이 이해하기 쉽고 내부적으로는 면적, 시간과 비용에서 만들 수 있습니다."], formula: "유효 면적 단가 = 필요한 프로젝트 가격 ÷ 세척 면적" },
      { id: "condition", title: "3. 상태와 난이도를 조정합니다", paragraphs: ["심한 유기물, 기름, 녹, 껌, 페인트, 거친 표면, 장애물, 나쁜 배수, 제한된 물, 경사와 세부 마감은 시간, 약품, 위험을 늘립니다.", "가벼움, 표준, 심함, 매우 심함처럼 일관된 등급을 정의하세요. 배수는 실제 추가 자원을 나타내야 하며 임의 할증이 되어서는 안 됩니다."] },
      { id: "operating-costs", title: "4. 모든 운영비를 포함합니다", paragraphs: ["모든 인원의 총 인건비, 세척기와 차량 연료, 세제와 처리제, 물, 장비 감가와 수리, 호스와 노즐, 이동 시간, 거리, 통행료, 주차, 설정, 보호, 정리와 고객 확인을 포함합니다.", "인건비 요율은 실수령 임금보다 큽니다. 고용 비용, 비청구 시간, 관리, 보험, 소프트웨어, 일정, 마케팅과 행정도 회수해야 합니다."] },
      { id: "profit-margin", title: "5. 목표 마진을 올바르게 적용합니다", paragraphs: ["총 작업 원가를 일에서 목표 마진을 뺀 값으로 나눕니다. 원가에 마진 비율을 곱하면 원하는 마진이 아니라 가산율이 됩니다. 다른 업체 단가가 아닌 실제 작업 결과로 조정하세요."], formula: "프로젝트 가격 = 총원가 ÷ (1 − 목표 마진)" },
      { id: "worked-example", title: "6. 진입로 세척 견적 예시", paragraphs: ["진입로와 짧은 보도가 1,200제곱피트이고 2명이 설정과 정리를 포함해 3시간 작업한다고 가정합니다. 인건비 132, 약품 18, 장비와 연료 24, 이동 20, 간접비 16으로 총원가는 210입니다.", "목표 마진 30%면 프로젝트 가격은 300이고 유효 단가는 제곱피트당 0.25입니다. 이는 해당 사업자의 비용과 생산성에서 나온 값이지 보편 시세가 아닙니다."] },
      { id: "minimum-charge", title: "7. 최소 요금으로 작은 작업을 보호합니다", paragraphs: ["작은 보도도 일정, 이동, 하역, 물 연결, 설정, 정리, 청구와 결제가 필요합니다. 수익이 나는 가장 작은 방문을 기준으로 최소 요금을 정하고 같은 장소의 여러 서비스를 묶을 수 있습니다."] },
      { id: "write-quote", title: "8. 범위 분쟁을 막는 견적을 작성합니다", paragraphs: ["포함 표면, 면적, 방법, 처리, 고객 준비와 제외 사항을 적고 물, 접근, 가구 이동, 배수와 숨은 손상 처리 방식을 명확히 하세요.", "모든 얼룩 제거를 보장하지 말고 총액, 세금, 결제, 작업 예정 기간과 유효기간을 기재합니다. 실제 상태가 크게 다르면 범위 변경 승인을 받으세요."] },
    ],
    checklistTitle: "고압 세척 견적 체크리스트",
    checklist: ["각 표면을 확인하고 면적 측정.", "재질, 상태, 접근, 물과 배수 기록.", "설정과 정리를 포함한 총 팀 시간 추정.", "약품, 연료, 장비, 이동과 간접비 추가.", "특별 난이도와 위험 조정.", "올바른 마진 공식 적용.", "최소 요금과 비교.", "범위, 가정, 제외 사항과 유효기간 기록."],
  },
};
