import type { Locale } from "@/lib/i18n/config";
import type { LocalizedGuideCopy } from "./types";

type TranslatedLocale = Exclude<Locale, "en">;

export const threeDPrintGuide: Record<TranslatedLocale, LocalizedGuideCopy> = {
  "zh-hant": {
    title: "3D 列印如何定價：成本、毛利與報價公式",
    description: "用耗材、機器時間、人工、失敗風險、營運費用與目標毛利，計算 FDM 3D 列印價格。",
    readingTime: "閱讀約 10 分鐘", toolLabel: "開啟計算器",
    toc: [{ id: "true-cost", label: "計算真實成本" }, { id: "risk-overhead", label: "風險與營運費用" }, { id: "profit-margin", label: "套用目標毛利" }, { id: "worked-example", label: "計算實例" }, { id: "minimum-charge", label: "設定最低收費" }, { id: "professional-quote", label: "製作正式報價" }],
    faq: [
      { question: "3D 列印每克應該收多少？", answer: "只按克數收費通常不夠，因為它忽略機器時間、前置作業、後處理、失敗、包裝與營運費用。先計算每克耗材成本，再加入其他成本與目標毛利。" },
      { question: "3D 列印機器時間需要收費嗎？", answer: "需要。機器費率應分攤折舊、維護、替換零件，以及設備被本工作占用而無法承接其他訂單的成本。" },
      { question: "3D 列印合理的毛利率是多少？", answer: "沒有適用所有業者的固定數字。應依市場、複雜度、風險與經營需求設定，並用真實成交結果校準。毛利率和加價率不是同一概念。" },
      { question: "報價如何納入列印失敗？", answer: "根據自己的歷史資料估算正常失敗率，把預期失敗成本平均分攤到成功訂單，而不是等一次失敗吃掉整筆訂單的利潤。" },
    ],
    lead: "可持續的 3D 列印價格不能只支付耗材，還要涵蓋機器、電力、實際操作時間、損耗、失敗、包裝，以及讓工作室能繼續營運的利潤。",
    formulaLabel: "簡化公式", formula: "報價 = 總成本 ÷（1 − 目標毛利率）", formulaBody: "先算完整工作成本，再套用毛利公式，最後比較最低訂單金額並加入運費與適用稅額。",
    sections: [
      { id: "true-cost", title: "1. 計算列印的真實成本", paragraphs: ["先分開記錄會隨訂單改變的成本。耗材應使用切片軟體估算重量，因為其中包含支撐與客戶看不到的列印材料。機器時間則應以可實際計費的運轉時數分攤設備購置、維護、噴嘴、熱床與未來汰換成本。", "電力通常小於耗材或人工，但長時間列印仍值得計算。人工只計入需要人員操作的時間，例如檔案檢查、切片、設定、換料、拆支撐、打磨、組裝、品檢、溝通與包裝。"], formula: "耗材成本 =（使用克數 ÷ 整卷克數）× 整卷價格" },
      { id: "risk-overhead", title: "2. 加入失敗風險、營運費用與專案成本", paragraphs: ["翹曲、黏著、耗材、斷電或幾何問題都可能造成失敗。用自己的紀錄估算正常失敗率，並把預期損失分攤到生產成本。", "包裝、五金、磁鐵、嵌件、黏著劑、外包後加工、平台費與付款手續費都要列入。軟體、空間、保險、行政和行銷等營運費用可放入機器或人工費率，也可另外分攤，但不要重複計算。"] },
      { id: "profit-margin", title: "3. 正確套用目標毛利", paragraphs: ["加價率與毛利率不同。成本 50 元加價 30% 得到 65 元，但毛利率只有約 23.1%。若要真正達到 30% 毛利，應以成本除以 0.70。價格算出後仍要依市場回饋驗證，但不能用市場均價取代自己的成本底線。"], formula: "目標售價 = 總成本 ÷（1 − 目標毛利率）" },
      { id: "worked-example", title: "4. 3D 列印報價實例", paragraphs: ["假設一筆兩件 FDM 訂單使用 180 g 耗材、占用機器 12 小時，準備與後處理共 45 分鐘。耗材與損耗 4.75、機器 18、電力 0.26、人工 21、包裝 2.50、預期失敗 2.30，總成本為 48.81。", "套用 30% 目標毛利後，未稅價格為 69.73。業者可整理為 70，再加入運費與適用稅額；若最低訂單金額為 75，則應採用 75。"] },
      { id: "minimum-charge", title: "5. 設定最低訂單金額", paragraphs: ["小訂單仍需要回覆訊息、設定、切片、檢查、收款與行政處理。最低收費可以避免看似有毛利的訂單，實際只產生很少的利潤金額。最低值應反映值得打斷工作流程的最小訂單。"] },
      { id: "professional-quote", title: "6. 把計算轉成正式報價", paragraphs: ["客戶通常不需要看到內部成本。報價應清楚列出數量、材料、顏色、表面處理、公差或假設、單價、總價、交期、有效期限、運費與稅額，並記錄所採用的檔案版本。", "設計或數量變更應觸發新版報價。使用免費 3D 列印成本計算器可加入多個項目、檢查毛利、套用最低費用，並在不註冊帳號的情況下匯出 PDF 或 CSV。"] },
    ],
    checklistTitle: "可重複使用的 3D 列印定價清單",
    checklist: ["使用切片軟體的材料與時間估算。", "包含支撐、損耗與消耗品。", "計算機器占用與實際人工。", "分攤正常列印失敗。", "加入包裝與專案採購。", "使用正確毛利公式。", "與最低訂單金額比較。", "在報價中寫明範圍、假設、交期與有效期限。"],
  },
  de: {
    title: "3D-Druck kalkulieren: Kosten, Marge und Angebotsformel",
    description: "Berechne den Preis eines FDM-3D-Drucks aus Filament, Maschinenzeit, Arbeit, Ausfallrisiko, Gemeinkosten und Zielmarge.",
    readingTime: "10 Min. Lesezeit", toolLabel: "Rechner öffnen",
    toc: [{ id: "true-cost", label: "Echte Kosten berechnen" }, { id: "risk-overhead", label: "Risiko und Gemeinkosten" }, { id: "profit-margin", label: "Zielmarge anwenden" }, { id: "worked-example", label: "Rechenbeispiel" }, { id: "minimum-charge", label: "Mindestpreis festlegen" }, { id: "professional-quote", label: "Angebot erstellen" }],
    faq: [
      { question: "Wie viel sollte ich pro Gramm 3D-Druck berechnen?", answer: "Ein reiner Grammpreis reicht selten aus. Er ignoriert Maschinenzeit, Einrichtung, Nachbearbeitung, Fehldrucke, Verpackung und Gemeinkosten. Berechne das Filament pro Gramm und ergänze alle weiteren Kosten vor der Marge." },
      { question: "Sollte ich die Maschinenzeit des 3D-Druckers berechnen?", answer: "Ja. Der Maschinensatz sollte Abschreibung, Wartung, Ersatzteile und die Belegung des Druckers durch diesen Auftrag abdecken." },
      { question: "Welche Gewinnmarge ist beim 3D-Druck sinnvoll?", answer: "Es gibt keine allgemeingültige Marge. Sie hängt von Markt, Komplexität, Risiko und deinen betrieblichen Zielen ab. Marge und Aufschlag dürfen dabei nicht verwechselt werden." },
      { question: "Wie berücksichtige ich Fehldrucke im Angebot?", answer: "Ermittle deine normale Ausfallquote aus vergangenen Aufträgen und verteile die erwarteten Ausfallkosten auf erfolgreiche Aufträge." },
    ],
    lead: "Ein nachhaltiger 3D-Druckpreis muss mehr als Filament bezahlen. Er deckt Drucker, Strom, aktive Arbeitszeit, Ausschuss, Fehldrucke, Verpackung und den Gewinn ab, den dein Betrieb zum Weiterarbeiten braucht.",
    formulaLabel: "Kurzformel", formula: "Angebot = Gesamtkosten ÷ (1 − Zielmarge)", formulaBody: "Berechne zuerst die vollständigen Auftragskosten. Wende danach die Margenformel an und berücksichtige Mindestauftragswert, Versand und Steuern.",
    sections: [
      { id: "true-cost", title: "1. Die echten Druckkosten berechnen", paragraphs: ["Trenne zunächst die variablen Kosten. Nutze für das Filament die Materialschätzung des Slicers, weil sie Stützmaterial und weitere gedruckte Reste einschließt. Ein Maschinenstundensatz verteilt Anschaffung, Wartung, Düsen, Druckbetten und späteren Ersatz auf realistische abrechenbare Stunden.", "Strom ist oft kleiner als Material oder Arbeit, wird bei langen Drucken aber relevant. Als Arbeitszeit zählen Dateiprüfung, Slicing, Einrichtung, Materialwechsel, Entfernen von Stützen, Schleifen, Montage, Qualitätskontrolle, Kundenkommunikation und Verpackung."], formula: "Filamentkosten = (verbrauchte Gramm ÷ Spulengewicht) × Spulenpreis" },
      { id: "risk-overhead", title: "2. Ausfallrisiko, Gemeinkosten und Zusatzkosten ergänzen", paragraphs: ["Haftungsprobleme, Filamentfehler, Stromausfall oder Geometrie können einen Druck zerstören. Leite eine normale Ausfallquote aus deinen eigenen Daten ab und verteile die erwarteten Kosten auf erfolgreiche Aufträge.", "Verpackung, Zukaufteile, Magnete, Einsätze, Klebstoffe, externe Nachbearbeitung sowie Plattform- und Zahlungsgebühren gehören in die Kalkulation. Software, Werkstatt, Versicherung, Verwaltung und Marketing dürfen über Maschinen- oder Arbeitssätze oder separat verteilt werden – aber nur einmal."] },
      { id: "profit-margin", title: "3. Die Zielmarge korrekt anwenden", paragraphs: ["Aufschlag und Marge sind nicht dasselbe. Ein Aufschlag von 30% auf 50 Euro Kosten ergibt 65 Euro und nur 23,1% Marge. Für echte 30% Marge teilst du die Kosten durch 0,70. Prüfe den resultierenden Preis anschließend am Markt, ohne deine Kostenuntergrenze aufzugeben."], formula: "Preis bei Zielmarge = Gesamtkosten ÷ (1 − Marge)" },
      { id: "worked-example", title: "4. Beispiel für ein 3D-Druckangebot", paragraphs: ["Ein zweiteiliger FDM-Auftrag benötigt 180 g Filament, 12 Maschinenstunden und 45 Minuten Vorbereitung und Nacharbeit. Material mit Ausschuss kostet 4,75 Euro, Maschine 18, Strom 0,26, Arbeit 21, Verpackung 2,50 und die Ausfallreserve 2,30. Die Gesamtkosten betragen 48,81 Euro.", "Bei 30% Zielmarge liegt der Nettopreis bei 69,73 Euro. Der Betrieb kann auf 70 Euro runden und Versand sowie Steuer ergänzen. Gilt ein Mindestauftragswert von 75 Euro, hat dieser Vorrang."] },
      { id: "minimum-charge", title: "5. Einen Mindestauftragswert festlegen", paragraphs: ["Auch kleine Aufträge brauchen Nachrichten, Einrichtung, Slicing, Prüfung und Zahlungsabwicklung. Ein Mindestpreis verhindert, dass eine rechnerisch gute Prozentmarge nur einen unbedeutenden Gewinnbetrag liefert. Orientiere ihn am kleinsten Auftrag, für den sich eine Unterbrechung deines Ablaufs lohnt."] },
      { id: "professional-quote", title: "6. Aus der Kalkulation ein professionelles Angebot machen", paragraphs: ["Kunden benötigen normalerweise nicht deine interne Kostenaufteilung. Nenne Menge, Material, Farbe, Oberfläche, Toleranzen oder Annahmen, Stückpreis, Gesamtbetrag, Lieferzeit, Gültigkeit, Versand und Steuer. Halte außerdem fest, welche Dateiversion kalkuliert wurde.", "Änderungen an Design oder Menge sollten ein neues Angebot auslösen. Im kostenlosen 3D-Druckkostenrechner kannst du mehrere Positionen erfassen, die Marge prüfen, einen Mindestpreis anwenden und ohne Konto PDF oder CSV exportieren."] },
    ],
    checklistTitle: "Checkliste für wiederholbare 3D-Druckkalkulationen",
    checklist: ["Material- und Zeitschätzung des Slicers verwenden.", "Stützen, Ausschuss und Verbrauchsmittel einrechnen.", "Maschinenbelegung und aktive Arbeit berechnen.", "Normale Fehldrucke berücksichtigen.", "Verpackung und Zukaufteile ergänzen.", "Die korrekte Margenformel anwenden.", "Mit dem Mindestauftragswert vergleichen.", "Leistungsumfang, Annahmen, Lieferzeit und Gültigkeit dokumentieren."],
  },
  ja: {
    title: "3Dプリントの価格設定方法：原価・利益率・見積もり計算式",
    description: "フィラメント、機械時間、人件費、造形失敗、間接費、目標利益率からFDM 3Dプリント価格を計算します。",
    readingTime: "読了約10分", toolLabel: "計算機を開く",
    toc: [{ id: "true-cost", label: "実際の原価を計算" }, { id: "risk-overhead", label: "失敗リスクと間接費" }, { id: "profit-margin", label: "目標利益率を適用" }, { id: "worked-example", label: "計算例" }, { id: "minimum-charge", label: "最低料金を設定" }, { id: "professional-quote", label: "見積書を作成" }],
    faq: [
      { question: "3Dプリントは1gあたりいくらにすべきですか？", answer: "重量だけの価格では、機械時間、準備、後処理、失敗、梱包、間接費を回収できません。1gあたり材料費を計算した後、その他の原価と利益率を加えてください。" },
      { question: "3Dプリンターの稼働時間も請求すべきですか？", answer: "はい。機械時間には減価、保守、交換部品に加え、その装置で別の有料案件を実行できない占有コストがあります。" },
      { question: "3Dプリントの適正な利益率は？", answer: "一律の正解はありません。市場、難易度、リスク、事業目標に合わせ、実際の受注結果で調整します。利益率と値入率・上乗せ率は区別してください。" },
      { question: "造形失敗を見積もりにどう含めますか？", answer: "通常の失敗率を履歴から推定し、期待される失敗原価を成功した案件に配分します。" },
    ],
    lead: "継続できる3Dプリント価格は、フィラメント代だけではありません。プリンター、電気、実作業、廃棄、造形失敗、梱包、そして事業を続けるための利益を回収する必要があります。",
    formulaLabel: "基本の計算式", formula: "見積価格 = 総原価 ÷（1 − 目標利益率）", formulaBody: "最初に案件全体の原価を計算し、利益率の式を適用します。その後、最低受注額、送料、該当する税を加えます。",
    sections: [
      { id: "true-cost", title: "1. 造形の実際原価を計算する", paragraphs: ["まず案件によって変わる原価を分けます。材料は完成品重量ではなく、サポートなどを含むスライサーの推定使用量を使います。機械時間単価には本体価格、保守、ノズル、ベッド、将来の更新費を、現実的な有償稼働時間で配分します。", "電気代は材料費や人件費より小さいことが多いものの、長時間造形では無視できません。人件費にはデータ確認、スライス、設定、材料交換、サポート除去、研磨、組立、検品、顧客対応、梱包など、人が実際に作業する時間を含めます。"], formula: "材料費 =（使用量g ÷ スプール重量g）× スプール価格" },
      { id: "risk-overhead", title: "2. 失敗リスク・間接費・案件固有費を加える", paragraphs: ["定着不良、材料、停電、形状などで造形が失敗することがあります。自社履歴から通常の失敗率を求め、期待損失を成功案件へ配分します。", "梱包材、金具、磁石、インサート、接着剤、外注仕上げ、販売プラットフォーム手数料、決済手数料も含めます。ソフト、作業場所、保険、事務、集客などの間接費は機械単価や作業単価に含めるか別配賦し、二重計上を避けます。"] },
      { id: "profit-margin", title: "3. 目標利益率を正しく適用する", paragraphs: ["原価への上乗せ率と売上に対する利益率は異なります。原価50に30%を上乗せすると価格65ですが、利益率は約23.1%です。利益率30%を確保するには原価を0.70で割ります。計算価格は需要と比較して調整しますが、原価割れを相場で正当化しないことが重要です。"], formula: "目標価格 = 総原価 ÷（1 − 目標利益率）" },
      { id: "worked-example", title: "4. 3Dプリント見積もりの計算例", paragraphs: ["2部品のFDM案件で材料180g、機械12時間、準備と後処理45分とします。材料と廃棄4.75、機械18、電気0.26、人件費21、梱包2.50、失敗引当2.30で、総原価は48.81です。", "目標利益率30%なら税抜価格は69.73です。70に丸めて送料と税を加えられます。最低受注額が75なら、最終価格は75を下回らないようにします。"] },
      { id: "minimum-charge", title: "5. 最低受注料金を設定する", paragraphs: ["小さな案件でも連絡、設定、スライス、検品、決済処理が必要です。最低料金を設けると、利益率は高くても利益額が小さすぎる注文を防げます。作業を中断してでも受ける価値がある最小案件を基準に決めます。"] },
      { id: "professional-quote", title: "6. 計算結果を正式な見積書にする", paragraphs: ["顧客に内部原価をすべて見せる必要はありません。数量、材料、色、仕上げ、許容差や前提、単価、総額、納期、有効期限、送料、税を明記し、どのデータ版を価格計算したか記録します。", "設計や数量が変わった場合は改訂見積もりを作ります。無料の3Dプリント原価計算機では複数品目、利益率、最低料金を確認し、登録なしでPDFまたはCSVを出力できます。"] },
    ],
    checklistTitle: "繰り返し使える3Dプリント価格チェックリスト",
    checklist: ["スライサーの材料量と時間を使う。", "サポート、廃棄、消耗品を含める。", "機械占有と実作業を計算する。", "通常の造形失敗を配分する。", "梱包と案件固有の購入品を加える。", "正しい利益率式を使う。", "最低受注額と比較する。", "範囲、前提、納期、見積有効期限を記載する。"],
  },
  es: {
    title: "Cómo poner precio a impresiones 3D: costes, margen y fórmula de presupuesto",
    description: "Calcula el precio de una impresión 3D FDM con filamento, tiempo de máquina, trabajo, riesgo de fallo, gastos generales y margen objetivo.",
    readingTime: "10 min de lectura", toolLabel: "Abrir calculadora",
    toc: [{ id: "true-cost", label: "Calcular el coste real" }, { id: "risk-overhead", label: "Riesgo y gastos generales" }, { id: "profit-margin", label: "Aplicar el margen" }, { id: "worked-example", label: "Ejemplo completo" }, { id: "minimum-charge", label: "Fijar un mínimo" }, { id: "professional-quote", label: "Crear el presupuesto" }],
    faq: [
      { question: "¿Cuánto debería cobrar por gramo de impresión 3D?", answer: "Cobrar solo por gramo rara vez basta: omite máquina, preparación, acabado, fallos, embalaje y gastos generales. Calcula el filamento por gramo y añade el resto antes del margen." },
      { question: "¿Debo cobrar el tiempo de máquina?", answer: "Sí. La tarifa de máquina debe recuperar depreciación, mantenimiento, repuestos y el tiempo durante el cual la impresora no puede producir otro trabajo pagado." },
      { question: "¿Qué margen es razonable en impresión 3D?", answer: "No existe un margen universal. Depende del mercado, la complejidad, el riesgo y las necesidades del negocio. No confundas margen con recargo." },
      { question: "¿Cómo incluyo impresiones fallidas?", answer: "Estima tu tasa normal de fallos con datos propios y reparte el coste esperado entre los trabajos completados con éxito." },
    ],
    lead: "Un precio sostenible debe pagar mucho más que el filamento: impresora, electricidad, trabajo activo, desperdicio, fallos, embalaje y el beneficio necesario para mantener el negocio.",
    formulaLabel: "Fórmula breve", formula: "Presupuesto = coste total ÷ (1 − margen objetivo)", formulaBody: "Calcula primero el coste completo. Después aplica el margen, comprueba el mínimo de pedido y añade envío e impuestos cuando correspondan.",
    sections: [
      { id: "true-cost", title: "1. Calcula el coste real de la impresión", paragraphs: ["Separa los costes que cambian con el trabajo. Para el material usa el peso estimado por el laminador, que incluye soportes y material que el cliente no recibe. La tarifa de máquina reparte compra, mantenimiento, boquillas, camas y sustitución futura entre horas facturables realistas.", "La electricidad suele ser menor que material o mano de obra, pero importa en impresiones largas. Cobra el tiempo activo de revisión, laminado, preparación, cambio de material, retirada de soportes, lijado, montaje, control de calidad, comunicación y embalaje."], formula: "Coste de filamento = (gramos usados ÷ gramos de la bobina) × precio de la bobina" },
      { id: "risk-overhead", title: "2. Añade fallos, gastos generales y costes específicos", paragraphs: ["La adhesión, el filamento, la energía o la geometría pueden provocar fallos. Calcula una tasa normal con tu historial y distribuye el coste esperado entre los trabajos buenos.", "Incluye embalaje, tornillería, imanes, insertos, adhesivos, acabados externos, comisiones de plataforma y pagos. Software, espacio, seguro, administración y marketing pueden incorporarse a las tarifas o asignarse aparte, pero no dos veces."] },
      { id: "profit-margin", title: "3. Aplica correctamente el margen objetivo", paragraphs: ["Recargo y margen no son iguales. Un recargo del 30% sobre un coste de 50 produce un precio de 65 y un margen de solo 23,1%. Para un margen real del 30%, divide entre 0,70. Contrasta el precio con la demanda sin olvidar tu suelo de costes."], formula: "Precio = coste total ÷ (1 − margen objetivo)" },
      { id: "worked-example", title: "4. Ejemplo de presupuesto de impresión 3D", paragraphs: ["Un pedido FDM de dos piezas usa 180 g, ocupa 12 horas y requiere 45 minutos de preparación y acabado. Material con desperdicio cuesta 4,75; máquina 18; electricidad 0,26; trabajo 21; embalaje 2,50; y reserva por fallos 2,30. El coste total es 48,81.", "Con margen objetivo del 30%, el precio antes de impuestos es 69,73. Puede redondearse a 70 y añadir envío e impuestos. Si el mínimo del taller es 75, se aplica el mínimo."] },
      { id: "minimum-charge", title: "5. Establece un pedido mínimo", paragraphs: ["Los encargos pequeños también exigen mensajes, preparación, laminado, inspección y cobro. Un mínimo evita que un porcentaje rentable produzca muy poco beneficio en dinero. Fíjalo según el pedido más pequeño que compensa interrumpir tu flujo de trabajo."] },
      { id: "professional-quote", title: "6. Convierte el cálculo en un presupuesto profesional", paragraphs: ["El cliente no suele necesitar tu desglose interno. Indica cantidad, material, color, acabado, tolerancias o supuestos, precio unitario, total, plazo, validez, envío e impuestos. Registra la versión del archivo utilizada.", "Los cambios de diseño o cantidad deben generar una revisión. La calculadora gratuita permite varias partidas, comprobar margen, aplicar un mínimo y exportar PDF o CSV sin cuenta."] },
    ],
    checklistTitle: "Lista de control para precios repetibles",
    checklist: ["Usar material y tiempo del laminador.", "Incluir soportes, desperdicio y consumibles.", "Cobrar máquina y trabajo activo.", "Repartir fallos normales.", "Añadir embalaje y compras específicas.", "Aplicar la fórmula correcta de margen.", "Comprobar el mínimo de pedido.", "Documentar alcance, supuestos, entrega y validez."],
  },
  fr: {
    title: "Comment fixer le prix d’une impression 3D : coûts, marge et formule de devis",
    description: "Calculez le prix d’une impression 3D FDM avec le filament, le temps machine, le travail, le risque d’échec, les frais généraux et la marge cible.",
    readingTime: "10 min de lecture", toolLabel: "Ouvrir le calculateur",
    toc: [{ id: "true-cost", label: "Calculer le coût réel" }, { id: "risk-overhead", label: "Risque et frais généraux" }, { id: "profit-margin", label: "Appliquer la marge" }, { id: "worked-example", label: "Exemple chiffré" }, { id: "minimum-charge", label: "Fixer un minimum" }, { id: "professional-quote", label: "Créer le devis" }],
    faq: [
      { question: "Combien facturer par gramme imprimé ?", answer: "Un prix au gramme seul suffit rarement : il oublie le temps machine, la préparation, la finition, les échecs, l’emballage et les frais généraux. Calculez le filament au gramme puis ajoutez les autres coûts avant la marge." },
      { question: "Faut-il facturer le temps machine ?", answer: "Oui. Le taux machine doit couvrir amortissement, entretien, pièces et occupation de l’imprimante pendant laquelle aucun autre travail payant ne peut être produit." },
      { question: "Quelle marge viser en impression 3D ?", answer: "Il n’existe pas de marge universelle. Elle dépend du marché, de la complexité, du risque et de vos besoins. Ne confondez pas marge et majoration." },
      { question: "Comment intégrer les impressions ratées ?", answer: "Estimez votre taux d’échec habituel à partir de vos données et répartissez le coût attendu sur les travaux réussis." },
    ],
    lead: "Un prix durable doit financer plus que le filament : machine, électricité, travail actif, pertes, échecs, emballage et bénéfice nécessaire à la continuité de l’activité.",
    formulaLabel: "Formule courte", formula: "Devis = coût total ÷ (1 − marge cible)", formulaBody: "Calculez d’abord le coût complet, appliquez la marge, vérifiez le minimum de commande puis ajoutez livraison et taxes applicables.",
    sections: [
      { id: "true-cost", title: "1. Calculer le coût réel de l’impression", paragraphs: ["Séparez les coûts variables. Utilisez le poids estimé par le slicer, qui inclut supports et matière non livrée. Le taux horaire machine répartit achat, maintenance, buses, plateaux et remplacement futur sur des heures facturables réalistes.", "L’électricité est souvent inférieure à la matière ou au travail mais compte sur les longues impressions. Facturez le temps actif : contrôle du fichier, tranchage, réglage, changement de matière, retrait des supports, ponçage, assemblage, contrôle qualité, échanges et emballage."], formula: "Coût filament = (grammes utilisés ÷ poids bobine) × prix bobine" },
      { id: "risk-overhead", title: "2. Ajouter risque d’échec, frais généraux et coûts spécifiques", paragraphs: ["Adhérence, filament, alimentation ou géométrie peuvent provoquer un échec. Déduisez un taux normal de votre historique et répartissez son coût attendu sur les travaux réussis.", "Ajoutez emballage, quincaillerie, aimants, inserts, colles, finition sous-traitée et commissions. Logiciels, atelier, assurance, administration et marketing peuvent être intégrés aux taux ou répartis séparément, sans double comptage."] },
      { id: "profit-margin", title: "3. Appliquer correctement la marge cible", paragraphs: ["Majoration et marge diffèrent. Une majoration de 30% sur un coût de 50 donne 65, soit seulement 23,1% de marge. Pour une vraie marge de 30%, divisez par 0,70. Comparez ensuite le prix à la demande sans abandonner votre seuil de coût."], formula: "Prix = coût total ÷ (1 − marge cible)" },
      { id: "worked-example", title: "4. Exemple de devis d’impression 3D", paragraphs: ["Une commande FDM de deux pièces utilise 180 g, occupe 12 heures et demande 45 minutes de préparation et finition. Matière avec pertes : 4,75 ; machine : 18 ; électricité : 0,26 ; travail : 21 ; emballage : 2,50 ; réserve d’échec : 2,30. Total : 48,81.", "Avec 30% de marge cible, le prix hors taxes est 69,73. Il peut être arrondi à 70 puis complété par livraison et taxes. Si le minimum est 75, ce minimum s’applique."] },
      { id: "minimum-charge", title: "5. Fixer un minimum de commande", paragraphs: ["Même un petit travail exige messages, réglage, tranchage, contrôle et paiement. Un minimum empêche qu’un bon pourcentage de marge ne produise qu’un bénéfice dérisoire. Basez-le sur la plus petite commande qui justifie d’interrompre votre flux de travail."] },
      { id: "professional-quote", title: "6. Transformer le calcul en devis professionnel", paragraphs: ["Le client n’a généralement pas besoin du détail interne. Indiquez quantité, matière, couleur, finition, tolérances ou hypothèses, prix unitaire, total, délai, validité, livraison et taxes. Notez la version du fichier chiffrée.", "Toute modification de conception ou quantité doit produire une révision. Le calculateur gratuit gère plusieurs lignes, la marge, le minimum et l’export PDF ou CSV sans compte."] },
    ],
    checklistTitle: "Liste de contrôle pour une tarification répétable",
    checklist: ["Utiliser les estimations du slicer.", "Inclure supports, pertes et consommables.", "Facturer occupation machine et travail actif.", "Répartir les échecs normaux.", "Ajouter emballage et achats spécifiques.", "Employer la bonne formule de marge.", "Comparer au minimum de commande.", "Documenter périmètre, hypothèses, délai et validité."],
  },
  "pt-br": {
    title: "Como precificar impressão 3D: custos, margem e fórmula de orçamento",
    description: "Calcule o preço de uma impressão 3D FDM usando filamento, tempo de máquina, trabalho, risco de falha, despesas e margem desejada.",
    readingTime: "10 min de leitura", toolLabel: "Abrir calculadora",
    toc: [{ id: "true-cost", label: "Calcular o custo real" }, { id: "risk-overhead", label: "Risco e despesas" }, { id: "profit-margin", label: "Aplicar a margem" }, { id: "worked-example", label: "Exemplo completo" }, { id: "minimum-charge", label: "Definir valor mínimo" }, { id: "professional-quote", label: "Criar o orçamento" }],
    faq: [
      { question: "Quanto cobrar por grama de impressão 3D?", answer: "Cobrar só por grama raramente basta. Isso ignora máquina, preparação, acabamento, falhas, embalagem e despesas. Calcule o filamento por grama e some os demais custos antes da margem." },
      { question: "Devo cobrar o tempo da impressora?", answer: "Sim. A taxa de máquina deve recuperar depreciação, manutenção, peças e o período em que a impressora não pode executar outro trabalho pago." },
      { question: "Qual margem é razoável para impressão 3D?", answer: "Não existe margem universal. Ela depende do mercado, complexidade, risco e necessidades do negócio. Margem não é a mesma coisa que acréscimo." },
      { question: "Como incluir impressões que falham?", answer: "Estime sua taxa normal de falha com dados próprios e distribua o custo esperado entre os trabalhos concluídos." },
    ],
    lead: "Um preço sustentável paga muito mais que o filamento: impressora, energia, trabalho ativo, desperdício, falhas, embalagem e o lucro necessário para manter o negócio.",
    formulaLabel: "Fórmula resumida", formula: "Orçamento = custo total ÷ (1 − margem desejada)", formulaBody: "Calcule o custo completo, aplique a margem, compare com o pedido mínimo e acrescente frete e impostos aplicáveis.",
    sections: [
      { id: "true-cost", title: "1. Calcule o custo real da impressão", paragraphs: ["Separe os custos que variam com o trabalho. Use o peso estimado pelo fatiador, incluindo suportes. A taxa horária da máquina distribui compra, manutenção, bicos, mesas e futura substituição por horas faturáveis realistas.", "Energia costuma custar menos que material ou mão de obra, mas pesa em impressões longas. Cobre o tempo ativo de revisão, fatiamento, preparação, troca de material, remoção de suportes, lixamento, montagem, inspeção, comunicação e embalagem."], formula: "Custo do filamento = (gramas usadas ÷ peso do rolo) × preço do rolo" },
      { id: "risk-overhead", title: "2. Some risco de falha, despesas e custos específicos", paragraphs: ["Aderência, filamento, energia ou geometria podem causar falhas. Calcule uma taxa normal a partir do histórico e distribua o custo esperado entre trabalhos bem-sucedidos.", "Inclua embalagem, ferragens, ímãs, insertos, colas, acabamento terceirizado e taxas de plataforma e pagamento. Software, espaço, seguro, administração e marketing podem entrar nas taxas ou ser rateados separadamente, sem duplicidade."] },
      { id: "profit-margin", title: "3. Aplique corretamente a margem desejada", paragraphs: ["Acréscimo e margem são diferentes. Acrescentar 30% a um custo de 50 gera preço de 65 e margem de apenas 23,1%. Para margem real de 30%, divida por 0,70. Compare o resultado com a demanda sem ignorar seu piso de custos."], formula: "Preço = custo total ÷ (1 − margem desejada)" },
      { id: "worked-example", title: "4. Exemplo de orçamento de impressão 3D", paragraphs: ["Um pedido FDM de duas peças usa 180 g, ocupa 12 horas e exige 45 minutos de preparação e acabamento. Material com perda custa 4,75; máquina 18; energia 0,26; trabalho 21; embalagem 2,50; reserva de falha 2,30. Total: 48,81.", "Com margem de 30%, o preço antes de impostos é 69,73. Pode ser arredondado para 70 e receber frete e tributos. Se o mínimo for 75, prevalece o mínimo."] },
      { id: "minimum-charge", title: "5. Defina um valor mínimo", paragraphs: ["Pedidos pequenos ainda exigem mensagens, preparação, fatiamento, inspeção e cobrança. Um mínimo evita que uma boa margem percentual gere lucro pequeno demais em dinheiro. Baseie-o no menor pedido que vale interromper seu fluxo."] },
      { id: "professional-quote", title: "6. Transforme o cálculo em orçamento profissional", paragraphs: ["O cliente normalmente não precisa do detalhamento interno. Informe quantidade, material, cor, acabamento, tolerâncias ou premissas, preço unitário, total, prazo, validade, frete e impostos. Registre a versão do arquivo calculada.", "Mudanças de design ou quantidade pedem revisão. A calculadora gratuita aceita vários itens, confere margem, aplica mínimo e exporta PDF ou CSV sem conta."] },
    ],
    checklistTitle: "Checklist para precificação repetível",
    checklist: ["Usar material e tempo do fatiador.", "Incluir suportes, perdas e consumíveis.", "Cobrar ocupação da máquina e trabalho ativo.", "Distribuir falhas normais.", "Somar embalagem e compras específicas.", "Aplicar a fórmula correta de margem.", "Comparar com o pedido mínimo.", "Documentar escopo, premissas, entrega e validade."],
  },
  ko: {
    title: "3D 프린팅 가격 책정 방법: 원가, 마진, 견적 공식",
    description: "필라멘트, 장비 시간, 인건비, 실패 위험, 간접비와 목표 마진으로 FDM 3D 프린팅 가격을 계산합니다.",
    readingTime: "읽는 시간 10분", toolLabel: "계산기 열기",
    toc: [{ id: "true-cost", label: "실제 원가 계산" }, { id: "risk-overhead", label: "위험과 간접비" }, { id: "profit-margin", label: "목표 마진 적용" }, { id: "worked-example", label: "계산 예시" }, { id: "minimum-charge", label: "최소 요금 설정" }, { id: "professional-quote", label: "전문 견적 작성" }],
    faq: [
      { question: "3D 프린팅은 g당 얼마를 받아야 하나요?", answer: "무게만으로 가격을 정하면 장비 시간, 준비, 후처리, 실패, 포장과 간접비가 빠집니다. g당 필라멘트 비용을 계산한 뒤 다른 비용과 마진을 더하세요." },
      { question: "3D 프린터 장비 시간도 청구해야 하나요?", answer: "네. 장비 요율은 감가상각, 유지보수, 교체 부품과 해당 작업 동안 다른 유료 작업을 할 수 없는 점을 반영해야 합니다." },
      { question: "3D 프린팅의 적정 마진은 얼마인가요?", answer: "모든 사업자에게 맞는 하나의 마진은 없습니다. 시장, 복잡도, 위험과 사업 목표에 따라 정하고 실제 주문 결과로 조정해야 합니다." },
      { question: "출력 실패는 견적에 어떻게 넣나요?", answer: "과거 기록으로 정상 실패율을 추정하고 예상 실패 비용을 성공한 작업들에 나누어 반영합니다." },
    ],
    lead: "지속 가능한 3D 프린팅 가격은 필라멘트만이 아니라 프린터, 전기, 실제 작업 시간, 폐기, 실패, 포장과 사업을 유지할 이익까지 회수해야 합니다.",
    formulaLabel: "기본 공식", formula: "견적가 = 총원가 ÷ (1 − 목표 마진)", formulaBody: "먼저 전체 작업 원가를 계산하고 마진 공식을 적용한 뒤 최소 주문액, 배송비와 해당 세금을 더합니다.",
    sections: [
      { id: "true-cost", title: "1. 출력의 실제 원가를 계산합니다", paragraphs: ["작업에 따라 달라지는 비용을 분리하세요. 재료는 서포트까지 포함하는 슬라이서 예상 사용량을 사용합니다. 장비 시간 요율은 구입비, 유지보수, 노즐, 베드와 향후 교체 비용을 현실적인 유료 가동 시간에 배분합니다.", "전기료는 재료나 인건비보다 작은 경우가 많지만 장시간 출력에서는 중요합니다. 파일 검토, 슬라이싱, 설정, 재료 교체, 서포트 제거, 연마, 조립, 검사, 고객 응대와 포장처럼 사람이 직접 일하는 시간을 청구하세요."], formula: "필라멘트 비용 = (사용 g ÷ 스풀 g) × 스풀 가격" },
      { id: "risk-overhead", title: "2. 실패 위험, 간접비와 작업별 비용을 더합니다", paragraphs: ["접착, 필라멘트, 전원이나 형상 문제로 출력이 실패할 수 있습니다. 자체 기록에서 정상 실패율을 구해 예상 손실을 성공 작업에 배분하세요.", "포장, 하드웨어, 자석, 인서트, 접착제, 외주 후처리, 플랫폼과 결제 수수료를 포함합니다. 소프트웨어, 공간, 보험, 행정과 마케팅은 장비·인건비 요율에 넣거나 별도로 배분하되 중복 계산하지 않습니다."] },
      { id: "profit-margin", title: "3. 목표 마진을 올바르게 적용합니다", paragraphs: ["원가 가산율과 매출 마진은 다릅니다. 원가 50에 30%를 더하면 가격은 65지만 마진은 약 23.1%입니다. 실제 30% 마진을 원하면 원가를 0.70으로 나눕니다. 결과 가격은 시장 수요로 검증하되 원가 하한을 잊지 마세요."], formula: "목표 가격 = 총원가 ÷ (1 − 목표 마진)" },
      { id: "worked-example", title: "4. 3D 프린팅 견적 예시", paragraphs: ["부품 2개의 FDM 주문이 필라멘트 180g, 장비 12시간, 준비와 후처리 45분을 사용한다고 가정합니다. 재료와 폐기 4.75, 장비 18, 전기 0.26, 인건비 21, 포장 2.50, 실패 충당 2.30으로 총원가는 48.81입니다.", "목표 마진 30%면 세전 가격은 69.73입니다. 70으로 정리한 뒤 배송과 세금을 더할 수 있습니다. 최소 주문액이 75라면 75를 적용합니다."] },
      { id: "minimum-charge", title: "5. 최소 주문 요금을 설정합니다", paragraphs: ["작은 주문도 메시지, 설정, 슬라이싱, 검사와 결제가 필요합니다. 최소 요금은 비율상 수익성이 있어도 실제 이익액이 너무 작은 작업을 막아 줍니다. 작업 흐름을 중단할 가치가 있는 가장 작은 주문을 기준으로 정하세요."] },
      { id: "professional-quote", title: "6. 계산을 전문 견적으로 바꿉니다", paragraphs: ["고객에게 내부 원가를 모두 보여줄 필요는 없습니다. 수량, 재료, 색상, 마감, 공차나 가정, 단가, 총액, 납기, 유효기간, 배송과 세금을 명시하고 가격을 계산한 파일 버전을 기록하세요.", "설계나 수량 변경은 수정 견적을 만들어야 합니다. 무료 계산기에서 여러 품목, 마진, 최소 요금을 확인하고 가입 없이 PDF 또는 CSV로 내보낼 수 있습니다."] },
    ],
    checklistTitle: "반복 가능한 3D 프린팅 가격 체크리스트",
    checklist: ["슬라이서의 재료와 시간 예상값 사용.", "서포트, 폐기와 소모품 포함.", "장비 점유와 실제 작업 시간 계산.", "정상 실패 비용 배분.", "포장과 작업별 구매품 추가.", "올바른 마진 공식 적용.", "최소 주문액과 비교.", "범위, 가정, 납기와 견적 유효기간 기록."],
  },
};
