import type { Locale } from "@/lib/i18n/config";
import type { GuidesIndexCopy, GuideUiCopy } from "./types";

export const guideUi: Record<Locale, GuideUiCopy> = {
  en: { home: "Home", guides: "Guides", guide: "Guide", category: "Pricing & quoting", updated: "Updated", by: "By zaps.work", onThisPage: "On this page", toolTitle: "Put the formula to work", toolDescription: "Use your own costs and target margin to build a quote in the free calculator.", freeNoSignup: "Free · No sign-up", commonQuestions: "Common questions", faqTitle: "Frequently asked questions", finalKicker: "Build your quote", finalTitle: "Use your numbers, not a generic market average." },
  "zh-hant": { home: "首頁", guides: "指南", guide: "指南", category: "成本與報價", updated: "更新", by: "zaps.work 編寫", onThisPage: "本頁內容", toolTitle: "把公式用在真實工作上", toolDescription: "在免費計算器中輸入自己的成本與目標毛利，建立可用的報價。", freeNoSignup: "免費 · 無須註冊", commonQuestions: "常見問題", faqTitle: "常見問題解答", finalKicker: "建立你的報價", finalTitle: "使用自己的數據，不依賴籠統的市場均價。" },
  de: { home: "Startseite", guides: "Leitfäden", guide: "Leitfaden", category: "Kalkulation & Angebote", updated: "Aktualisiert", by: "Von zaps.work", onThisPage: "Auf dieser Seite", toolTitle: "Formel direkt anwenden", toolDescription: "Nutze deine eigenen Kosten und deine Zielmarge im kostenlosen Rechner.", freeNoSignup: "Kostenlos · Ohne Anmeldung", commonQuestions: "Häufige Fragen", faqTitle: "Häufig gestellte Fragen", finalKicker: "Angebot erstellen", finalTitle: "Nutze deine eigenen Zahlen statt eines pauschalen Marktpreises." },
  ja: { home: "ホーム", guides: "ガイド", guide: "ガイド", category: "原価計算と見積もり", updated: "更新日", by: "zaps.work", onThisPage: "目次", toolTitle: "計算式を実際の見積もりに", toolDescription: "無料計算機に自社の原価と目標利益率を入力して見積もりを作成できます。", freeNoSignup: "無料 · 登録不要", commonQuestions: "よくある質問", faqTitle: "よくある質問と回答", finalKicker: "見積もりを作成", finalTitle: "一般的な相場ではなく、自分の数字で価格を決めましょう。" },
  es: { home: "Inicio", guides: "Guías", guide: "Guía", category: "Costes y presupuestos", updated: "Actualizado", by: "Por zaps.work", onThisPage: "En esta página", toolTitle: "Aplica la fórmula", toolDescription: "Usa tus propios costes y margen objetivo en la calculadora gratuita.", freeNoSignup: "Gratis · Sin registro", commonQuestions: "Preguntas comunes", faqTitle: "Preguntas frecuentes", finalKicker: "Crea tu presupuesto", finalTitle: "Usa tus propios números, no una media genérica del mercado." },
  fr: { home: "Accueil", guides: "Guides", guide: "Guide", category: "Coûts et devis", updated: "Mis à jour", by: "Par zaps.work", onThisPage: "Dans ce guide", toolTitle: "Appliquez la formule", toolDescription: "Utilisez vos propres coûts et votre marge cible dans le calculateur gratuit.", freeNoSignup: "Gratuit · Sans inscription", commonQuestions: "Questions courantes", faqTitle: "Questions fréquentes", finalKicker: "Créez votre devis", finalTitle: "Utilisez vos chiffres, pas une moyenne générique du marché." },
  "pt-br": { home: "Início", guides: "Guias", guide: "Guia", category: "Custos e orçamentos", updated: "Atualizado", by: "Por zaps.work", onThisPage: "Neste guia", toolTitle: "Aplique a fórmula", toolDescription: "Use seus próprios custos e a margem desejada na calculadora gratuita.", freeNoSignup: "Grátis · Sem cadastro", commonQuestions: "Dúvidas comuns", faqTitle: "Perguntas frequentes", finalKicker: "Crie seu orçamento", finalTitle: "Use seus próprios números, não uma média genérica do mercado." },
  ko: { home: "홈", guides: "가이드", guide: "가이드", category: "원가 및 견적", updated: "업데이트", by: "zaps.work 작성", onThisPage: "목차", toolTitle: "계산식을 바로 적용하세요", toolDescription: "무료 계산기에 실제 비용과 목표 마진을 입력해 견적을 만드세요.", freeNoSignup: "무료 · 가입 불필요", commonQuestions: "자주 묻는 질문", faqTitle: "자주 묻는 질문과 답변", finalKicker: "견적 만들기", finalTitle: "일반적인 시세가 아니라 자신의 수치로 가격을 정하세요." },
};

export const guidesIndexCopy: Record<Locale, GuidesIndexCopy> = {
  en: { metadataTitle: "Pricing & Quote Guides for Small Businesses | zaps.work", metadataDescription: "Practical guides to job costing, profit margins, and customer-ready quotes for 3D printing and local service work.", kicker: "Guides", heading: "Price real work with confidence.", intro: "Practical formulas and worked examples for turning job costs into clear, profitable customer quotes.", listKicker: "Start here", listHeading: "Pricing guides", listIntro: "Each guide explains the method, then links to a free calculator where you can use your own rates.", readGuide: "Read guide", cards: [
    { category: "3D printing", title: "How to Price 3D Prints", description: "Turn filament, machine time, labor, failure risk, and target margin into a defensible customer quote.", time: "10 min read" },
    { category: "Pressure washing", title: "How to Price Pressure Washing Jobs", description: "Estimate surface work, operating costs, crew time, minimum charges, and profit without guessing.", time: "9 min read" },
  ] },
  "zh-hant": { metadataTitle: "小型企業成本與報價指南 | zaps.work", metadataDescription: "用實際公式了解 3D 列印與高壓清洗的工作成本、毛利與客戶報價。", kicker: "指南", heading: "更有把握地為真實工作定價。", intro: "用清楚的公式與實例，把工作成本轉換成有利潤、可交付客戶的報價。", listKicker: "從這裡開始", listHeading: "定價指南", listIntro: "每篇指南先解釋方法，再連結免費計算器，讓你套用自己的費率。", readGuide: "閱讀指南", cards: [
    { category: "3D 列印", title: "3D 列印如何定價", description: "把耗材、機器時間、人工、失敗風險與目標毛利轉換成合理報價。", time: "閱讀約 10 分鐘" },
    { category: "高壓清洗", title: "高壓清洗工作如何報價", description: "依面積、工時、營運成本、最低收費與毛利建立估價。", time: "閱讀約 9 分鐘" },
  ] },
  de: { metadataTitle: "Leitfäden für Kalkulation und Angebote | zaps.work", metadataDescription: "Praxisnahe Leitfäden zu Auftragskosten, Gewinnmargen und Angeboten für 3D-Druck und Reinigungsarbeiten.", kicker: "Leitfäden", heading: "Reale Aufträge sicher kalkulieren.", intro: "Klare Formeln und Beispiele, mit denen aus Auftragskosten ein profitables Kundenangebot wird.", listKicker: "Hier starten", listHeading: "Kalkulationsleitfäden", listIntro: "Jeder Leitfaden erklärt die Methode und führt anschließend zu einem kostenlosen Rechner für deine eigenen Werte.", readGuide: "Leitfaden lesen", cards: [
    { category: "3D-Druck", title: "3D-Druck richtig kalkulieren", description: "Filament, Maschinenzeit, Arbeit, Ausfallrisiko und Zielmarge zu einem belastbaren Angebot verbinden.", time: "10 Min. Lesezeit" },
    { category: "Hochdruckreinigung", title: "Hochdruckreinigungsaufträge kalkulieren", description: "Fläche, Betriebskosten, Arbeitszeit, Mindestpreis und Gewinn ohne Raten berechnen.", time: "9 Min. Lesezeit" },
  ] },
  ja: { metadataTitle: "小規模事業者向け原価計算・見積もりガイド | zaps.work", metadataDescription: "3Dプリントと高圧洗浄の原価、利益率、顧客向け見積もりを実例で解説します。", kicker: "ガイド", heading: "実際の仕事を根拠を持って価格設定。", intro: "原価から利益を確保した顧客向け見積もりを作るための計算式と実例です。", listKicker: "ここから始める", listHeading: "価格設定ガイド", listIntro: "各ガイドで計算方法を理解し、無料計算機に自社の数字を入力できます。", readGuide: "ガイドを読む", cards: [
    { category: "3Dプリント", title: "3Dプリントの価格設定方法", description: "材料、機械時間、人件費、失敗リスク、目標利益率から見積価格を決めます。", time: "読了約10分" },
    { category: "高圧洗浄", title: "高圧洗浄作業の見積もり方法", description: "面積、作業時間、運営費、最低料金、利益率から適正価格を計算します。", time: "読了約9分" },
  ] },
  es: { metadataTitle: "Guías de costes y presupuestos para pequeños negocios | zaps.work", metadataDescription: "Guías prácticas sobre costes, márgenes y presupuestos para impresión 3D y servicios de limpieza a presión.", kicker: "Guías", heading: "Pon precio al trabajo real con confianza.", intro: "Fórmulas claras y ejemplos para convertir costes en presupuestos rentables y fáciles de enviar.", listKicker: "Empieza aquí", listHeading: "Guías de precios", listIntro: "Cada guía explica el método y enlaza una calculadora gratuita para usar tus propias tarifas.", readGuide: "Leer guía", cards: [
    { category: "Impresión 3D", title: "Cómo poner precio a impresiones 3D", description: "Convierte filamento, tiempo de máquina, trabajo, riesgo de fallo y margen en un presupuesto defendible.", time: "10 min de lectura" },
    { category: "Lavado a presión", title: "Cómo presupuestar trabajos de lavado a presión", description: "Calcula superficie, costes operativos, horas, mínimo de servicio y beneficio sin adivinar.", time: "9 min de lectura" },
  ] },
  fr: { metadataTitle: "Guides de coûts et de devis pour petites entreprises | zaps.work", metadataDescription: "Guides pratiques sur les coûts, les marges et les devis pour l’impression 3D et le nettoyage haute pression.", kicker: "Guides", heading: "Chiffrez le travail réel avec confiance.", intro: "Des formules claires et des exemples pour transformer les coûts en devis rentables et prêts à envoyer.", listKicker: "Commencer ici", listHeading: "Guides de tarification", listIntro: "Chaque guide explique la méthode puis renvoie vers un calculateur gratuit pour utiliser vos propres tarifs.", readGuide: "Lire le guide", cards: [
    { category: "Impression 3D", title: "Comment fixer le prix d’une impression 3D", description: "Transformez filament, temps machine, travail, risque d’échec et marge en un devis solide.", time: "10 min de lecture" },
    { category: "Nettoyage haute pression", title: "Comment chiffrer un nettoyage haute pression", description: "Estimez surface, coûts, temps d’équipe, minimum de facturation et bénéfice sans deviner.", time: "9 min de lecture" },
  ] },
  "pt-br": { metadataTitle: "Guias de custos e orçamentos para pequenos negócios | zaps.work", metadataDescription: "Guias práticos de custos, margens e orçamentos para impressão 3D e serviços de lavagem de alta pressão.", kicker: "Guias", heading: "Calcule trabalhos reais com confiança.", intro: "Fórmulas claras e exemplos para transformar custos em orçamentos lucrativos e prontos para enviar.", listKicker: "Comece aqui", listHeading: "Guias de precificação", listIntro: "Cada guia explica o método e leva a uma calculadora gratuita para usar suas próprias taxas.", readGuide: "Ler guia", cards: [
    { category: "Impressão 3D", title: "Como precificar impressões 3D", description: "Transforme filamento, tempo de máquina, trabalho, risco de falha e margem em um orçamento defensável.", time: "10 min de leitura" },
    { category: "Lavagem de alta pressão", title: "Como orçar serviços de lavagem de alta pressão", description: "Calcule área, custos operacionais, horas da equipe, valor mínimo e lucro sem chutes.", time: "9 min de leitura" },
  ] },
  ko: { metadataTitle: "소규모 사업자를 위한 원가 및 견적 가이드 | zaps.work", metadataDescription: "3D 프린팅과 고압 세척 작업의 원가, 마진, 고객 견적을 실용적인 예제로 설명합니다.", kicker: "가이드", heading: "실제 작업 가격을 자신 있게 정하세요.", intro: "작업 비용을 수익성 있고 명확한 고객 견적으로 바꾸는 공식과 예제를 제공합니다.", listKicker: "여기서 시작", listHeading: "가격 책정 가이드", listIntro: "각 가이드에서 방법을 익힌 뒤 무료 계산기에 자신의 요율을 입력할 수 있습니다.", readGuide: "가이드 읽기", cards: [
    { category: "3D 프린팅", title: "3D 프린팅 가격 책정 방법", description: "필라멘트, 장비 시간, 인건비, 실패 위험과 목표 마진을 근거 있는 견적으로 바꿉니다.", time: "읽는 시간 10분" },
    { category: "고압 세척", title: "고압 세척 작업 견적 방법", description: "면적, 운영비, 작업 시간, 최소 요금과 이익을 추측 없이 계산합니다.", time: "읽는 시간 9분" },
  ] },
};
