"use client";

import { SimpleQuoteCalculator, type SimpleQuoteConfig } from "@/components/simple-quote-calculator";
import { calculateCncQuote, convertCncCurrency, createDefaultCncInput, type CncInput } from "@/lib/calculators/cnc";
import { calculateFreelanceQuote, convertFreelanceCurrency, createDefaultFreelanceInput, type FreelanceInput } from "@/lib/calculators/freelance";
import { calculateLawnCareQuote, convertLawnCareCurrency, createDefaultLawnCareInput, type LawnCareInput } from "@/lib/calculators/lawn-care";
import type { Locale } from "@/lib/i18n/config";
import type { Dictionary } from "@/lib/i18n/dictionaries";
import { getNewToolCopy, type NewToolKind } from "@/lib/i18n/new-tools";

const common = (copy: ReturnType<typeof getNewToolCopy>) => ({ title: copy.heading, privacyNote: "Your rates and customer details stay in your browser and are not stored.", targetQuote: "Target quote", directCostLabel: "Direct cost", profitLabel: "Profit", marginLabel: "Margin", breakdownTitle: "Quote breakdown", printLabel: "Print / save PDF", exportLabel: "Export CSV", viewLabel: "View quote" });
function freelanceConfig(locale: Locale): SimpleQuoteConfig { const copy = getNewToolCopy(locale, "freelance"); return { ...common(copy), category: "freelance", fields: [{ key: "hours", label: "Scope hours", section: "Scope", suffix: "h", max: 10_000 }, { key: "hourlyRate", label: "Hourly rate", section: "Scope", suffix: "currency" }, { key: "revisions", label: "Included revisions", section: "Scope", max: 100, step: 1 }, { key: "revisionHours", label: "Hours per revision", section: "Scope", suffix: "h" }, { key: "fixedCosts", label: "Fixed costs", section: "Costs", suffix: "currency" }, { key: "rushPercent", label: "Rush premium", section: "Costs", suffix: "%", max: 200 }, { key: "targetMargin", label: "Target margin", section: "Pricing", suffix: "%", max: 95 }, { key: "minimumFee", label: "Minimum job fee", section: "Pricing", suffix: "currency" }, { key: "taxRate", label: "Tax", section: "Pricing", suffix: "%", max: 100 }], createDefaultInput: (currency) => createDefaultFreelanceInput(currency), convertCurrency: (input, from, to) => convertFreelanceCurrency(input as FreelanceInput, from, to), calculate: (input) => calculateFreelanceQuote(input as FreelanceInput), breakdown: (result) => { const value = result as ReturnType<typeof calculateFreelanceQuote>; return [{ label: "Labor", amount: value.laborCost }, { label: "Fixed costs", amount: value.input.fixedCosts }]; }, lines: (result, money) => { const value = result as ReturnType<typeof calculateFreelanceQuote>; return [{ id: "scope", description: "Freelance scope", detail: `${value.baseHours.toFixed(1)} h`, quantity: value.baseHours, unitPrice: money(value.input.hourlyRate), amount: money(value.laborCost) }]; } }; }
function cncConfig(locale: Locale): SimpleQuoteConfig { const copy = getNewToolCopy(locale, "cnc"); return { ...common(copy), category: "cnc-machining", fields: [{ key: "quantity", label: "Quantity", section: "Batch", min: 1, max: 100_000, step: 1 }, { key: "stockVolumeCm3", label: "Stock volume per part", section: "Material", suffix: "cm³" }, { key: "materialCostPerCm3", label: "Material cost per cm³", section: "Material", suffix: "currency" }, { key: "scrapPercent", label: "Material scrap", section: "Material", suffix: "%", max: 100 }, { key: "programmingHours", label: "Programming hours", section: "Machining", suffix: "h" }, { key: "setupHours", label: "Setup hours", section: "Machining", suffix: "h" }, { key: "cycleMinutes", label: "Cycle time per part", section: "Machining", suffix: "min" }, { key: "inspectionMinutes", label: "Inspection per part", section: "Machining", suffix: "min" }, { key: "machineRate", label: "Machine rate", section: "Machining", suffix: "currency" }, { key: "laborRate", label: "Labor rate", section: "Machining", suffix: "currency" }, { key: "toolingCost", label: "Tooling", section: "Pricing", suffix: "currency" }, { key: "finishingCost", label: "Finishing", section: "Pricing", suffix: "currency" }, { key: "targetMargin", label: "Target margin", section: "Pricing", suffix: "%", max: 95 }, { key: "minimumFee", label: "Minimum order fee", section: "Pricing", suffix: "currency" }, { key: "taxRate", label: "Tax", section: "Pricing", suffix: "%", max: 100 }], createDefaultInput: (currency) => createDefaultCncInput(currency), convertCurrency: (input, from, to) => convertCncCurrency(input as CncInput, from, to), calculate: (input) => calculateCncQuote(input as CncInput), breakdown: (result) => { const value = result as ReturnType<typeof calculateCncQuote>; return [{ label: "Material", amount: value.materialCost }, { label: "Machine", amount: value.machineCost }, { label: "Labor", amount: value.laborCost }, { label: "Tooling & finishing", amount: value.input.toolingCost + value.input.finishingCost }]; }, lines: (result, money) => { const value = result as ReturnType<typeof calculateCncQuote>; return [{ id: "batch", description: "CNC milling batch", detail: `${value.input.quantity} parts`, quantity: value.input.quantity, unitPrice: money(value.total / value.input.quantity), amount: money(value.total) }]; } }; }
function lawnConfig(locale: Locale): SimpleQuoteConfig { const copy = getNewToolCopy(locale, "lawn-care"); return { ...common(copy), category: "lawn-care", fields: [{ key: "area", label: "Mowable area", section: "Property", suffix: "sq ft" }, { key: "condition", label: "Grass condition", section: "Property", options: [{ value: "light", label: "Light" }, { value: "standard", label: "Standard" }, { value: "overgrown", label: "Overgrown" }] }, { key: "productionRate", label: "Crew production rate", section: "Crew", suffix: "sq ft/h", min: .01 }, { key: "crewSize", label: "Crew size", section: "Crew", min: 1, max: 100, step: 1 }, { key: "laborRate", label: "Labor rate", section: "Crew", suffix: "currency" }, { key: "equipmentCost", label: "Equipment & fuel", section: "Costs", suffix: "currency" }, { key: "travelCost", label: "Travel", section: "Costs", suffix: "currency" }, { key: "addOnAmount", label: "Add-ons", section: "Costs", suffix: "currency" }, { key: "overheadPercent", label: "Labor overhead", section: "Pricing", suffix: "%", max: 100 }, { key: "targetMargin", label: "Target margin", section: "Pricing", suffix: "%", max: 95 }, { key: "minimumFee", label: "Minimum service fee", section: "Pricing", suffix: "currency" }, { key: "taxRate", label: "Tax", section: "Pricing", suffix: "%", max: 100 }], createDefaultInput: (currency) => createDefaultLawnCareInput(currency), convertCurrency: (input, from, to) => convertLawnCareCurrency(input as LawnCareInput, from, to), calculate: (input) => calculateLawnCareQuote(input as LawnCareInput), breakdown: (result) => { const value = result as ReturnType<typeof calculateLawnCareQuote>; return [{ label: "Crew labor", amount: value.laborCost }, { label: "Labor overhead", amount: value.overheadCost }, { label: "Equipment & fuel", amount: value.input.equipmentCost }, { label: "Travel & add-ons", amount: value.input.travelCost + value.input.addOnAmount }]; }, lines: (result, money) => { const value = result as ReturnType<typeof calculateLawnCareQuote>; return [{ id: "service", description: "Lawn service", detail: `${value.crewHours.toFixed(1)} crew h`, quantity: 1, unitPrice: money(value.subtotal), amount: money(value.subtotal) }]; }, notes: (input) => [{ label: "Condition", value: String(input.condition) }] }; }
export function NewToolCalculator({ kind, locale, dictionary }: { kind: NewToolKind; locale: Locale; dictionary: Dictionary }) { const config = kind === "freelance" ? freelanceConfig(locale) : kind === "cnc" ? cncConfig(locale) : lawnConfig(locale); return <SimpleQuoteCalculator locale={locale} dictionary={dictionary} config={config} />; }
