"use client";

import { useMemo } from "react";
import { SimpleQuoteCalculator, type SimpleQuoteConfig } from "@/components/simple-quote-calculator";
import { calculateCncQuote, convertCncCurrency, createDefaultCncInput, type CncInput } from "@/lib/calculators/cnc";
import { calculateFreelanceQuote, convertFreelanceCurrency, createDefaultFreelanceInput, type FreelanceInput } from "@/lib/calculators/freelance";
import { calculateLawnCareQuote, convertLawnCareCurrency, createDefaultLawnCareInput, type LawnCareInput } from "@/lib/calculators/lawn-care";
import { calculateWindowCleaningQuote, convertWindowCleaningCurrency, createDefaultWindowCleaningInput, type WindowCleaningInput } from "@/lib/calculators/window-cleaning";
import type { Locale } from "@/lib/i18n/config";
import type { Dictionary } from "@/lib/i18n/dictionaries";
import { getNewToolCopy, type NewToolKind } from "@/lib/i18n/new-tools";
import { withSimplifiedChinese } from "@/lib/i18n/simplified-chinese";

const CM3_PER_IN3 = 16.387064;
const SQFT_PER_SQM = 10.7639;
type Input = Record<string, string | number>;

type ToolText = {
  privacy: string; directCost: string; breakdown: string; adjustment: string; print: string; view: string;
  scope: string; costs: string; batch: string; material: string; machining: string; property: string; crew: string;
  scopeHours: string; hourlyRate: string; extraRevisions: string; hoursPerRevision: string; fixedCosts: string; rushPremium: string;
  freelanceService: string; scopeDetail: string; revisionDetail: string;
  stockVolume: string; materialCost: string; scrap: string; programming: string; setup: string; cycle: string; inspection: string; tooling: string; finishing: string; minimumOrder: string; cncService: string; parts: string;
  mowableArea: string; grassCondition: string; productionRate: string; crewSize: string; equipment: string; travel: string; addOns: string; overhead: string; minimumService: string; lawnService: string; crewHours: string; light: string; standard: string; overgrown: string;
};

const baseTexts: Record<Exclude<Locale, "zh-hans">, ToolText> = {
  en: { privacy: "Your rates and customer details stay in your browser and are not stored.", directCost: "Direct cost", breakdown: "Quote breakdown", adjustment: "Pricing adjustment", print: "Print / save PDF", view: "View quote", scope: "Scope", costs: "Costs", batch: "Batch", material: "Material", machining: "Machining", property: "Property", crew: "Crew", scopeHours: "Scope hours", hourlyRate: "Hourly rate", extraRevisions: "Extra revisions", hoursPerRevision: "Hours per revision", fixedCosts: "Fixed costs", rushPremium: "Rush premium", freelanceService: "Freelance project", scopeDetail: "project hours", revisionDetail: "revision hours", stockVolume: "Stock volume per part", materialCost: "Material cost per volume", scrap: "Material scrap", programming: "Programming hours", setup: "Setup hours", cycle: "Cycle time per part", inspection: "Inspection per part", tooling: "Tooling", finishing: "Finishing", minimumOrder: "Minimum order fee", cncService: "CNC machining batch", parts: "parts", mowableArea: "Mowable area", grassCondition: "Grass condition", productionRate: "Crew production rate", crewSize: "Crew size", equipment: "Equipment & fuel", travel: "Travel", addOns: "Add-ons", overhead: "Labor overhead", minimumService: "Minimum service fee", lawnService: "Lawn service", crewHours: "crew h", light: "Light", standard: "Standard", overgrown: "Overgrown" },
  "zh-hant": { privacy: "你的費率與客戶資料只保留在瀏覽器中，不會被儲存。", directCost: "直接成本", breakdown: "報價明細", adjustment: "定價調整", print: "列印／儲存 PDF", view: "查看報價", scope: "工作範圍", costs: "成本", batch: "批次", material: "材料", machining: "加工", property: "場地", crew: "人員", scopeHours: "工作時數", hourlyRate: "每小時費率", extraRevisions: "額外修改次數", hoursPerRevision: "每次修改時數", fixedCosts: "固定成本", rushPremium: "急件加價", freelanceService: "自由工作者專案", scopeDetail: "專案時數", revisionDetail: "修改時數", stockVolume: "每件毛胚體積", materialCost: "每單位材料成本", scrap: "材料耗損", programming: "程式編寫時數", setup: "設定時數", cycle: "每件循環時間", inspection: "每件檢驗時間", tooling: "刀具", finishing: "後處理", minimumOrder: "最低訂單費", cncService: "CNC 加工批次", parts: "件", mowableArea: "可修剪面積", grassCondition: "草坪狀況", productionRate: "團隊作業效率", crewSize: "人員數量", equipment: "設備與燃料", travel: "交通", addOns: "附加服務", overhead: "人工間接成本", minimumService: "最低服務費", lawnService: "草坪服務", crewHours: "團隊小時", light: "輕度", standard: "一般", overgrown: "雜草過長" },
  de: { privacy: "Deine Sätze und Kundendaten bleiben in deinem Browser und werden nicht gespeichert.", directCost: "Direkte Kosten", breakdown: "Angebotsaufschlüsselung", adjustment: "Preisaufschlag", print: "Drucken / PDF speichern", view: "Angebot anzeigen", scope: "Umfang", costs: "Kosten", batch: "Los", material: "Material", machining: "Bearbeitung", property: "Grundstück", crew: "Team", scopeHours: "Projektstunden", hourlyRate: "Stundensatz", extraRevisions: "Zusätzliche Revisionen", hoursPerRevision: "Stunden je Revision", fixedCosts: "Fixkosten", rushPremium: "Eilzuschlag", freelanceService: "Freelance-Projekt", scopeDetail: "Projektstunden", revisionDetail: "Revisionsstunden", stockVolume: "Rohvolumen pro Teil", materialCost: "Materialkosten je Volumen", scrap: "Materialausschuss", programming: "Programmierstunden", setup: "Rüststunden", cycle: "Zykluszeit je Teil", inspection: "Prüfung je Teil", tooling: "Werkzeuge", finishing: "Nachbearbeitung", minimumOrder: "Mindestauftragswert", cncService: "CNC-Fertigungslose", parts: "Teile", mowableArea: "Mähfläche", grassCondition: "Graszustand", productionRate: "Teamleistung", crewSize: "Teamgröße", equipment: "Geräte & Kraftstoff", travel: "Anfahrt", addOns: "Zusatzleistungen", overhead: "Lohnnebenkosten", minimumService: "Mindestservicepreis", lawnService: "Rasenservice", crewHours: "Teamstd.", light: "Leicht", standard: "Standard", overgrown: "Überwachsen" },
  ja: { privacy: "料金と顧客情報はブラウザ内にのみ保持され、保存されません。", directCost: "直接原価", breakdown: "見積内訳", adjustment: "価格調整", print: "印刷／PDF 保存", view: "見積を見る", scope: "作業範囲", costs: "コスト", batch: "ロット", material: "材料", machining: "加工", property: "敷地", crew: "作業員", scopeHours: "作業時間", hourlyRate: "時間単価", extraRevisions: "追加修正回数", hoursPerRevision: "修正1回の時間", fixedCosts: "固定費", rushPremium: "特急料金", freelanceService: "フリーランス案件", scopeDetail: "案件時間", revisionDetail: "修正時間", stockVolume: "部品あたり素材体積", materialCost: "単位体積あたり材料費", scrap: "材料ロス", programming: "プログラミング時間", setup: "段取り時間", cycle: "部品あたりサイクル時間", inspection: "部品あたり検査", tooling: "工具", finishing: "仕上げ", minimumOrder: "最低注文額", cncService: "CNC 加工ロット", parts: "個", mowableArea: "芝刈り面積", grassCondition: "芝の状態", productionRate: "チーム作業率", crewSize: "作業員数", equipment: "機材・燃料", travel: "出張費", addOns: "追加サービス", overhead: "人件費間接費", minimumService: "最低サービス料金", lawnService: "芝生サービス", crewHours: "チーム時間", light: "軽度", standard: "標準", overgrown: "伸びすぎ" },
  es: { privacy: "Tus tarifas y datos de clientes se mantienen en tu navegador y no se almacenan.", directCost: "Costo directo", breakdown: "Desglose de cotización", adjustment: "Ajuste de precio", print: "Imprimir / guardar PDF", view: "Ver cotización", scope: "Alcance", costs: "Costos", batch: "Lote", material: "Material", machining: "Mecanizado", property: "Propiedad", crew: "Equipo", scopeHours: "Horas del proyecto", hourlyRate: "Tarifa por hora", extraRevisions: "Revisiones adicionales", hoursPerRevision: "Horas por revisión", fixedCosts: "Costos fijos", rushPremium: "Recargo urgente", freelanceService: "Proyecto freelance", scopeDetail: "horas de proyecto", revisionDetail: "horas de revisión", stockVolume: "Volumen de material por pieza", materialCost: "Costo de material por volumen", scrap: "Merma de material", programming: "Horas de programación", setup: "Horas de preparación", cycle: "Ciclo por pieza", inspection: "Inspección por pieza", tooling: "Herramental", finishing: "Acabado", minimumOrder: "Pedido mínimo", cncService: "Lote de mecanizado CNC", parts: "piezas", mowableArea: "Área cortable", grassCondition: "Estado del césped", productionRate: "Rendimiento del equipo", crewSize: "Tamaño del equipo", equipment: "Equipo y combustible", travel: "Desplazamiento", addOns: "Servicios extra", overhead: "Cargas laborales", minimumService: "Servicio mínimo", lawnService: "Servicio de césped", crewHours: "h de equipo", light: "Ligero", standard: "Estándar", overgrown: "Crecido" },
  fr: { privacy: "Vos tarifs et les informations client restent dans votre navigateur et ne sont pas enregistrés.", directCost: "Coût direct", breakdown: "Détail du devis", adjustment: "Ajustement de prix", print: "Imprimer / enregistrer en PDF", view: "Voir le devis", scope: "Périmètre", costs: "Coûts", batch: "Lot", material: "Matière", machining: "Usinage", property: "Propriété", crew: "Équipe", scopeHours: "Heures du projet", hourlyRate: "Taux horaire", extraRevisions: "Révisions supplémentaires", hoursPerRevision: "Heures par révision", fixedCosts: "Coûts fixes", rushPremium: "Supplément urgent", freelanceService: "Projet freelance", scopeDetail: "heures de projet", revisionDetail: "heures de révision", stockVolume: "Volume matière par pièce", materialCost: "Coût matière par volume", scrap: "Chute matière", programming: "Heures de programmation", setup: "Heures de réglage", cycle: "Cycle par pièce", inspection: "Contrôle par pièce", tooling: "Outillage", finishing: "Finition", minimumOrder: "Commande minimum", cncService: "Lot d'usinage CNC", parts: "pièces", mowableArea: "Surface à tondre", grassCondition: "État de l'herbe", productionRate: "Rendement de l'équipe", crewSize: "Taille de l'équipe", equipment: "Équipement et carburant", travel: "Déplacement", addOns: "Suppléments", overhead: "Charges de main-d'œuvre", minimumService: "Service minimum", lawnService: "Service d'entretien du gazon", crewHours: "h d'équipe", light: "Léger", standard: "Standard", overgrown: "Très haute" },
  "pt-br": { privacy: "Suas taxas e dados de clientes ficam no seu navegador e não são armazenados.", directCost: "Custo direto", breakdown: "Detalhamento do orçamento", adjustment: "Ajuste de preço", print: "Imprimir / salvar PDF", view: "Ver orçamento", scope: "Escopo", costs: "Custos", batch: "Lote", material: "Material", machining: "Usinagem", property: "Propriedade", crew: "Equipe", scopeHours: "Horas do projeto", hourlyRate: "Valor por hora", extraRevisions: "Revisões extras", hoursPerRevision: "Horas por revisão", fixedCosts: "Custos fixos", rushPremium: "Adicional de urgência", freelanceService: "Projeto freelancer", scopeDetail: "horas do projeto", revisionDetail: "horas de revisão", stockVolume: "Volume de material por peça", materialCost: "Custo de material por volume", scrap: "Perda de material", programming: "Horas de programação", setup: "Horas de preparação", cycle: "Ciclo por peça", inspection: "Inspeção por peça", tooling: "Ferramental", finishing: "Acabamento", minimumOrder: "Pedido mínimo", cncService: "Lote de usinagem CNC", parts: "peças", mowableArea: "Área para corte", grassCondition: "Condição da grama", productionRate: "Produtividade da equipe", crewSize: "Tamanho da equipe", equipment: "Equipamento e combustível", travel: "Deslocamento", addOns: "Adicionais", overhead: "Encargos trabalhistas", minimumService: "Serviço mínimo", lawnService: "Serviço de gramado", crewHours: "h de equipe", light: "Leve", standard: "Padrão", overgrown: "Crescida" },
  ko: { privacy: "요금과 고객 정보는 브라우저에만 남으며 저장되지 않습니다.", directCost: "직접 비용", breakdown: "견적 내역", adjustment: "가격 조정", print: "인쇄 / PDF 저장", view: "견적 보기", scope: "작업 범위", costs: "비용", batch: "배치", material: "재료", machining: "가공", property: "현장", crew: "작업팀", scopeHours: "프로젝트 시간", hourlyRate: "시간당 요금", extraRevisions: "추가 수정 횟수", hoursPerRevision: "수정당 시간", fixedCosts: "고정 비용", rushPremium: "긴급 할증", freelanceService: "프리랜서 프로젝트", scopeDetail: "프로젝트 시간", revisionDetail: "수정 시간", stockVolume: "부품당 소재 체적", materialCost: "체적당 소재비", scrap: "소재 손실", programming: "프로그래밍 시간", setup: "셋업 시간", cycle: "부품당 사이클 시간", inspection: "부품당 검사", tooling: "공구", finishing: "마감", minimumOrder: "최소 주문 금액", cncService: "CNC 가공 배치", parts: "개", mowableArea: "잔디 면적", grassCondition: "잔디 상태", productionRate: "작업팀 생산성", crewSize: "작업팀 규모", equipment: "장비 및 연료", travel: "이동", addOns: "추가 서비스", overhead: "인건비 간접비", minimumService: "최소 서비스 요금", lawnService: "잔디 관리 서비스", crewHours: "작업팀 시간", light: "가벼움", standard: "보통", overgrown: "무성함" },
};
const texts: Record<Locale, ToolText> = withSimplifiedChinese(baseTexts);

type WindowText = { scope: string; standardWindows: string; largeWindows: string; skylights: string; serviceType: string; exterior: string; insideOut: string; access: string; ground: string; secondFloor: string; highAccess: string; condition: string; standardCondition: string; heavy: string; addOns: string; screens: string; deepTracks: string; production: string; standardMinutes: string; largeMinutes: string; skylightMinutes: string; screenMinutes: string; trackMinutes: string; supplies: string; service: string; windows: string; crewHours: string };
const windowEnglish: WindowText = { scope: "Service scope", standardWindows: "Standard windows", largeWindows: "Large windows / patio doors", skylights: "Skylights", serviceType: "Service type", exterior: "Exterior only", insideOut: "Inside & exterior", access: "Access height", ground: "Ground floor", secondFloor: "Second floor", highAccess: "High access / ladder", condition: "Window condition", standardCondition: "Standard", heavy: "Heavy soil", addOns: "Add-ons", screens: "Screens", deepTracks: "Deep-clean tracks", production: "Crew production", standardMinutes: "Minutes per standard window", largeMinutes: "Minutes per large window", skylightMinutes: "Minutes per skylight", screenMinutes: "Minutes per screen", trackMinutes: "Minutes per deep track", supplies: "Supplies & equipment", service: "Window cleaning service", windows: "windows", crewHours: "crew h" };
const windowTexts: Record<Exclude<Locale, "en" | "zh-hans">, Partial<WindowText>> = {
  "zh-hant": { scope: "服務範圍", standardWindows: "標準窗", largeWindows: "大型窗／落地門", skylights: "天窗", serviceType: "清潔範圍", exterior: "僅外側", insideOut: "內外雙面", access: "作業高度", ground: "一樓", secondFloor: "二樓", highAccess: "高處／需梯子", condition: "窗戶狀況", standardCondition: "一般", heavy: "重度污漬", addOns: "附加服務", screens: "紗窗", deepTracks: "深度清潔軌道", production: "團隊產能", standardMinutes: "每扇標準窗分鐘數", largeMinutes: "每扇大型窗分鐘數", skylightMinutes: "每扇天窗分鐘數", screenMinutes: "每片紗窗分鐘數", trackMinutes: "每組深度軌道分鐘數", supplies: "耗材與設備", service: "窗戶清潔服務", windows: "扇窗", crewHours: "團隊小時" },
  de: { scope: "Leistungsumfang", standardWindows: "Standardfenster", largeWindows: "Große Fenster / Terrassentüren", skylights: "Dachfenster", serviceType: "Reinigungsart", exterior: "Nur außen", insideOut: "Innen und außen", access: "Zugangshöhe", ground: "Erdgeschoss", secondFloor: "Zweiter Stock", highAccess: "Hoher Zugang / Leiter", condition: "Fensterzustand", standardCondition: "Standard", heavy: "Starke Verschmutzung", addOns: "Zusatzleistungen", screens: "Fliegengitter", deepTracks: "Tiefe Schienenreinigung", production: "Teamleistung", supplies: "Material & Geräte", service: "Fensterreinigung", windows: "Fenster", crewHours: "Teamstd." },
  ja: { scope: "サービス範囲", standardWindows: "標準窓", largeWindows: "大型窓・パティオドア", skylights: "天窓", serviceType: "清掃範囲", exterior: "外側のみ", insideOut: "内外両面", access: "作業高さ", ground: "1階", secondFloor: "2階", highAccess: "高所・はしご", condition: "窓の状態", standardCondition: "標準", heavy: "頑固な汚れ", addOns: "追加作業", screens: "網戸", deepTracks: "レール深部清掃", production: "チーム作業時間", supplies: "消耗品・機材", service: "窓清掃サービス", windows: "窓", crewHours: "チーム時間" },
  es: { scope: "Alcance del servicio", standardWindows: "Ventanas estándar", largeWindows: "Ventanas grandes / puertas de patio", skylights: "Tragaluces", serviceType: "Tipo de servicio", exterior: "Solo exterior", insideOut: "Interior y exterior", access: "Altura de acceso", ground: "Planta baja", secondFloor: "Segundo piso", highAccess: "Acceso alto / escalera", condition: "Estado de las ventanas", standardCondition: "Estándar", heavy: "Suciedad intensa", addOns: "Servicios extra", screens: "Mosquiteros", deepTracks: "Rieles con limpieza profunda", production: "Producción del equipo", supplies: "Suministros y equipo", service: "Limpieza de ventanas", windows: "ventanas", crewHours: "h de equipo" },
  fr: { scope: "Périmètre du service", standardWindows: "Fenêtres standard", largeWindows: "Grandes baies / portes-fenêtres", skylights: "Velux", serviceType: "Type de service", exterior: "Extérieur seulement", insideOut: "Intérieur et extérieur", access: "Hauteur d'accès", ground: "Rez-de-chaussée", secondFloor: "Deuxième étage", highAccess: "Accès en hauteur / échelle", condition: "État des vitres", standardCondition: "Standard", heavy: "Très sale", addOns: "Suppléments", screens: "Moustiquaires", deepTracks: "Rails en profondeur", production: "Production de l'équipe", supplies: "Fournitures et matériel", service: "Nettoyage de vitres", windows: "vitres", crewHours: "h d'équipe" },
  "pt-br": { scope: "Escopo do serviço", standardWindows: "Janelas padrão", largeWindows: "Janelas grandes / portas de vidro", skylights: "Claraboias", serviceType: "Tipo de serviço", exterior: "Somente externo", insideOut: "Interno e externo", access: "Altura de acesso", ground: "Térreo", secondFloor: "Segundo andar", highAccess: "Acesso alto / escada", condition: "Condição das janelas", standardCondition: "Padrão", heavy: "Sujeira pesada", addOns: "Adicionais", screens: "Telas", deepTracks: "Trilhos com limpeza profunda", production: "Produção da equipe", supplies: "Materiais e equipamento", service: "Limpeza de janelas", windows: "janelas", crewHours: "h de equipe" },
  ko: { scope: "서비스 범위", standardWindows: "일반 창문", largeWindows: "대형 창문 / 파티오 문", skylights: "천창", serviceType: "서비스 유형", exterior: "외부만", insideOut: "내부 및 외부", access: "작업 높이", ground: "1층", secondFloor: "2층", highAccess: "고소 작업 / 사다리", condition: "창문 상태", standardCondition: "보통", heavy: "심한 오염", addOns: "추가 서비스", screens: "방충망", deepTracks: "창틀 레일 심층 청소", production: "작업팀 생산성", supplies: "소모품 및 장비", service: "창문 청소 서비스", windows: "창문", crewHours: "작업팀 시간" },
};
const localizedWindowTexts = withSimplifiedChinese(windowTexts);
function getWindowText(locale: Locale): WindowText { return { ...windowEnglish, ...(locale === "en" ? {} : localizedWindowTexts[locale]) }; }

function common(locale: Locale, dictionary: Dictionary) {
  const copy = getNewToolCopy(locale, "freelance");
  const text = texts[locale];
  return { title: copy.heading, privacyNote: text.privacy, targetQuote: dictionary.calculator.targetQuote, directCostLabel: text.directCost, profitLabel: dictionary.calculator.profit, marginLabel: dictionary.calculator.margin, breakdownTitle: text.breakdown, pricingAdjustmentLabel: text.adjustment, printLabel: text.print, exportLabel: dictionary.calculator.exportCsv, viewLabel: text.view };
}

function withPricingAdjustment(items: Array<{ label: string; amount: number }>, subtotal: number, directCost: number, label: string) {
  const adjustment = subtotal - directCost;
  return adjustment > .005 ? [...items, { label, amount: adjustment }] : items;
}

function freelanceConfig(locale: Locale, dictionary: Dictionary): SimpleQuoteConfig {
  const text = texts[locale];
  return { ...common(locale, dictionary), title: getNewToolCopy(locale, "freelance").heading, category: "freelance", fields: [
    { key: "hours", label: text.scopeHours, section: text.scope, suffix: "h", max: 10_000 }, { key: "hourlyRate", label: text.hourlyRate, section: text.scope, suffix: "currency" }, { key: "revisions", label: text.extraRevisions, section: text.scope, max: 100, step: 1 }, { key: "revisionHours", label: text.hoursPerRevision, section: text.scope, suffix: "h" },
    { key: "fixedCosts", label: text.fixedCosts, section: text.costs, suffix: "currency" }, { key: "rushPercent", label: text.rushPremium, section: text.costs, suffix: "%", max: 200 },
    { key: "targetMargin", label: dictionary.calculator.targetMargin, section: dictionary.calculator.pricing, suffix: "%", max: 95 }, { key: "minimumFee", label: dictionary.calculator.minimumFee, section: dictionary.calculator.pricing, suffix: "currency" }, { key: "taxRate", label: dictionary.calculator.tax, section: dictionary.calculator.pricing, suffix: "%", max: 100 },
  ], createDefaultInput: createDefaultFreelanceInput, convertCurrency: (input, from, to) => convertFreelanceCurrency(input as FreelanceInput, from, to), calculate: (input) => calculateFreelanceQuote(input as FreelanceInput), breakdown: (result) => { const value = result as ReturnType<typeof calculateFreelanceQuote>; return withPricingAdjustment([{ label: dictionary.calculator.labor, amount: value.laborCost }, { label: text.fixedCosts, amount: value.input.fixedCosts }], value.subtotal, value.directCost, text.adjustment); }, lines: (result, money) => { const value = result as ReturnType<typeof calculateFreelanceQuote>; return [{ id: "scope", description: text.freelanceService, detail: `${value.baseHours.toFixed(1)} h · ${text.scopeDetail}`, quantity: 1, unitPrice: money(value.subtotal), amount: money(value.subtotal) }]; }, notes: (input, result) => { const value = result as ReturnType<typeof calculateFreelanceQuote>; return [{ label: text.extraRevisions, value: `${value.input.revisions} · ${value.input.revisionHours} h` }]; } };
}

function cncDisplayInput(input: CncInput, unit: "cm3" | "in3") { return unit === "in3" ? { ...input, volumeUnit: "in3", stockVolumeCm3: input.stockVolumeCm3 / CM3_PER_IN3, materialCostPerCm3: input.materialCostPerCm3 * CM3_PER_IN3 } : { ...input, volumeUnit: "cm3" }; }
function cncCalculationInput(input: Input): CncInput { if (input.volumeUnit !== "in3") return input as CncInput; return { ...(input as CncInput), stockVolumeCm3: Number(input.stockVolumeCm3) * CM3_PER_IN3, materialCostPerCm3: Number(input.materialCostPerCm3) / CM3_PER_IN3 }; }

function cncConfig(locale: Locale, dictionary: Dictionary): SimpleQuoteConfig {
  const text = texts[locale];
  return { ...common(locale, dictionary), title: getNewToolCopy(locale, "cnc").heading, category: "cnc-machining", fields: [
    { key: "quantity", label: dictionary.calculator.quantity, section: text.batch, min: 1, max: 100_000, step: 1 }, { key: "volumeUnit", label: text.material, section: text.material, options: [{ value: "cm3", label: "cm³" }, { value: "in3", label: "in³" }] }, { key: "stockVolumeCm3", label: text.stockVolume, section: text.material, suffix: (input) => input.volumeUnit === "in3" ? "in³" : "cm³" }, { key: "materialCostPerCm3", label: text.materialCost, section: text.material, suffix: "currency" }, { key: "scrapPercent", label: text.scrap, section: text.material, suffix: "%", max: 100 },
    { key: "programmingHours", label: text.programming, section: text.machining, suffix: "h" }, { key: "setupHours", label: text.setup, section: text.machining, suffix: "h" }, { key: "cycleMinutes", label: text.cycle, section: text.machining, suffix: "min" }, { key: "inspectionMinutes", label: text.inspection, section: text.machining, suffix: "min" }, { key: "machineRate", label: dictionary.calculator.machineRate, section: text.machining, suffix: "currency" }, { key: "laborRate", label: dictionary.calculator.laborRate, section: text.machining, suffix: "currency" },
    { key: "toolingCost", label: text.tooling, section: dictionary.calculator.pricing, suffix: "currency" }, { key: "finishingCost", label: text.finishing, section: dictionary.calculator.pricing, suffix: "currency" }, { key: "targetMargin", label: dictionary.calculator.targetMargin, section: dictionary.calculator.pricing, suffix: "%", max: 95 }, { key: "minimumFee", label: text.minimumOrder, section: dictionary.calculator.pricing, suffix: "currency" }, { key: "taxRate", label: dictionary.calculator.tax, section: dictionary.calculator.pricing, suffix: "%", max: 100 },
  ], createDefaultInput: (currency) => cncDisplayInput(createDefaultCncInput(currency), "cm3"), convertCurrency: (input, from, to) => cncDisplayInput(convertCncCurrency(cncCalculationInput(input), from, to), input.volumeUnit === "in3" ? "in3" : "cm3"), calculate: (input) => calculateCncQuote(cncCalculationInput(input)), breakdown: (result) => { const value = result as ReturnType<typeof calculateCncQuote>; return withPricingAdjustment([{ label: text.material, amount: value.materialCost }, { label: dictionary.calculator.machine, amount: value.machineCost }, { label: dictionary.calculator.labor, amount: value.laborCost }, { label: `${text.tooling} & ${text.finishing}`, amount: value.input.toolingCost + value.input.finishingCost }], value.subtotal, value.directCost, text.adjustment); }, lines: (result, money) => { const value = result as ReturnType<typeof calculateCncQuote>; return [{ id: "batch", description: text.cncService, detail: `${value.input.quantity} ${text.parts} · ${money(value.subtotal / value.input.quantity)} / ${text.parts.slice(0, -1) || text.parts}`, quantity: 1, unitPrice: money(value.subtotal), amount: money(value.subtotal) }]; }, changeInput: (input, key, value) => { if (key !== "volumeUnit") return { ...input, [key]: value }; const next = value === "in3" ? "in3" : "cm3"; if (input.volumeUnit === next) return { ...input, volumeUnit: next }; const factor = next === "in3" ? 1 / CM3_PER_IN3 : CM3_PER_IN3; return { ...input, volumeUnit: next, stockVolumeCm3: Number(input.stockVolumeCm3) * factor, materialCostPerCm3: Number(input.materialCostPerCm3) / factor }; } };
}

function lawnDisplayInput(input: LawnCareInput, unit: "sqft" | "sqm") { return unit === "sqm" ? { ...input, areaUnit: "sqm", area: input.area / SQFT_PER_SQM, productionRate: input.productionRate / SQFT_PER_SQM } : { ...input, areaUnit: "sqft" }; }
function lawnCalculationInput(input: Input): LawnCareInput { if (input.areaUnit !== "sqm") return input as LawnCareInput; return { ...(input as LawnCareInput), area: Number(input.area) * SQFT_PER_SQM, productionRate: Number(input.productionRate) * SQFT_PER_SQM }; }

function lawnConfig(locale: Locale, dictionary: Dictionary): SimpleQuoteConfig {
  const text = texts[locale];
  const useMetric = locale !== "en";
  return { ...common(locale, dictionary), title: getNewToolCopy(locale, "lawn-care").heading, category: "lawn-care", fields: [
    { key: "areaUnit", label: text.property, section: text.property, options: [{ value: "sqft", label: "sq ft" }, { value: "sqm", label: "m²" }] }, { key: "area", label: text.mowableArea, section: text.property, suffix: (input) => input.areaUnit === "sqm" ? "m²" : "sq ft" }, { key: "condition", label: text.grassCondition, section: text.property, options: [{ value: "light", label: text.light }, { value: "standard", label: text.standard }, { value: "overgrown", label: text.overgrown }] },
    { key: "productionRate", label: text.productionRate, section: text.crew, suffix: (input) => input.areaUnit === "sqm" ? "m²/h" : "sq ft/h", min: .01 }, { key: "crewSize", label: text.crewSize, section: text.crew, min: 1, max: 100, step: 1 }, { key: "laborRate", label: dictionary.calculator.laborRate, section: text.crew, suffix: "currency" },
    { key: "equipmentCost", label: text.equipment, section: text.costs, suffix: "currency" }, { key: "travelCost", label: text.travel, section: text.costs, suffix: "currency" }, { key: "addOnAmount", label: text.addOns, section: text.costs, suffix: "currency" },
    { key: "overheadPercent", label: text.overhead, section: dictionary.calculator.pricing, suffix: "%", max: 100 }, { key: "targetMargin", label: dictionary.calculator.targetMargin, section: dictionary.calculator.pricing, suffix: "%", max: 95 }, { key: "minimumFee", label: text.minimumService, section: dictionary.calculator.pricing, suffix: "currency" }, { key: "taxRate", label: dictionary.calculator.tax, section: dictionary.calculator.pricing, suffix: "%", max: 100 },
  ], createDefaultInput: (currency) => lawnDisplayInput(createDefaultLawnCareInput(currency), useMetric ? "sqm" : "sqft"), convertCurrency: (input, from, to) => lawnDisplayInput(convertLawnCareCurrency(lawnCalculationInput(input), from, to), input.areaUnit === "sqm" ? "sqm" : "sqft"), calculate: (input) => calculateLawnCareQuote(lawnCalculationInput(input)), breakdown: (result) => { const value = result as ReturnType<typeof calculateLawnCareQuote>; return withPricingAdjustment([{ label: dictionary.calculator.labor, amount: value.laborCost }, { label: text.overhead, amount: value.overheadCost }, { label: text.equipment, amount: value.input.equipmentCost }, { label: `${text.travel} & ${text.addOns}`, amount: value.input.travelCost + value.input.addOnAmount }], value.subtotal, value.directCost, text.adjustment); }, lines: (result, money) => { const value = result as ReturnType<typeof calculateLawnCareQuote>; return [{ id: "service", description: text.lawnService, detail: `${value.crewHours.toFixed(1)} ${text.crewHours}`, quantity: 1, unitPrice: money(value.subtotal), amount: money(value.subtotal) }]; }, notes: (input) => [{ label: text.grassCondition, value: text[String(input.condition) as "light" | "standard" | "overgrown"] }], changeInput: (input, key, value) => { if (key !== "areaUnit") return { ...input, [key]: value }; const next = value === "sqm" ? "sqm" : "sqft"; if (input.areaUnit === next) return { ...input, areaUnit: next }; const factor = next === "sqm" ? 1 / SQFT_PER_SQM : SQFT_PER_SQM; return { ...input, areaUnit: next, area: Number(input.area) * factor, productionRate: Number(input.productionRate) * factor }; } };
}

function windowCleaningConfig(locale: Locale, dictionary: Dictionary): SimpleQuoteConfig {
  const text = texts[locale];
  const window = getWindowText(locale);
  return { ...common(locale, dictionary), title: getNewToolCopy(locale, "window-cleaning").heading, category: "window-cleaning", fields: [
    { key: "standardWindows", label: window.standardWindows, section: window.scope, max: 10_000, step: 1 }, { key: "largeWindows", label: window.largeWindows, section: window.scope, max: 10_000, step: 1 }, { key: "skylights", label: window.skylights, section: window.scope, max: 10_000, step: 1 }, { key: "serviceType", label: window.serviceType, section: window.scope, options: [{ value: "exterior", label: window.exterior }, { value: "inside-out", label: window.insideOut }] },
    { key: "access", label: window.access, section: text.property, options: [{ value: "ground", label: window.ground }, { value: "second-floor", label: window.secondFloor }, { value: "high-access", label: window.highAccess }] }, { key: "condition", label: window.condition, section: text.property, options: [{ value: "standard", label: window.standardCondition }, { value: "heavy", label: window.heavy }] }, { key: "screens", label: window.screens, section: window.addOns, max: 10_000, step: 1 }, { key: "deepTracks", label: window.deepTracks, section: window.addOns, max: 10_000, step: 1 },
    { key: "minutesPerStandard", label: `min / ${window.standardWindows}`, section: window.production, suffix: "min" }, { key: "minutesPerLarge", label: `min / ${window.largeWindows}`, section: window.production, suffix: "min" }, { key: "minutesPerSkylight", label: `min / ${window.skylights}`, section: window.production, suffix: "min" }, { key: "minutesPerScreen", label: `min / ${window.screens}`, section: window.production, suffix: "min" }, { key: "minutesPerTrack", label: `min / ${window.deepTracks}`, section: window.production, suffix: "min" }, { key: "secondFloorMultiplier", label: window.secondFloor, section: window.production, suffix: "×", min: 1, max: 5, step: .05 }, { key: "highAccessMultiplier", label: window.highAccess, section: window.production, suffix: "×", min: 1, max: 5, step: .05 }, { key: "heavySoilMultiplier", label: window.heavy, section: window.production, suffix: "×", min: 1, max: 5, step: .05 }, { key: "crewSize", label: text.crewSize, section: window.production, min: 1, max: 100, step: 1 }, { key: "laborRate", label: dictionary.calculator.laborRate, section: window.production, suffix: "currency" },
    { key: "suppliesCost", label: window.supplies, section: text.costs, suffix: "currency" }, { key: "travelCost", label: text.travel, section: text.costs, suffix: "currency" },
    { key: "overheadPercent", label: text.overhead, section: dictionary.calculator.pricing, suffix: "%", max: 100 }, { key: "targetMargin", label: dictionary.calculator.targetMargin, section: dictionary.calculator.pricing, suffix: "%", max: 95 }, { key: "minimumFee", label: text.minimumService, section: dictionary.calculator.pricing, suffix: "currency" }, { key: "taxRate", label: dictionary.calculator.tax, section: dictionary.calculator.pricing, suffix: "%", max: 100 },
  ], createDefaultInput: createDefaultWindowCleaningInput, convertCurrency: (input, from, to) => convertWindowCleaningCurrency(input as WindowCleaningInput, from, to), calculate: (input) => calculateWindowCleaningQuote(input as WindowCleaningInput), breakdown: (result) => { const value = result as ReturnType<typeof calculateWindowCleaningQuote>; return withPricingAdjustment([{ label: dictionary.calculator.labor, amount: value.laborCost }, { label: text.overhead, amount: value.overheadCost }, { label: window.supplies, amount: value.input.suppliesCost }, { label: text.travel, amount: value.input.travelCost }], value.subtotal, value.directCost, text.adjustment); }, lines: (result, money) => { const value = result as ReturnType<typeof calculateWindowCleaningQuote>; const count = value.input.standardWindows + value.input.largeWindows + value.input.skylights; return [{ id: "window-cleaning", description: window.service, detail: `${count} ${window.windows} · ${window[value.input.serviceType === "exterior" ? "exterior" : "insideOut"]}`, quantity: 1, unitPrice: money(value.subtotal), amount: money(value.subtotal) }]; }, notes: (input, result) => { const value = result as ReturnType<typeof calculateWindowCleaningQuote>; return [{ label: window.access, value: window[value.input.access === "ground" ? "ground" : value.input.access === "second-floor" ? "secondFloor" : "highAccess"] }, { label: window.condition, value: window[value.input.condition === "standard" ? "standardCondition" : "heavy"] }, { label: window.addOns, value: `${value.input.screens} ${window.screens} · ${value.input.deepTracks} ${window.deepTracks}` }, { label: window.production, value: `${value.crewHours.toFixed(1)} ${window.crewHours}` }]; } };
}

export function NewToolCalculator({ kind, locale, dictionary }: { kind: NewToolKind; locale: Locale; dictionary: Dictionary }) {
  const config = useMemo(() => kind === "freelance" ? freelanceConfig(locale, dictionary) : kind === "cnc" ? cncConfig(locale, dictionary) : kind === "lawn-care" ? lawnConfig(locale, dictionary) : windowCleaningConfig(locale, dictionary), [dictionary, kind, locale]);
  return <SimpleQuoteCalculator locale={locale} dictionary={dictionary} config={config} />;
}
