import type { Metadata } from "next";
import { GuideArticle, type GuideFaq, type GuideTocItem } from "@/components/guide-article";
import { buildMetadata } from "@/lib/seo";

const title = "How to Price Laser Cutting Jobs: Material, Machine Time & Margin";
const description = "Build a laser cutting quote from sheet material, nesting waste, machine time, setup, handling, finishing, and your target profit margin.";
const faq: GuideFaq[] = [
  { question: "Should laser cutting be priced by minute or cut length?", answer: "Use the measure that best explains your own cost. Cut time usually maps directly to machine occupancy, while cut length and pierce count help validate CAM output, consumables, and job difficulty." },
  { question: "How do I include sheet waste in a laser cutting quote?", answer: "Multiply the sheet area actually occupied by the material rate, then add a documented allowance for borders, test cuts, defects, and remnants that cannot be reused." },
  { question: "Should setup be charged per part?", answer: "Setup is normally a batch-level cost. Add setup labor once to the job, then divide the complete quote by quantity to review the unit price. Material, cutting, and handling may scale with quantity." },
  { question: "What should a laser cutting quote include?", answer: "State material, thickness, quantity, file revision, finishing, dimensional and tolerance assumptions, lead time, shipping, tax, quote validity, and any excluded bending, welding, or design work." },
];
const toc: GuideTocItem[] = [{ id: "job-data", label: "Collect job data" }, { id: "material", label: "Material and waste" }, { id: "machine", label: "Machine and labor" }, { id: "margin", label: "Apply margin" }, { id: "example", label: "Worked example" }, { id: "quote", label: "Write the quote" }];

export const metadata: Metadata = buildMetadata({ locale: "en", path: "guides/how-to-price-laser-cutting-jobs", title, description });

export default function Page() {
  return <GuideArticle title={title} description={description} published="2026-07-13" updated="2026-07-13" readingTime="9 min read" slug="how-to-price-laser-cutting-jobs" toolHref="/tools/laser-cutting-cost-calculator" toolLabel="Open laser cutting calculator" toc={toc} faq={faq}>
    <p className="guide-lead">A defensible laser cutting price does not come from cut minutes alone. Sheet utilization, nesting waste, setup, machine occupancy, handling, finishing, and normal production risk all change the real cost of a batch.</p>
    <div className="guide-callout"><strong>The core formula</strong><code>Quote = (material + machine + setup + handling + finishing + other costs) ÷ (1 − target margin)</code><p>Keep any discount above direct cost, then add tax only where applicable.</p></div>
    <h2 id="job-data">1. Collect traceable CAD/CAM job data</h2><p>Record material, thickness, quantity, occupied sheet area, cut time, cut length, pierce count, and the file revision being priced. The manual calculator does not need the CAD file itself; it uses statistics already available from CAM or nesting software.</p><p>Cut length and pierces do not need a universal price. They are valuable checks for dense contours, repeated starts, consumable wear, and a toolpath that differs from an earlier revision.</p>
    <h2 id="material">2. Calculate sheet material and usable waste</h2><p>Use the sheet area occupied by the nest, not only the finished part outline. Include borders, spacing rules, test cuts, defects, and remnants that cannot realistically return to inventory.</p><pre><code>Material cost = occupied area × material rate × (1 + waste rate) × quantity</code></pre><p>If a full sheet must be purchased for the job, decide whether the remainder has a credible future use. Do not quietly assume every offcut will recover its value.</p>
    <h2 id="machine">3. Separate machine time, setup, and hands-on work</h2><p>A machine rate can recover equipment depreciation, laser source, assist gas, electricity, optics, nozzles, maintenance, and billable capacity. Setup is generally incurred once per batch, while handling, deburring, cleaning, inspection, and packaging often increase with quantity.</p><p>Separating machine occupancy from active labor makes quantity changes easier to explain and prevents a short setup-heavy batch from being underpriced.</p>
    <h2 id="margin">4. Apply target margin correctly</h2><p>If direct cost is 100 and the target margin is 30%, the price is 100 ÷ 0.70 = 142.86. Adding 30% produces 130, which is only a 23.1% margin.</p><pre><code>Target price = direct cost ÷ (1 − target margin)</code></pre><p>Show discounts explicitly and recheck the resulting margin. A discount should not erase setup recovery or push the quote below direct cost.</p>
    <h2 id="example">5. Worked laser cutting quote example</h2><p>Assume sheet material and waste cost 48, machine time costs 32, setup labor is 18, handling and deburring are 22, and other job costs are 5. Direct cost is 125.</p><p>At a 35% target margin, the pre-tax quote is 192.31. Divide that result by quantity for the customer unit price, then add shipping and applicable tax.</p>
    <h2 id="quote">6. Turn the calculation into a customer-ready quote</h2><p>Describe the deliverable rather than exposing the internal cost breakdown. Include material, thickness, quantity, unit price, total, lead time, file revision, and finishing.</p><p>Document tolerance assumptions, material substitutions, design changes, excluded bending or welding, shipping, and quote validity. Recalculate when the design, quantity, or material changes.</p>
    <h2>Laser cutting quote checklist</h2><ul><li>Confirm material, thickness, quantity, and file revision.</li><li>Use occupied sheet area and a defensible waste rate.</li><li>Enter CAM cut time, length, and pierce count.</li><li>Separate machine, setup, handling, and finishing.</li><li>Add other job-specific costs.</li><li>Apply the target-margin formula correctly.</li><li>Check that discounts stay above direct cost.</li><li>Document scope, assumptions, lead time, and validity.</li></ul>
  </GuideArticle>;
}
