import type { Locale } from "./config";

export type CleaningCopy = {
  title: string; description: string; heading: string; intro: string;
  jobDetails: string; propertyType: string; house: string; apartment: string; condo: string; area: string; measurementUnit: string; squareFeet: string; squareMeters: string; bedrooms: string; bathrooms: string;
  cleaningType: string; standard: string; deep: string; move: string; frequency: string; oneTime: string; weekly: string; biweekly: string; monthly: string; difficulty: string; light: string; typical: string; heavy: string;
  laborEstimate: string; estimationMode: string; byArea: string; manual: string; productionRate: string; manualCleanerHours: string; crewSize: string; laborCostPerHour: string; overheadPerHour: string;
  costsAndAddOns: string; suppliesCost: string; travelCost: string; addOns: string; oven: string; fridge: string; windows: string; cabinets: string; laundry: string; petHair: string; quantity: string; addedMinutes: string; fixedPrice: string;
  pricing: string; targetMargin: string; minimumFee: string; frequencyDiscount: string; firstCleanSurcharge: string; taxRate: string; quoteDetails: string;
  targetQuote: string; jobCost: string; profit: string; margin: string; totalCleanerHours: string; onSiteDuration: string; labor: string; overhead: string; addOnCost: string; minimumAdjustment: string; serviceLine: string; selectedAddOns: string;
  methodologyTitle: string; methodologyBody: string; privacyNote: string; faqTitle: string; guideLink: string; faq: Array<{ question: string; answer: string }>;
};

const copies: Record<Locale, CleaningCopy> = {
  en: {
    title: "Cleaning Quote Generator & House Cleaning Estimate Calculator | zaps.work", description: "Estimate cleaner-hours, labor, overhead, supplies, travel, add-ons, minimum fees, and margin for a house cleaning quote.", heading: "Cleaning Quote Generator", intro: "Estimate total cleaner-hours, add real job costs, and create a customer-ready flat cleaning quote.",
    jobDetails: "Property & scope", propertyType: "Property type", house: "House", apartment: "Apartment", condo: "Condo", area: "Cleanable area", measurementUnit: "Area unit", squareFeet: "sq ft", squareMeters: "sq m", bedrooms: "Bedrooms", bathrooms: "Bathrooms",
    cleaningType: "Cleaning type", standard: "Standard cleaning", deep: "Deep cleaning", move: "Move-in / move-out", frequency: "Frequency", oneTime: "One-time", weekly: "Weekly", biweekly: "Every 2 weeks", monthly: "Every 4 weeks", difficulty: "Difficulty", light: "Light", typical: "Typical", heavy: "Heavy",
    laborEstimate: "Labor estimate", estimationMode: "Estimate mode", byArea: "Estimate by area", manual: "Enter cleaner-hours", productionRate: "Production rate", manualCleanerHours: "Manual cleaner-hours", crewSize: "Crew size", laborCostPerHour: "Loaded labor cost", overheadPerHour: "Overhead per cleaner-hour",
    costsAndAddOns: "Costs & add-ons", suppliesCost: "Supplies", travelCost: "Travel & parking", addOns: "Optional services", oven: "Inside oven", fridge: "Inside fridge", windows: "Interior windows", cabinets: "Inside cabinets", laundry: "Laundry", petHair: "Pet hair / heavy soil", quantity: "Quantity", addedMinutes: "Minutes each", fixedPrice: "Fixed customer price",
    pricing: "Pricing", targetMargin: "Target margin", minimumFee: "Minimum service fee", frequencyDiscount: "Frequency discount", firstCleanSurcharge: "First-clean surcharge", taxRate: "Tax", quoteDetails: "Quote details",
    targetQuote: "Suggested flat quote", jobCost: "Job cost", profit: "Profit", margin: "Margin", totalCleanerHours: "Cleaner-hours", onSiteDuration: "On-site duration", labor: "Labor", overhead: "Overhead", addOnCost: "Add-on cost", minimumAdjustment: "Minimum-fee adjustment", serviceLine: "Residential cleaning service", selectedAddOns: "Included add-ons",
    methodologyTitle: "How the cleaning estimate works", methodologyBody: "Estimate cleaner-hours from area, cleaning type, and difficulty—or enter hours manually. The quote then covers labor, overhead, supplies, travel, selected add-ons, target margin, recurring discount, minimum service fee, and tax.", privacyNote: "Customer names, addresses, and contact details stay in your browser and are not stored in our database.", faqTitle: "Cleaning quote questions", guideLink: "Read the complete house cleaning pricing guide →",
    faq: [{ question: "How do I estimate cleaner-hours?", answer: "Divide cleanable area by your measured production rate, then adjust for cleaning type and difficulty. Replace starter assumptions with results from completed jobs." }, { question: "What is a cleaner-hour?", answer: "One cleaner-hour is one person working for one hour. Two cleaners working for two hours equals four cleaner-hours and about two hours on site." }, { question: "Should house cleaning be hourly or flat rate?", answer: "Estimate internally with cleaner-hours and costs, then present a flat quote when the scope is clear. Use explicit assumptions and exclusions when condition or access is uncertain." }, { question: "How should recurring discounts work?", answer: "Use a discount only when repeat visits genuinely reduce setup, sales, or cleaning time. Recheck the actual margin after applying it." }],
  },
  "zh-hant": {
    title: "清潔服務報價生成器與居家清潔估價計算器 | zaps.work", description: "估算清潔人工時、人工、營運分攤、耗材、交通、附加服務、最低收費與毛利。", heading: "清潔服務報價生成器", intro: "估算總清潔人工時，加入真實工作成本，產生可交付客戶的固定報價。",
    jobDetails: "房屋與工作範圍", propertyType: "房屋類型", house: "獨立屋", apartment: "公寓", condo: "集合住宅", area: "清潔面積", measurementUnit: "面積單位", squareFeet: "平方英尺", squareMeters: "平方公尺", bedrooms: "臥室", bathrooms: "衛浴",
    cleaningType: "清潔類型", standard: "標準清潔", deep: "深度清潔", move: "搬入／搬出清潔", frequency: "服務頻率", oneTime: "單次", weekly: "每週", biweekly: "每兩週", monthly: "每四週", difficulty: "難度", light: "輕度", typical: "一般", heavy: "重度",
    laborEstimate: "人工估算", estimationMode: "估算方式", byArea: "依面積估算", manual: "手動輸入人工時", productionRate: "生產率", manualCleanerHours: "手動清潔人工時", crewSize: "團隊人數", laborCostPerHour: "每人工時完整成本", overheadPerHour: "每人工時營運分攤",
    costsAndAddOns: "成本與附加服務", suppliesCost: "耗材", travelCost: "交通與停車", addOns: "可選服務", oven: "烤箱內部", fridge: "冰箱內部", windows: "室內窗戶", cabinets: "櫥櫃內部", laundry: "洗衣", petHair: "寵物毛髮／重度髒污", quantity: "數量", addedMinutes: "每項分鐘", fixedPrice: "固定客戶價格",
    pricing: "定價", targetMargin: "目標毛利率", minimumFee: "最低服務費", frequencyDiscount: "週期折扣", firstCleanSurcharge: "首次清潔附加費", taxRate: "稅額", quoteDetails: "報價資料",
    targetQuote: "建議固定報價", jobCost: "工作成本", profit: "利潤", margin: "毛利率", totalCleanerHours: "總清潔人工時", onSiteDuration: "現場時長", labor: "人工", overhead: "營運分攤", addOnCost: "附加服務成本", minimumAdjustment: "最低收費調整", serviceLine: "住宅清潔服務", selectedAddOns: "包含附加服務",
    methodologyTitle: "清潔估價如何計算", methodologyBody: "依面積、清潔類型與難度估算清潔人工時，或手動輸入工時，再加入人工、營運、耗材、交通、附加服務、目標毛利、週期折扣、最低收費與稅額。", privacyNote: "客戶姓名、地址與聯絡資料只留在瀏覽器，不會儲存在資料庫。", faqTitle: "清潔報價常見問題", guideLink: "閱讀完整居家清潔定價指南 →",
    faq: [{ question: "如何估算清潔人工時？", answer: "用清潔面積除以自己的生產率，再依清潔類型與難度調整。應使用已完成工作的記錄替換起始假設。" }, { question: "什麼是清潔人工時？", answer: "一位清潔人員工作一小時是一個人工時；兩人工作兩小時等於四個人工時，現場時長約兩小時。" }, { question: "應按小時還是固定價格收費？", answer: "內部先用人工時與成本估算，工作範圍清楚時再向客戶提供固定報價。" }, { question: "週期折扣如何設定？", answer: "只有重複服務確實減少設定、銷售或清潔時間時才折扣，并重新檢查實際毛利。" }],
  },
  de: {
    title: "Reinigungsangebot erstellen & Hausreinigung kalkulieren | zaps.work", description: "Reinigerstunden, Arbeit, Gemeinkosten, Material, Anfahrt, Zusatzleistungen, Mindestpreis und Marge kalkulieren.", heading: "Angebotsgenerator für Reinigung", intro: "Reinigerstunden schätzen, echte Auftragskosten ergänzen und ein Festpreisangebot erstellen.",
    jobDetails: "Objekt & Umfang", propertyType: "Objekttyp", house: "Haus", apartment: "Wohnung", condo: "Eigentumswohnung", area: "Reinigungsfläche", measurementUnit: "Flächeneinheit", squareFeet: "sq ft", squareMeters: "m²", bedrooms: "Schlafzimmer", bathrooms: "Bäder", cleaningType: "Reinigungsart", standard: "Standardreinigung", deep: "Grundreinigung", move: "Ein-/Auszugsreinigung", frequency: "Häufigkeit", oneTime: "Einmalig", weekly: "Wöchentlich", biweekly: "Alle 2 Wochen", monthly: "Alle 4 Wochen", difficulty: "Schwierigkeit", light: "Leicht", typical: "Normal", heavy: "Stark",
    laborEstimate: "Arbeitsaufwand", estimationMode: "Schätzmethode", byArea: "Nach Fläche", manual: "Reinigerstunden eingeben", productionRate: "Leistung", manualCleanerHours: "Reinigerstunden", crewSize: "Teamgröße", laborCostPerHour: "Vollkosten Arbeit", overheadPerHour: "Gemeinkosten je Reinigerstunde",
    costsAndAddOns: "Kosten & Zusatzleistungen", suppliesCost: "Material", travelCost: "Anfahrt & Parken", addOns: "Zusatzleistungen", oven: "Backofen innen", fridge: "Kühlschrank innen", windows: "Fenster innen", cabinets: "Schränke innen", laundry: "Wäsche", petHair: "Tierhaare / starke Verschmutzung", quantity: "Menge", addedMinutes: "Minuten je Einheit", fixedPrice: "Fester Kundenpreis",
    pricing: "Preisgestaltung", targetMargin: "Zielmarge", minimumFee: "Mindestpreis", frequencyDiscount: "Intervallrabatt", firstCleanSurcharge: "Erstreinigungszuschlag", taxRate: "Steuer", quoteDetails: "Angebotsdaten", targetQuote: "Empfohlenes Festangebot", jobCost: "Auftragskosten", profit: "Gewinn", margin: "Marge", totalCleanerHours: "Reinigerstunden", onSiteDuration: "Zeit vor Ort", labor: "Arbeit", overhead: "Gemeinkosten", addOnCost: "Zusatzkosten", minimumAdjustment: "Mindestpreis-Anpassung", serviceLine: "Haushaltsreinigung", selectedAddOns: "Enthaltene Zusätze",
    methodologyTitle: "So funktioniert die Kalkulation", methodologyBody: "Schätze Reinigerstunden aus Fläche, Reinigungsart und Schwierigkeit oder gib Stunden manuell ein. Danach werden Arbeit, Gemeinkosten, Material, Anfahrt, Zusätze, Marge, Rabatt, Mindestpreis und Steuer berücksichtigt.", privacyNote: "Kundennamen, Adressen und Kontaktdaten bleiben im Browser.", faqTitle: "Fragen zur Reinigungskalkulation", guideLink: "Vollständigen Preisleitfaden lesen →", faq: [{ question: "Wie schätze ich Reinigerstunden?", answer: "Teile die Fläche durch deine gemessene Leistung und passe Reinigungsart und Schwierigkeit an." }, { question: "Was ist eine Reinigerstunde?", answer: "Eine Person für eine Stunde entspricht einer Reinigerstunde. Zwei Personen für zwei Stunden ergeben vier Reinigerstunden." }, { question: "Stunden- oder Festpreis?", answer: "Kalkuliere intern mit Stunden und Kosten und biete bei klarem Umfang einen Festpreis an." }, { question: "Wie funktionieren Intervallrabatte?", answer: "Rabattiere nur, wenn Wiederholungen tatsächlich Zeit oder Kosten sparen, und prüfe danach die Marge." }],
  },
  ja: {
    title: "清掃見積もり作成・ハウスクリーニング料金計算 | zaps.work", description: "清掃人時、人件費、間接費、用品、移動、追加サービス、最低料金と利益率を計算します。", heading: "清掃見積もり作成ツール", intro: "総清掃人時と実際の費用を計算し、顧客向けの固定価格見積もりを作成します。",
    jobDetails: "物件と範囲", propertyType: "物件タイプ", house: "一戸建て", apartment: "アパート", condo: "マンション", area: "清掃面積", measurementUnit: "面積単位", squareFeet: "平方フィート", squareMeters: "平方メートル", bedrooms: "寝室", bathrooms: "浴室", cleaningType: "清掃タイプ", standard: "標準清掃", deep: "徹底清掃", move: "入退去清掃", frequency: "頻度", oneTime: "1回", weekly: "毎週", biweekly: "2週間ごと", monthly: "4週間ごと", difficulty: "難易度", light: "軽い", typical: "標準", heavy: "重い",
    laborEstimate: "作業時間", estimationMode: "計算方法", byArea: "面積から計算", manual: "清掃人時を入力", productionRate: "作業効率", manualCleanerHours: "手動清掃人時", crewSize: "人数", laborCostPerHour: "人時あたり人件費", overheadPerHour: "人時あたり間接費",
    costsAndAddOns: "費用と追加サービス", suppliesCost: "清掃用品", travelCost: "移動・駐車", addOns: "追加サービス", oven: "オーブン内部", fridge: "冷蔵庫内部", windows: "室内窓", cabinets: "収納内部", laundry: "洗濯", petHair: "ペット毛・強い汚れ", quantity: "数量", addedMinutes: "1件の追加分", fixedPrice: "固定顧客価格",
    pricing: "料金設定", targetMargin: "目標利益率", minimumFee: "最低料金", frequencyDiscount: "定期割引", firstCleanSurcharge: "初回清掃加算", taxRate: "税", quoteDetails: "見積書情報", targetQuote: "推奨固定見積額", jobCost: "作業原価", profit: "利益", margin: "利益率", totalCleanerHours: "総清掃人時", onSiteDuration: "現場時間", labor: "人件費", overhead: "間接費", addOnCost: "追加作業原価", minimumAdjustment: "最低料金調整", serviceLine: "住宅清掃サービス", selectedAddOns: "含まれる追加サービス",
    methodologyTitle: "清掃見積もりの計算方法", methodologyBody: "面積、清掃タイプ、難易度から清掃人時を推定するか手動入力し、人件費、間接費、用品、移動、追加サービス、利益率、定期割引、最低料金、税を計算します。", privacyNote: "顧客名、住所、連絡先はブラウザ内に留まり、データベースには保存されません。", faqTitle: "清掃見積もりの質問", guideLink: "ハウスクリーニング料金ガイドを読む →", faq: [{ question: "清掃人時はどう見積もりますか？", answer: "清掃面積を実績の作業効率で割り、清掃タイプと難易度で調整します。" }, { question: "清掃人時とは？", answer: "1人が1時間働くと1人時です。2人が2時間なら4人時、現場時間は約2時間です。" }, { question: "時間制と固定料金のどちら？", answer: "内部では人時と原価で計算し、範囲が明確なら顧客には固定価格を提示します。" }, { question: "定期割引はどう設定しますか？", answer: "再訪で準備や清掃時間が実際に減る場合だけ割引し、適用後の利益率を確認します。" }],
  },
  es: {
    title: "Generador de presupuestos y calculadora de limpieza | zaps.work", description: "Calcula horas-persona, trabajo, gastos, suministros, viaje, extras, mínimo y margen para limpieza doméstica.", heading: "Generador de presupuestos de limpieza", intro: "Estima horas-persona, añade costes reales y crea un presupuesto cerrado para el cliente.",
    jobDetails: "Propiedad y alcance", propertyType: "Tipo de propiedad", house: "Casa", apartment: "Apartamento", condo: "Condominio", area: "Área de limpieza", measurementUnit: "Unidad", squareFeet: "pies²", squareMeters: "m²", bedrooms: "Dormitorios", bathrooms: "Baños", cleaningType: "Tipo de limpieza", standard: "Limpieza estándar", deep: "Limpieza profunda", move: "Entrada / salida", frequency: "Frecuencia", oneTime: "Una vez", weekly: "Semanal", biweekly: "Cada 2 semanas", monthly: "Cada 4 semanas", difficulty: "Dificultad", light: "Ligera", typical: "Normal", heavy: "Alta",
    laborEstimate: "Estimación de trabajo", estimationMode: "Método", byArea: "Por área", manual: "Introducir horas-persona", productionRate: "Productividad", manualCleanerHours: "Horas-persona", crewSize: "Equipo", laborCostPerHour: "Coste laboral por hora", overheadPerHour: "Gastos por hora-persona",
    costsAndAddOns: "Costes y extras", suppliesCost: "Suministros", travelCost: "Viaje y aparcamiento", addOns: "Servicios extra", oven: "Interior del horno", fridge: "Interior del frigorífico", windows: "Ventanas interiores", cabinets: "Interior de armarios", laundry: "Lavandería", petHair: "Pelo de mascota / suciedad", quantity: "Cantidad", addedMinutes: "Minutos cada uno", fixedPrice: "Precio fijo al cliente",
    pricing: "Precios", targetMargin: "Margen objetivo", minimumFee: "Servicio mínimo", frequencyDiscount: "Descuento recurrente", firstCleanSurcharge: "Recargo primera limpieza", taxRate: "Impuesto", quoteDetails: "Datos del presupuesto", targetQuote: "Presupuesto fijo sugerido", jobCost: "Coste del trabajo", profit: "Beneficio", margin: "Margen", totalCleanerHours: "Horas-persona", onSiteDuration: "Tiempo en sitio", labor: "Trabajo", overhead: "Gastos", addOnCost: "Coste de extras", minimumAdjustment: "Ajuste mínimo", serviceLine: "Servicio de limpieza doméstica", selectedAddOns: "Extras incluidos",
    methodologyTitle: "Cómo funciona la estimación", methodologyBody: "Estima horas-persona por área, tipo y dificultad o introdúcelas manualmente; después suma trabajo, gastos, suministros, viaje, extras, margen, descuento, mínimo e impuestos.", privacyNote: "Nombres, direcciones y contactos permanecen en el navegador.", faqTitle: "Preguntas sobre presupuestos", guideLink: "Leer la guía completa de precios →", faq: [{ question: "¿Cómo estimo horas-persona?", answer: "Divide el área por tu productividad medida y ajusta el tipo y la dificultad." }, { question: "¿Qué es una hora-persona?", answer: "Una persona durante una hora es una hora-persona. Dos personas durante dos horas son cuatro horas-persona." }, { question: "¿Cobrar por hora o precio fijo?", answer: "Calcula internamente con horas y costes y presenta precio fijo cuando el alcance sea claro." }, { question: "¿Cómo aplicar descuentos recurrentes?", answer: "Descuenta solo si las visitas repetidas reducen tiempo o costes y revisa el margen final." }],
  },
  fr: {
    title: "Générateur de devis et calculateur de ménage | zaps.work", description: "Estimez heures-personnes, travail, frais, fournitures, trajet, options, minimum et marge pour un ménage.", heading: "Générateur de devis de nettoyage", intro: "Estimez les heures-personnes, ajoutez les coûts réels et créez un devis forfaitaire client.",
    jobDetails: "Logement et périmètre", propertyType: "Type de logement", house: "Maison", apartment: "Appartement", condo: "Copropriété", area: "Surface à nettoyer", measurementUnit: "Unité", squareFeet: "pi²", squareMeters: "m²", bedrooms: "Chambres", bathrooms: "Salles de bain", cleaningType: "Type de nettoyage", standard: "Nettoyage standard", deep: "Grand nettoyage", move: "Entrée / sortie", frequency: "Fréquence", oneTime: "Ponctuel", weekly: "Hebdomadaire", biweekly: "Toutes les 2 semaines", monthly: "Toutes les 4 semaines", difficulty: "Difficulté", light: "Légère", typical: "Normale", heavy: "Élevée",
    laborEstimate: "Temps de travail", estimationMode: "Méthode", byArea: "Par surface", manual: "Saisir les heures-personnes", productionRate: "Rendement", manualCleanerHours: "Heures-personnes", crewSize: "Équipe", laborCostPerHour: "Coût horaire chargé", overheadPerHour: "Frais par heure-personne",
    costsAndAddOns: "Coûts et options", suppliesCost: "Fournitures", travelCost: "Trajet et parking", addOns: "Services en option", oven: "Intérieur du four", fridge: "Intérieur du réfrigérateur", windows: "Vitres intérieures", cabinets: "Intérieur des placards", laundry: "Linge", petHair: "Poils / saleté forte", quantity: "Quantité", addedMinutes: "Minutes chacun", fixedPrice: "Prix client fixe",
    pricing: "Tarification", targetMargin: "Marge cible", minimumFee: "Minimum d’intervention", frequencyDiscount: "Remise récurrente", firstCleanSurcharge: "Supplément première visite", taxRate: "Taxe", quoteDetails: "Données du devis", targetQuote: "Forfait conseillé", jobCost: "Coût du travail", profit: "Bénéfice", margin: "Marge", totalCleanerHours: "Heures-personnes", onSiteDuration: "Durée sur place", labor: "Travail", overhead: "Frais", addOnCost: "Coût des options", minimumAdjustment: "Ajustement minimum", serviceLine: "Service de ménage résidentiel", selectedAddOns: "Options incluses",
    methodologyTitle: "Comment fonctionne l’estimation", methodologyBody: "Estimez les heures-personnes par surface, type et difficulté ou saisissez-les, puis ajoutez travail, frais, fournitures, trajet, options, marge, remise, minimum et taxes.", privacyNote: "Noms, adresses et coordonnées restent dans le navigateur.", faqTitle: "Questions sur les devis", guideLink: "Lire le guide complet de tarification →", faq: [{ question: "Comment estimer les heures-personnes ?", answer: "Divisez la surface par votre rendement mesuré puis ajustez le type et la difficulté." }, { question: "Qu’est-ce qu’une heure-personne ?", answer: "Une personne pendant une heure égale une heure-personne. Deux personnes pendant deux heures en font quatre." }, { question: "Facturer à l’heure ou au forfait ?", answer: "Calculez en interne avec temps et coûts, puis proposez un forfait lorsque le périmètre est clair." }, { question: "Comment appliquer une remise récurrente ?", answer: "Remisez uniquement si les visites réduisent réellement temps ou coûts et vérifiez la marge finale." }],
  },
  "pt-br": {
    title: "Gerador de orçamento e calculadora de limpeza residencial | zaps.work", description: "Calcule horas-pessoa, trabalho, despesas, materiais, viagem, adicionais, mínimo e margem para limpeza.", heading: "Gerador de orçamentos de limpeza", intro: "Estime horas-pessoa, some custos reais e crie um orçamento fechado para o cliente.",
    jobDetails: "Imóvel e escopo", propertyType: "Tipo de imóvel", house: "Casa", apartment: "Apartamento", condo: "Condomínio", area: "Área de limpeza", measurementUnit: "Unidade", squareFeet: "pés²", squareMeters: "m²", bedrooms: "Quartos", bathrooms: "Banheiros", cleaningType: "Tipo de limpeza", standard: "Limpeza padrão", deep: "Limpeza pesada", move: "Mudança", frequency: "Frequência", oneTime: "Uma vez", weekly: "Semanal", biweekly: "A cada 2 semanas", monthly: "A cada 4 semanas", difficulty: "Dificuldade", light: "Leve", typical: "Normal", heavy: "Alta",
    laborEstimate: "Estimativa de trabalho", estimationMode: "Método", byArea: "Por área", manual: "Informar horas-pessoa", productionRate: "Produtividade", manualCleanerHours: "Horas-pessoa", crewSize: "Equipe", laborCostPerHour: "Custo de trabalho por hora", overheadPerHour: "Despesas por hora-pessoa",
    costsAndAddOns: "Custos e adicionais", suppliesCost: "Materiais", travelCost: "Viagem e estacionamento", addOns: "Serviços adicionais", oven: "Interior do forno", fridge: "Interior da geladeira", windows: "Janelas internas", cabinets: "Interior dos armários", laundry: "Lavanderia", petHair: "Pelos / sujeira pesada", quantity: "Quantidade", addedMinutes: "Minutos cada", fixedPrice: "Preço fixo ao cliente",
    pricing: "Preço", targetMargin: "Margem desejada", minimumFee: "Valor mínimo", frequencyDiscount: "Desconto recorrente", firstCleanSurcharge: "Adicional primeira limpeza", taxRate: "Imposto", quoteDetails: "Dados do orçamento", targetQuote: "Orçamento fixo sugerido", jobCost: "Custo do serviço", profit: "Lucro", margin: "Margem", totalCleanerHours: "Horas-pessoa", onSiteDuration: "Tempo no local", labor: "Trabalho", overhead: "Despesas", addOnCost: "Custo dos adicionais", minimumAdjustment: "Ajuste mínimo", serviceLine: "Serviço de limpeza residencial", selectedAddOns: "Adicionais incluídos",
    methodologyTitle: "Como funciona a estimativa", methodologyBody: "Estime horas-pessoa por área, tipo e dificuldade ou informe manualmente; depois some trabalho, despesas, materiais, viagem, adicionais, margem, desconto, mínimo e impostos.", privacyNote: "Nomes, endereços e contatos ficam no navegador.", faqTitle: "Dúvidas sobre orçamento", guideLink: "Ler o guia completo de preços →", faq: [{ question: "Como estimar horas-pessoa?", answer: "Divida a área pela produtividade medida e ajuste tipo e dificuldade." }, { question: "O que é hora-pessoa?", answer: "Uma pessoa por uma hora é uma hora-pessoa. Duas pessoas por duas horas são quatro horas-pessoa." }, { question: "Cobrar por hora ou valor fechado?", answer: "Calcule internamente com horas e custos e apresente valor fechado quando o escopo estiver claro." }, { question: "Como aplicar desconto recorrente?", answer: "Dê desconto apenas quando visitas repetidas reduzirem tempo ou custo e confira a margem final." }],
  },
  ko: {
    title: "청소 견적 생성기 및 가정 청소 비용 계산기 | zaps.work", description: "청소 인시, 인건비, 간접비, 용품, 이동, 추가 서비스, 최소 요금과 마진을 계산합니다.", heading: "청소 견적 생성기", intro: "총 청소 인시와 실제 비용을 계산해 고객용 고정 견적을 만드세요.",
    jobDetails: "공간과 범위", propertyType: "공간 유형", house: "주택", apartment: "아파트", condo: "공동주택", area: "청소 면적", measurementUnit: "면적 단위", squareFeet: "제곱피트", squareMeters: "제곱미터", bedrooms: "침실", bathrooms: "욕실", cleaningType: "청소 유형", standard: "일반 청소", deep: "대청소", move: "입주 / 퇴거 청소", frequency: "주기", oneTime: "1회", weekly: "매주", biweekly: "2주마다", monthly: "4주마다", difficulty: "난이도", light: "가벼움", typical: "보통", heavy: "심함",
    laborEstimate: "작업 시간", estimationMode: "계산 방식", byArea: "면적으로 계산", manual: "청소 인시 입력", productionRate: "작업 효율", manualCleanerHours: "수동 청소 인시", crewSize: "인원", laborCostPerHour: "인시당 인건비", overheadPerHour: "인시당 간접비",
    costsAndAddOns: "비용과 추가 서비스", suppliesCost: "청소 용품", travelCost: "이동 및 주차", addOns: "추가 서비스", oven: "오븐 내부", fridge: "냉장고 내부", windows: "실내 창문", cabinets: "수납장 내부", laundry: "세탁", petHair: "반려동물 털 / 심한 오염", quantity: "수량", addedMinutes: "개당 분", fixedPrice: "고객 고정 가격",
    pricing: "가격", targetMargin: "목표 마진", minimumFee: "최소 서비스 요금", frequencyDiscount: "정기 할인", firstCleanSurcharge: "첫 청소 추가 요금", taxRate: "세금", quoteDetails: "견적 정보", targetQuote: "권장 고정 견적", jobCost: "작업 원가", profit: "이익", margin: "마진", totalCleanerHours: "총 청소 인시", onSiteDuration: "현장 시간", labor: "인건비", overhead: "간접비", addOnCost: "추가 작업 원가", minimumAdjustment: "최소 요금 조정", serviceLine: "주거 청소 서비스", selectedAddOns: "포함 추가 서비스",
    methodologyTitle: "청소 견적 계산 방식", methodologyBody: "면적, 청소 유형과 난이도로 청소 인시를 계산하거나 직접 입력한 뒤 인건비, 간접비, 용품, 이동, 추가 서비스, 마진, 할인, 최소 요금과 세금을 반영합니다.", privacyNote: "고객 이름, 주소와 연락처는 브라우저에만 남습니다.", faqTitle: "청소 견적 질문", guideLink: "가정 청소 가격 가이드 읽기 →", faq: [{ question: "청소 인시는 어떻게 계산하나요?", answer: "면적을 실제 작업 효율로 나누고 청소 유형과 난이도로 조정합니다." }, { question: "청소 인시란 무엇인가요?", answer: "한 사람이 한 시간 일하면 1인시입니다. 두 사람이 두 시간 일하면 4인시입니다." }, { question: "시간제와 고정 가격 중 무엇이 좋나요?", answer: "내부에서는 인시와 비용으로 계산하고 범위가 명확하면 고객에게 고정 가격을 제시합니다." }, { question: "정기 할인은 어떻게 적용하나요?", answer: "재방문이 실제 시간이나 비용을 줄이는 경우에만 할인하고 최종 마진을 확인하세요." }],
  },
};

export function getCleaningCopy(locale: Locale) { return copies[locale]; }
