import type { Locale } from "./config";

export type HousePaintingCopy = {
  title: string; description: string; heading: string; intro: string; jobDetails: string; paintPlan: string; labor: string; pricing: string;
  projectType: string; interior: string; exterior: string; area: string; squareFeet: string; squareMeters: string; coats: string; rooms: string; condition: string; good: string; standard: string; repairHeavy: string;
  coveragePerContainer: string; paintPrice: string; wastePercent: string; sundriesCost: string; productionRate: string; laborRate: string; crewSize: string; prepCost: string; travelCost: string; overheadPercent: string; targetMargin: string; minimumFee: string; taxRate: string;
  targetQuote: string; directCost: string; profit: string; paint: string; laborCost: string; overhead: string; onSiteHours: string; paintContainers: string; quoteBreakdown: string; printOrSave: string; exportCsv: string; viewQuote: string; privacyNote: string; methodologyTitle: string; methodologyBody: string; faqTitle: string; faq: Array<{ question: string; answer: string }>;
};

const en: HousePaintingCopy = {
  title: "House Painting Quote Calculator | zaps.work", description: "Estimate paint, labor, overhead, margin, and a customer-ready house painting quote.", heading: "House Painting Quote Calculator", intro: "Turn paint coverage, labor production, site condition, and your target margin into a clear house painting quote.",
  jobDetails: "Job details", paintPlan: "Paint & materials", labor: "Labor plan", pricing: "Pricing", projectType: "Project type", interior: "Interior", exterior: "Exterior", area: "Paintable area", squareFeet: "sq ft", squareMeters: "sq m", coats: "Coats", rooms: "Rooms", condition: "Surface condition", good: "Good", standard: "Standard", repairHeavy: "Repair-heavy",
  coveragePerContainer: "Coverage per container", paintPrice: "Paint price per container", wastePercent: "Paint waste", sundriesCost: "Sundries & protection", productionRate: "Production rate per painter-hour", laborRate: "Loaded labor rate", crewSize: "Crew size", prepCost: "Extra prep cost", travelCost: "Travel", overheadPercent: "Labor overhead", targetMargin: "Target margin", minimumFee: "Minimum job fee", taxRate: "Tax", targetQuote: "Target quote", directCost: "Direct cost", profit: "Profit", paint: "Paint", laborCost: "Labor", overhead: "Overhead", onSiteHours: "On-site hours", paintContainers: "Paint containers", quoteBreakdown: "Quote breakdown", printOrSave: "Print / save PDF", exportCsv: "Export CSV", viewQuote: "View quote", privacyNote: "Your rates and customer details stay in your browser. This calculator does not store them.", methodologyTitle: "A quote built from your own production", methodologyBody: "The estimate uses paintable area, coats, waste, container coverage, room setup allowance, production rate, surface condition, labor, overhead, fixed costs, minimum fee, target margin, and tax. It is not a market-price recommendation.", faqTitle: "House painting quote questions", faq: [
    { question: "How does the calculator estimate paint?", answer: "It divides the paintable area multiplied by coats and waste by the coverage per container, then rounds up to whole containers." },
    { question: "Why is production rate entered per painter-hour?", answer: "This makes labor cost traceable to your own crew. The tool adds a small room setup allowance and adjusts time for project type and surface condition." },
    { question: "Does the result use a market average price?", answer: "No. It calculates from the rates and costs you enter, then applies your target margin and minimum job fee." },
  ],
};

const copies: Record<Locale, HousePaintingCopy> = {
  en,
  "zh-hant": { ...en, title: "房屋油漆報價計算器 | zaps.work", description: "估算油漆、人工、間接成本、毛利與可寄給客戶的房屋油漆報價。", heading: "房屋油漆報價計算器", intro: "以油漆覆蓋率、人工產能、現場狀況與目標毛利，建立清楚的房屋油漆報價。", jobDetails: "工程資料", paintPlan: "油漆與材料", labor: "人工規劃", pricing: "定價", projectType: "工程類型", interior: "室內", exterior: "室外", area: "可上漆面積", coats: "塗層數", rooms: "房間數", condition: "表面狀況", good: "良好", standard: "一般", repairHeavy: "需較多修補", coveragePerContainer: "每桶覆蓋面積", paintPrice: "每桶油漆價格", wastePercent: "油漆損耗", sundriesCost: "耗材與保護", productionRate: "每人每小時產能", laborRate: "完整人工時薪", crewSize: "團隊人數", prepCost: "額外前置成本", travelCost: "交通", overheadPercent: "人工間接成本", targetMargin: "目標毛利", minimumFee: "最低工程費", taxRate: "稅額", targetQuote: "目標報價", directCost: "直接成本", profit: "利潤", paint: "油漆", laborCost: "人工", overhead: "間接成本", onSiteHours: "現場工時", paintContainers: "油漆桶數", quoteBreakdown: "報價明細", printOrSave: "列印／儲存 PDF", exportCsv: "匯出 CSV", viewQuote: "查看報價", methodologyTitle: "用自己的產能建立報價", methodologyBody: "估價依可上漆面積、塗層、損耗、覆蓋率、房間準備、產能、表面狀況、人工、間接成本、固定成本、最低工程費、目標毛利與稅額計算，並非市場均價建議。", faqTitle: "房屋油漆報價問題" },
  de: { ...en, title: "Angebotsrechner für Hausanstriche | zaps.work", description: "Farbe, Arbeit, Gemeinkosten, Marge und ein Kundenangebot für Hausanstriche kalkulieren.", heading: "Angebotsrechner für Hausanstriche", intro: "Erstellen Sie ein Angebot aus Deckkraft, Arbeitsleistung, Zustand und Zielmarge.", jobDetails: "Auftragsdaten", paintPlan: "Farbe und Material", labor: "Arbeitsplan", pricing: "Preisgestaltung", projectType: "Projektart", interior: "Innen", exterior: "Außen", area: "Streichfläche", coats: "Anstriche", rooms: "Räume", condition: "Oberflächenzustand", good: "Gut", standard: "Standard", repairHeavy: "Reparaturintensiv", coveragePerContainer: "Deckkraft je Gebinde", paintPrice: "Farbpreis je Gebinde", wastePercent: "Farbverlust", sundriesCost: "Verbrauchsmaterial & Schutz", productionRate: "Leistung je Malerstunde", laborRate: "Vollständiger Lohnsatz", crewSize: "Teamgröße", prepCost: "Zusätzliche Vorbereitung", travelCost: "Anfahrt", overheadPercent: "Lohn-Gemeinkosten", targetMargin: "Zielmarge", minimumFee: "Mindestauftragswert", taxRate: "Steuer", targetQuote: "Zielangebot", directCost: "Direktkosten", profit: "Gewinn", paint: "Farbe", laborCost: "Arbeit", overhead: "Gemeinkosten", onSiteHours: "Stunden vor Ort", paintContainers: "Farbgebinde", quoteBreakdown: "Angebotsaufschlüsselung", printOrSave: "Drucken / PDF speichern", exportCsv: "CSV exportieren", viewQuote: "Angebot anzeigen", methodologyTitle: "Angebot aus Ihrer eigenen Leistung", faqTitle: "Fragen zum Malerangebot" },
  ja: { ...en, title: "住宅塗装見積もり計算機 | zaps.work", description: "塗料、人件費、間接費、利益率から住宅塗装の見積もりを作成します。", heading: "住宅塗装見積もり計算機", intro: "塗料の塗布面積、作業生産性、現場状態、目標利益率から明確な見積もりを作成します。", jobDetails: "工事内容", paintPlan: "塗料と材料", labor: "人員計画", pricing: "価格設定", projectType: "工事種別", interior: "室内", exterior: "屋外", area: "塗装面積", coats: "塗り回数", rooms: "部屋数", condition: "下地の状態", good: "良好", standard: "標準", repairHeavy: "補修多め", coveragePerContainer: "容器あたりの塗布面積", paintPrice: "塗料容器単価", wastePercent: "塗料ロス", sundriesCost: "副資材・養生", productionRate: "職人1時間あたりの生産性", laborRate: "実質人件費単価", crewSize: "人数", prepCost: "追加下地処理費", travelCost: "移動費", overheadPercent: "人件費間接費", targetMargin: "目標利益率", minimumFee: "最低工事費", taxRate: "税", targetQuote: "見積もり金額", directCost: "直接原価", profit: "利益", paint: "塗料", laborCost: "人件費", overhead: "間接費", onSiteHours: "現場時間", paintContainers: "塗料容器", quoteBreakdown: "見積もり内訳", printOrSave: "印刷 / PDF保存", exportCsv: "CSV出力", viewQuote: "見積もりを見る", methodologyTitle: "自社の生産性から見積もる", faqTitle: "住宅塗装見積もりの質問" },
  es: { ...en, title: "Calculadora de presupuestos de pintura de casas | zaps.work", description: "Calcula pintura, mano de obra, costes indirectos, margen y un presupuesto para pintura residencial.", heading: "Calculadora de presupuestos de pintura residencial", intro: "Convierte cobertura, productividad, estado de la superficie y margen objetivo en un presupuesto claro.", jobDetails: "Datos del trabajo", paintPlan: "Pintura y materiales", labor: "Plan de mano de obra", pricing: "Precios", projectType: "Tipo de proyecto", interior: "Interior", exterior: "Exterior", area: "Superficie pintable", coats: "Manos", rooms: "Habitaciones", condition: "Estado de la superficie", good: "Bueno", standard: "Estándar", repairHeavy: "Con mucha reparación", coveragePerContainer: "Cobertura por envase", paintPrice: "Precio por envase", wastePercent: "Merma de pintura", sundriesCost: "Consumibles y protección", productionRate: "Producción por pintor-hora", laborRate: "Tarifa laboral completa", crewSize: "Tamaño del equipo", prepCost: "Preparación adicional", travelCost: "Desplazamiento", overheadPercent: "Indirectos de mano de obra", targetMargin: "Margen objetivo", minimumFee: "Tarifa mínima", taxRate: "Impuesto", targetQuote: "Presupuesto objetivo", directCost: "Coste directo", profit: "Beneficio", paint: "Pintura", laborCost: "Mano de obra", overhead: "Indirectos", onSiteHours: "Horas en obra", paintContainers: "Envases de pintura", quoteBreakdown: "Desglose", printOrSave: "Imprimir / guardar PDF", exportCsv: "Exportar CSV", viewQuote: "Ver presupuesto", methodologyTitle: "Presupuesto con tu propia productividad", faqTitle: "Preguntas sobre presupuestos de pintura" },
  fr: { ...en, title: "Calculateur de devis de peinture de maison | zaps.work", description: "Estimez peinture, main-d’œuvre, frais indirects, marge et devis de peinture résidentielle.", heading: "Calculateur de devis de peinture résidentielle", intro: "Transformez rendement, productivité, état des surfaces et marge cible en devis clair.", jobDetails: "Détails du chantier", paintPlan: "Peinture et matériaux", labor: "Plan de main-d’œuvre", pricing: "Tarification", projectType: "Type de chantier", interior: "Intérieur", exterior: "Extérieur", area: "Surface à peindre", coats: "Couches", rooms: "Pièces", condition: "État de la surface", good: "Bon", standard: "Standard", repairHeavy: "Réparations importantes", coveragePerContainer: "Rendement par contenant", paintPrice: "Prix par contenant", wastePercent: "Perte de peinture", sundriesCost: "Fournitures et protection", productionRate: "Rendement par peintre-heure", laborRate: "Taux de main-d’œuvre chargé", crewSize: "Taille de l’équipe", prepCost: "Préparation supplémentaire", travelCost: "Déplacement", overheadPercent: "Frais indirects de main-d’œuvre", targetMargin: "Marge cible", minimumFee: "Forfait minimum", taxRate: "Taxe", targetQuote: "Devis cible", directCost: "Coût direct", profit: "Bénéfice", paint: "Peinture", laborCost: "Main-d’œuvre", overhead: "Frais indirects", onSiteHours: "Heures sur site", paintContainers: "Contenants de peinture", quoteBreakdown: "Détail du devis", printOrSave: "Imprimer / enregistrer PDF", exportCsv: "Exporter CSV", viewQuote: "Voir le devis", methodologyTitle: "Un devis issu de votre productivité", faqTitle: "Questions sur les devis de peinture" },
  "pt-br": { ...en, title: "Calculadora de orçamento de pintura residencial | zaps.work", description: "Calcule tinta, mão de obra, custos indiretos, margem e orçamento de pintura residencial.", heading: "Calculadora de orçamento de pintura residencial", intro: "Transforme cobertura, produtividade, estado da superfície e margem desejada em um orçamento claro.", jobDetails: "Dados do serviço", paintPlan: "Tinta e materiais", labor: "Plano de mão de obra", pricing: "Precificação", projectType: "Tipo de projeto", interior: "Interno", exterior: "Externo", area: "Área pintável", coats: "Demãos", rooms: "Cômodos", condition: "Condição da superfície", good: "Boa", standard: "Padrão", repairHeavy: "Muito reparo", coveragePerContainer: "Cobertura por embalagem", paintPrice: "Preço por embalagem", wastePercent: "Perda de tinta", sundriesCost: "Consumíveis e proteção", productionRate: "Produção por pintor-hora", laborRate: "Custo completo da mão de obra", crewSize: "Equipe", prepCost: "Preparo adicional", travelCost: "Deslocamento", overheadPercent: "Indiretos de mão de obra", targetMargin: "Margem desejada", minimumFee: "Valor mínimo", taxRate: "Imposto", targetQuote: "Orçamento alvo", directCost: "Custo direto", profit: "Lucro", paint: "Tinta", laborCost: "Mão de obra", overhead: "Indiretos", onSiteHours: "Horas no local", paintContainers: "Embalagens de tinta", quoteBreakdown: "Detalhamento", printOrSave: "Imprimir / salvar PDF", exportCsv: "Exportar CSV", viewQuote: "Ver orçamento", methodologyTitle: "Orçamento da sua produtividade", faqTitle: "Dúvidas sobre orçamento de pintura" },
  ko: { ...en, title: "주택 도장 견적 계산기 | zaps.work", description: "도료, 인건비, 간접비, 마진과 고객용 주택 도장 견적을 계산하세요.", heading: "주택 도장 견적 계산기", intro: "도료 도포 면적, 작업 생산성, 표면 상태와 목표 마진으로 명확한 주택 도장 견적을 만드세요.", jobDetails: "작업 정보", paintPlan: "도료 및 자재", labor: "인력 계획", pricing: "가격 설정", projectType: "작업 유형", interior: "실내", exterior: "실외", area: "도장 면적", coats: "도장 횟수", rooms: "방 수", condition: "표면 상태", good: "양호", standard: "표준", repairHeavy: "보수 많음", coveragePerContainer: "용기당 도포 면적", paintPrice: "도료 용기 단가", wastePercent: "도료 손실", sundriesCost: "소모품 및 보양", productionRate: "작업자 시간당 생산성", laborRate: "총 인건비 단가", crewSize: "팀 규모", prepCost: "추가 바탕 처리", travelCost: "이동", overheadPercent: "인건비 간접비", targetMargin: "목표 마진", minimumFee: "최소 작업비", taxRate: "세금", targetQuote: "목표 견적", directCost: "직접 비용", profit: "이익", paint: "도료", laborCost: "인건비", overhead: "간접비", onSiteHours: "현장 시간", paintContainers: "도료 용기", quoteBreakdown: "견적 내역", printOrSave: "인쇄 / PDF 저장", exportCsv: "CSV 내보내기", viewQuote: "견적 보기", methodologyTitle: "자체 생산성으로 만드는 견적", faqTitle: "주택 도장 견적 질문" },
};

export function getHousePaintingCopy(locale: Locale) { return copies[locale]; }
