import type { Locale } from "./config";

export type NewToolKind = "freelance" | "cnc" | "lawn-care";
export type NewToolCopy = { title: string; description: string; heading: string; intro: string; methodTitle: string; methodBody: string; faqTitle: string; faq: Array<{ question: string; answer: string }> };
const english: Record<NewToolKind, NewToolCopy> = {
  freelance: { title: "Freelance Job Quote Calculator | zaps.work", description: "Price freelance work from hours, revisions, rush work, costs, margin, and minimum fee.", heading: "Freelance Job Quote Calculator", intro: "Turn scope hours, revisions, rush work, and your target margin into a clear freelance quote.", methodTitle: "Quote your own scope", methodBody: "The estimate uses the hours, revision allowance, fixed costs, rush surcharge, target margin, minimum fee, and tax you enter. It does not recommend a market rate.", faqTitle: "Freelance quote questions", faq: [{ question: "How are revisions included?", answer: "Revision count multiplied by expected hours is added to your baseline scope before pricing." }, { question: "Is a rush fee a cost?", answer: "No. It is applied after the margin floor as an explicit premium for compressed scheduling and risk." }] },
  cnc: { title: "CNC Machining Cost Calculator | zaps.work", description: "Estimate CNC material, programming, setup, machine, labor, tooling, batch, margin, and quote cost.", heading: "CNC Machining Cost Calculator", intro: "Price a 3-axis CNC milling job from stock material, programming, setup, cycle time, labor, tooling, and batch size.", methodTitle: "Price the batch, then the part", methodBody: "The estimate allocates programming, setup, machine time, inspection, material scrap, tooling, finishing, target margin, minimum fee, and tax across the selected quantity.", faqTitle: "CNC cost questions", faq: [{ question: "What CNC process does this cover?", answer: "This first version is for manually estimated 3-axis milling work. Enter your own CAM and shop assumptions." }, { question: "Does it create a machining process?", answer: "No. It turns the times and costs you provide into a transparent quote; it does not replace CAM or process planning." }] },
  "lawn-care": { title: "Lawn Care Quote Calculator | zaps.work", description: "Estimate lawn service labor, condition, equipment, travel, add-ons, margin, and a customer-ready quote.", heading: "Lawn Care Quote Calculator", intro: "Turn mowable area, grass condition, crew production, equipment, and your target margin into a lawn service quote.", methodTitle: "Price the route with your own production", methodBody: "The estimate uses mowable area, grass condition, crew production, labor, equipment, travel, add-ons, overhead, target margin, minimum fee, and tax.", faqTitle: "Lawn service quote questions", faq: [{ question: "Why does grass condition change the quote?", answer: "Condition changes expected crew time. Define light, standard, and overgrown consistently for your own route." }, { question: "Can I quote add-ons?", answer: "Yes. Enter a fixed add-on amount for services such as edging, cleanup, hedge trimming, or green-waste handling." }] },
};
const translatedNames: Record<Exclude<Locale, "en">, Record<NewToolKind, { heading: string; intro: string }>> = {
  "zh-hant": { freelance: { heading: "自由工作者報價計算器", intro: "以工作時數、修改、急件與目標毛利建立清楚的自由工作者報價。" }, cnc: { heading: "CNC 加工成本計算器", intro: "以材料、編程、設定、機時、人工、刀具與批量建立 CNC 報價。" }, "lawn-care": { heading: "草坪服務報價計算器", intro: "以草坪面積、草況、團隊產能、設備與目標毛利建立服務報價。" } },
  de: { freelance: { heading: "Angebotsrechner für Freelancer", intro: "Erstellen Sie ein Angebot aus Aufwand, Korrekturen, Eilauftrag und Zielmarge." }, cnc: { heading: "CNC-Bearbeitungskostenrechner", intro: "Kalkulieren Sie CNC-Aufträge aus Material, Programmierung, Rüsten, Maschinenzeit und Stückzahl." }, "lawn-care": { heading: "Angebotsrechner für Rasenpflege", intro: "Erstellen Sie ein Rasenpflegeangebot aus Fläche, Zustand, Teamleistung und Marge." } },
  ja: { freelance: { heading: "フリーランス案件見積もり計算機", intro: "作業時間、修正、特急対応、目標利益率から明確な見積もりを作成します。" }, cnc: { heading: "CNC加工コスト計算機", intro: "材料、プログラム、段取り、加工時間、工具、数量からCNC見積もりを作成します。" }, "lawn-care": { heading: "芝生サービス見積もり計算機", intro: "面積、芝の状態、チーム生産性と目標利益率からサービス見積もりを作成します。" } },
  es: { freelance: { heading: "Calculadora de presupuestos freelance", intro: "Convierte horas, revisiones, urgencia y margen objetivo en un presupuesto freelance claro." }, cnc: { heading: "Calculadora de costes de mecanizado CNC", intro: "Calcula trabajos CNC con material, programación, preparación, máquina, mano de obra y lote." }, "lawn-care": { heading: "Calculadora de presupuestos de jardinería", intro: "Convierte superficie, estado del césped, producción y margen en un presupuesto de servicio." } },
  fr: { freelance: { heading: "Calculateur de devis freelance", intro: "Transformez heures, révisions, urgence et marge cible en devis freelance clair." }, cnc: { heading: "Calculateur de coût d’usinage CNC", intro: "Chiffrez un travail CNC avec matière, programmation, réglage, machine, main-d’œuvre et quantité." }, "lawn-care": { heading: "Calculateur de devis d’entretien de pelouse", intro: "Transformez surface, état du gazon, productivité et marge en devis de service." } },
  "pt-br": { freelance: { heading: "Calculadora de orçamento freelancer", intro: "Transforme horas, revisões, urgência e margem desejada em um orçamento freelancer claro." }, cnc: { heading: "Calculadora de custos de usinagem CNC", intro: "Calcule trabalhos CNC com material, programação, preparação, máquina, mão de obra e lote." }, "lawn-care": { heading: "Calculadora de orçamento de gramado", intro: "Transforme área, condição do gramado, produtividade e margem em um orçamento de serviço." } },
  ko: { freelance: { heading: "프리랜서 작업 견적 계산기", intro: "작업 시간, 수정, 긴급 작업과 목표 마진으로 명확한 프리랜서 견적을 만드세요." }, cnc: { heading: "CNC 가공 비용 계산기", intro: "재료, 프로그래밍, 설정, 기계 시간, 인건비와 수량으로 CNC 견적을 만드세요." }, "lawn-care": { heading: "잔디 관리 견적 계산기", intro: "면적, 잔디 상태, 팀 생산성과 목표 마진으로 서비스 견적을 만드세요." } },
};
export function getNewToolCopy(locale: Locale, kind: NewToolKind) { const base = english[kind]; if (locale === "en") return base; const translated = translatedNames[locale][kind]; return { ...base, title: `${translated.heading} | zaps.work`, description: translated.intro, heading: translated.heading, intro: translated.intro }; }
