import type { Metadata } from "next";
import { GuideArticle, type GuideFaq, type GuideTocItem } from "@/components/guide-article";
import { buildMetadata } from "@/lib/seo";

const title = "How to Price House Cleaning Jobs: Hours, Costs & Margin";
const description = "Build a house cleaning estimate from property scope, cleaner-hours, labor, overhead, supplies, travel, add-ons, minimum fees, and target margin.";
const faq: GuideFaq[] = [{ question: "Should house cleaning be priced hourly or as a flat rate?", answer: "Estimate internally with cleaner-hours and costs. When the scope is clear, a flat customer quote is usually easier to understand and rewards efficient work." }, { question: "How do I estimate how long a cleaning job will take?", answer: "Divide cleanable area by your measured production rate, then adjust for property type, rooms, standard or deep scope, visit frequency, and actual difficulty." }, { question: "How many cleaner-hours is a two-person crew working for two hours?", answer: "Four cleaner-hours. Crew size changes the expected time on site, but it does not reduce the total labor consumed by the job." }, { question: "Should recurring cleaning receive a discount?", answer: "Only when repeat visits genuinely reduce sales, setup, or cleaning time. Recalculate the actual margin after applying the discount." }];
const toc: GuideTocItem[] = [{ id: "scope", label: "Define scope" }, { id: "hours", label: "Estimate cleaner-hours" }, { id: "costs", label: "Add all costs" }, { id: "pricing", label: "Set the price" }, { id: "example", label: "Worked example" }, { id: "quote", label: "Write the quote" }];
export const metadata: Metadata = buildMetadata({ locale: "en", path: "guides/how-to-price-house-cleaning-jobs", title, description });

export default function Page() {
  return <GuideArticle title={title} description={description} published="2026-07-13" updated="2026-07-13" readingTime="9 min read" slug="how-to-price-house-cleaning-jobs" toolHref="/calculators/cleaning-quote-generator" toolLabel="Open cleaning quote generator" toc={toc} faq={faq}>
    <p className="guide-lead">A sustainable cleaning quote starts with scope and total cleaner-hours, not a copied local average. Add labor, overhead, supplies, travel, and optional services before applying margin and a minimum service charge.</p>
    <div className="guide-callout"><strong>The core formula</strong><code>Cleaning quote = (labor + overhead + supplies + travel + add-on costs) ÷ (1 − target margin)</code><p>Apply any first-clean surcharge and recurring discount, compare with the minimum service fee, then add applicable tax.</p></div>
    <h2 id="scope">1. Define the cleaning scope before pricing</h2><p>Record property type, cleanable area, bedrooms, bathrooms, cleaning type, frequency, and overall condition. Two homes with the same area can require different hours because of clutter, grease, pet hair, stairs, access, or detailed surfaces.</p><p>State whether oven, fridge, interior windows, cabinet interiors, laundry, furniture moving, and waste removal are included. A clear list prevents unpriced work from becoming an assumed free extra.</p>
    <h2 id="hours">2. Estimate total cleaner-hours from production rate</h2><p>Production rate should come from your own completed jobs. Total cleaner-hours means labor across the whole team: two cleaners working for two hours equals four cleaner-hours.</p><pre><code>Base cleaner-hours = max(0.25, area ÷ production rate + room adjustment) × property × cleaning type × difficulty × frequency</code></pre><p>The calculator converts area and production rate together when you switch units. It also scales starter cost assumptions when currency changes, but you should replace every starter value with your actual wages, overhead, travel, and minimum fee.</p><p>Experienced operators can override the area estimate with manual cleaner-hours when the property is unusual.</p>
    <h2 id="costs">3. Include every job cost</h2><p>Loaded labor cost includes wage and employer burden. Overhead per cleaner-hour can recover insurance, software, administration, equipment, vehicle costs, and non-billable time.</p><p>Add supplies, travel, parking, and the time required by every selected add-on. A fixed-price add-on still consumes labor, so preserve that cost when checking margin.</p>
    <h2 id="pricing">4. Apply margin, minimum fee, and discounts</h2><p>Target margin is not the same as adding the same percentage to cost. Divide job cost by one minus the target margin. Use a minimum service fee to protect small visits.</p><pre><code>Target price = job cost ÷ (1 − target margin)</code></pre><p>First-clean surcharges and recurring discounts should represent a real change in resources. Always check the actual margin after the adjustment.</p>
    <h2 id="example">5. Worked house cleaning estimate</h2><p>A standard 1,800-square-foot cleaning at 500 square feet per cleaner-hour needs 3.6 cleaner-hours. A two-person crew is expected to spend about 1.8 hours on site.</p><p>Loaded labor is 86.40, overhead is 36, supplies are 12, and travel is 15, for a job cost of 149.40. At a 30% target margin, the pre-tax flat quote is 213.43.</p>
    <h2 id="quote">6. Write a quote that avoids scope disputes</h2><p>List the property, cleaning type, frequency, included scope, selected add-ons, customer preparation, exclusions, total, tax, quote validity, and expected service window.</p><p>Do not promise results for stains or conditions that cannot be assessed in advance. If the actual property differs materially from the described scope, get approval before changing the work or price.</p>
    <h2>House cleaning quote checklist</h2><ul><li>Confirm property, area, cleaning type, frequency, and condition.</li><li>Use a production rate from your own completed jobs.</li><li>Separate total cleaner-hours from on-site duration.</li><li>Add loaded labor, overhead, supplies, and travel.</li><li>Estimate every selected add-on.</li><li>Apply the target-margin formula correctly.</li><li>Compare with the minimum fee and recheck margin after discounts.</li><li>Document scope, exclusions, service window, and quote validity.</li></ul>
  </GuideArticle>;
}
